Brings Borers Back
yogstation13/yogstation-2017- pull request #1089
Opened 2016-10-24 02:52 UTC by Super3222

Refer to issue https://github.com/yogstation13/yogstation/pull/747 which was left up for 22 days, never got an answer, and than was closed.

I may or may not go back to change a few things myself unless someone points out something because I'm exhausted and coding at the same time.

:cl:
tweak: Tickets now support captive brains.
tweak: Borers are back.
/:cl:

2016-10-24 02:53 UTC, ShadowDeath6 commented
wew

2016-10-24 04:02 UTC, Time-Green commented
Re-add borer removal surgery.

2016-10-24 04:20 UTC, ShadowDeath6 commented
nothing about borers were ever removed other than the event firing, time

2016-10-24 05:32 UTC, Time-Green commented
Well, surgery doesn't work.
I've gotten surgery to get it removed, both organ manip and removal of embedded objects.

You can't surgicly remove them.

2016-10-24 05:33 UTC, ShadowDeath6 commented
you need to aim for brain and it just takes the borer out instead

2016-10-24 05:35 UTC, Time-Green commented
Really? Could you fix that?
How is anyone supposed to know that removing someones brain doesn't remove their brain?

2016-10-24 05:36 UTC, ShadowDeath6 commented
game sense :^)

2016-10-24 08:09 UTC, Ephemeralis commented
"Something's living in this man's brain, lets try and dissect it by removing his brain."

HOLY SHIT ITS A BORER FUK

Sounds like space station 13 alright.

2016-10-24 10:58 UTC, Yewmi commented
@ShadowDeath6 I have to agree with @Time-Green, that sounds counter-intuitive as counter-intuitive can be.

2016-10-24 12:52 UTC, AdamElTablawy commented
it also sounds hilarious imo

'hey doc can i get borged'

'yeah sure hold on a sec bro'

'does surgery'

HOLY SHIT IT'S A BORER OH GOD  HE-everything is fine humans. do not fear.

2016-10-24 15:27 UTC, X-TheDark commented
Actually, organ manipulation surgery for borer removal IS NOT ported.
See old code (has borer removal) : https://github.com/yogstation13/yogstation-old/blob/master/code/modules/surgery/organ_manipulation.dm#L68
Current code (doesn't have) : https://github.com/yogstation13/yogstation/blob/master/code/modules/surgery/organ_manipulation.dm#L70

2016-10-24 19:26 UTC, Super3222 commented
In the last commit:
- Implements a new organ called a "borer vessel" which is virtually, a borers home. When removed, removes the borer.
- Everything is like it should be. The only exception is that during organ manipulation, when someone opens up your head they'll see a borer.
- Basically a less hacky way for borer surgery.
- Borers will also force eject when the brain is removed from their victim.
- The eggsac never leaves with the borer. It's only used to carry variables around while being supported by the organ code.

2016-10-24 19:27 UTC, Super3222 commented
In the last commit:
- Implements a new organ called a "borer vessel" which is virtually, a borers home. When removed, removes the borer.
- One of the things people will see inside of your head (when infected) is a borer vessel.
- Basically a less hacky way for borer surgery.
- Borers will also force eject when the brain is removed from their victim.
- The eggsac never leaves with the borer. It's only used to carry variables around while being supported by the organ code.

2016-10-24 19:29 UTC, X-TheDark commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +/obj/item/organ/borrer_home
borrer?

2016-10-24 20:14 UTC, ShadowDeath6 commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +/obj/item/organ/borrer_home
She borrer me

2016-10-24 21:03 UTC, Time-Green commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +/obj/item/organ/borrer_home
Thats so cute. Give it a cute name. Something like: adorable borer nest

2016-10-25 15:18 UTC, oisin100 commented on code/modules/surgery/organ_manipulation.dm
> +	var/mob/living/simple_animal/borer/borer = null //WARNING!! HACKY CODE ALERT NEEE NOOOH NEEEE NOOOH IT'S OISINS FAULT
;-;

2016-10-25 15:22 UTC, Super3222 commented on code/modules/surgery/organ_manipulation.dm
> +	var/mob/living/simple_animal/borer/borer = null //WARNING!! HACKY CODE ALERT NEEE NOOOH NEEEE NOOOH IT'S OISINS FAULT
You know Oisin I think our minds are in sync. I was JUST looking back at the code 10 minutes ago and realized that I didn't need that variable in the surgery in the first place lmao. Either that or I summoned you

2016-10-29 10:23 UTC, oisin100 requested changes

2016-10-29 10:23 UTC, oisin100 commented on code/modules/mob/living/simple_animal/borer/borer_captive.dm
> +		H << "<span class='danger'>With an immense exertion of will, you regain control of your body!</span>"
Should just use `src` here instead of the typecast.

2016-10-29 10:23 UTC, oisin100 commented on code/modules/mob/living/simple_animal/borer/borer_captive.dm
> +		..()
Huh, There will never be a parent proc here.

2016-10-29 10:23 UTC, oisin100 commented on code/modules/mob/living/simple_animal/borer/borer_captive.dm
> +	var/mob/living/captive_brain/H = src
So... Why is this being typecasted?

2016-10-29 10:23 UTC, oisin100 commented on code/modules/mob/living/simple_animal/borer/borer_captive.dm
> +	H << "<span class='danger'>You begin doggedly resisting the parasite's control (this will take approximately 10 seconds).</span>"
Should just use `src` here instead of the typecast.

2016-10-29 13:25 UTC, Super3222 commented on code/modules/mob/living/simple_animal/borer/borer_captive.dm
> +	var/mob/living/captive_brain/H = src
It was like that when I started making changes. I see the uselessness in it now that you've pointed it out.

2016-10-29 14:10 UTC, oisin100 approved these changes

2016-10-30 00:05 UTC, X-TheDark commented
Welp, let's see if this works.

2016-10-30 00:05 UTC, merged