Adds Pretty Filters for IC chat methods
yogstation13/yogstation-2017- pull request #1251
Opened 2016-11-21 02:42 UTC by utahclock

Refer to issue #0.

### Intent of your Pull Request

Type here what the purpose of your PR is. Also set the issue number above, or delete the line if this PR is not related to an issue. You can type "Fixes issue #6" and issue 6 will be automatically closed as your pull request is merged. Much easier for everyone if you do that.

#### Changelog

:cl:
tweak: tweaks pretty filter to include IC text.
/:cl:

2016-11-21 03:02 UTC, Super3222 commented
admin abuse

2016-11-21 08:25 UTC, Kmc2000 commented
For those that dont know, pretty filters stop you using bigotry

2016-11-21 08:42 UTC, Jc1469 commented
It'd probably be better to just leave IC as it is.  Replacing IC text makes an IC mess if it's set for bigotry.
Other than that, it's just another niche meme admin tool for trolling at the end of a round.

2016-11-21 09:24 UTC, oisin100 commented
If we do this we should alert admins when someone trips a pretty filter.

2016-11-21 12:53 UTC, matskuman5 commented
"If we do this we should alert admins when someone trips a pretty filter."

^^^^^^^^

Otherwise logs are fucked and people can just say "oh it was a joke i just typed in BANMEADMINS and hit enter"

2016-11-21 14:52 UTC, utahclock commented
I understand this is controversial. I suppose I can an admin message trigger. Not sure how to get it to state x said n word which triggered filter. The n word part would be part i would need help with . if any one has ideas.. On how to do that pm me on discord.

2016-11-22 14:36 UTC, monster860 requested changes
You're adding blank lines for 4 no raisin.

2016-11-22 14:36 UTC, monster860 commented on code/modules/mob/say.dm
> +
**screams**

AAAAAAAAAAAA! Too many blank lines!!!

2016-11-22 14:36 UTC, monster860 commented on code/modules/mob/say.dm
> +
**screams**

2016-11-22 14:36 UTC, monster860 commented on code/modules/mob/say.dm
> +
**screams**

2016-11-22 20:51 UTC, Super3222 commented
tbh I don't like it.

2016-11-28 16:15 UTC, Time-Green commented
I see seriously no problem with this?
Do you guys want people to scream F----- out loud? Isn't that against the rules?
Just notify admins if they do.

2016-11-28 16:35 UTC, Super3222 commented
IC chatter shouldn't be hindered. One of the many things to laugh about is someone using that word, and than getting banned for it. Filtering it so unfun, and while it may be against the rules we aren't Nazis, and nobody is going to get triggered over it. I am all for the dedication against slurs and other degrading profanities but if they do get triggered than they should stay off SS13.

At the very least an admin notification should be sent to ASAY. Nothing more

2016-11-30 19:04 UTC, merged