Adds an SCP facility lavaland ruin
yogstation13/yogstation-2017- pull request #1276
Opened 2016-11-23 22:17 UTC by matskuman5

Adds a new lavaland ruin. It's an anomalous object containment site run by NanoTrasen. It was hit by an earthquake a few decades ago and it has fallen to ruin. It holds some dangerous creatures inside, but it's got an open armoury at the end as a reward.

Includes fluff object testing logs!

:cl:
rscadd: A new lavaland ruin has been unearthed!
/:cl:

2016-11-23 22:35 UTC, Super3222 commented
> SCP
> No SCP's on the map
> 0 New mobs

2016-11-23 22:50 UTC, matskuman5 commented
I dont have the coding / spriting skills bby :(

2016-11-23 23:59 UTC, Slinky5890 commented
Once some mobs are sorted out (maybe even just a living statue that activates as a ghost role if someone enters, dunno how doable that is) then i'd definitely be interested in this.

2016-11-24 00:00 UTC, monster860 requested changes

2016-11-24 00:00 UTC, monster860 commented on yogstation.dme
> +#include "_maps\RandomRuins\SpaceRuins\emptyshell.dmm"
AHHH NO THAT IS NOT HOW YOU ADD RUINS!!!!

2016-11-24 00:00 UTC, Stealthkibbler commented
Needs skeletal remains and human remains.

If you cant make any new mobs then dig around in simple_animals for anything that could even slightly add to the ruins. 

As long as its fun for miners to explore and has something cool to find then it generally will be fine, yogs doesn't have any defining expectations or restrictions.

2016-11-24 00:07 UTC, monster860 commented
@matskuman5 

https://github.com/yogstation13/yogstation/blob/master/code/datums/ruins/lavaland.dm

Add your ruin here, revert your yogstation.dme back to what it was before.

2016-11-24 00:18 UTC, Stealthkibbler commented
The paper notes are cool though 👍

2016-11-24 04:21 UTC, AdamElTablawy commented
>kill one old asteroid goliath and not lavaland goliath

>kill one legion

>GET FUCKING AUTORIFLES

are you sERIOUS

2016-11-24 06:33 UTC, matskuman5 commented
You missed the buffed eye carp and the faithless, Adam

2016-11-24 08:36 UTC, Alek2ander commented
You realise miners can... mine? And don't really have a problem with rwalls. It's piss easy to get the loot while avoiding all hazards

2016-11-24 08:55 UTC, RoboticVodka commented
Seriously you only have to just walk around.... Even if you can't get past the Rwalls just go get an RCD, and make a bridge across the lava.

2016-11-24 13:23 UTC, matskuman5 commented
Made the walls unbreakable so you have to go through the enemies to get to the armoury. Added an imp and a christmas tree, plus some skeletal and normal corpses

2016-11-24 14:21 UTC, Time-Green commented
Could you ask someone to resprite a statue into The Sculpture?
![image](https://cloud.githubusercontent.com/assets/7501474/20601600/b67b28e8-b259-11e6-9b8b-9100dc747b9a.png)
I mean, if you're making an SCP facility...

2016-11-24 16:09 UTC, Dragonforcefive commented
Lol. I can just imagine miners getting better weapons then security.

2016-11-24 18:08 UTC, Cruix commented
How did you manage to post the only image on that entire massive website that is not public domain?

2016-11-24 21:46 UTC, monster860 requested changes
https://github.com/yogstation13/yogstation/blob/master/code/datums/ruins/lavaland.dm

Add your ruin here, revert your yogstation.dme back to what it was before.

2016-11-25 08:45 UTC, Stealthkibbler commented
As monster pointed out, ruins are not defined in the dme but rather in lavaland.dm

2016-11-30 23:05 UTC, AdamElTablawy commented
AUTORIFLES

2016-12-18 17:19 UTC, Super3222 commented
Looks nice, but the loot might be a problem. What type of guns are those in the armory?

2017-01-03 14:33 UTC, matskuman5 commented
Yeah this is fucked, I'll probably redo this later but can't be arsed to fix it now

I'll close this

2017-01-03 14:33 UTC, closed without merging