Mining Medics
yogstation13/yogstation-2017- pull request #1360
Opened 2016-12-08 04:14 UTC by Super3222

#### Intent of your Pull Request

Re-introducing Mining Medics: A new position in cargo with the sole objective to keep up to date on the miners well being- the mining medic spends their time at a short ended office within the premises of the mining station.

This is a single person role with a simple basis geared on the basis of putting a paramedic on lavaland. This also constitutes as a rework of the older form of a Mining Medic, which was practically a buddy that followed other miners around the asteroid.

Mining Medics are equipped with special uniforms that contain bio resistance (credit to KMC2000 for the sprite - made about 3-4 or so months ago).
Their locker holds a hand held crew monitor, medical supplies, an alternative costume, and more.

![](http://image.prntscr.com/image/8b451e5b0dee418da1e383e3d67b0c13.png)
![](http://image.prntscr.com/image/83c3c1032e60439a90b0233f35c4062f.png)

To the trained eye, their office is lacking a few things here and there that could benefit the miners a lot. Via a cloning machine, cyro tube, or even a surgery table. Albeit, those things do sound nice - that's not what the Mining Medic is for. I am not adding an entire medbay section to the mining station.

While the Mining Medic surely restores people back to health with their sleeper, something like cloning or implanting legion souls has to be handled back on the station. So not every last thing gets knotted down, and lavaland is still treacherous. I am interested in adding at least a defibrillator somewhere in their office however.

Checklist:
- [ ] Make some more patches to their access levels.

Disclaimer: This was a pretty old project that I moved on from in the past, but I've found the time to make the final adjustments here and there to make it at least presentable and hopefully it'll be brought into the game for players to enjoy.

2016-12-08 04:33 UTC, ShadowDeath6 commented
where's the mining medic hood you grr

2016-12-08 08:10 UTC, matskuman5 commented
Give them dwfibs

2016-12-08 15:58 UTC, Time-Green commented
Give them a mop. In-case a miner is a little to broken.

2016-12-09 21:24 UTC, Super3222 commented
This is ready for review.

2016-12-09 22:13 UTC, ShadowDeath6 commented
where is the hood at

2016-12-10 04:01 UTC, Super3222 commented
In the last commit(s):
- Mining Medics now have access to the morgue.
- Mining Medics do NOT have access to the station's surgery room.
- Mining Medics STILL have their mining access. That commit message was incorrect

2016-12-12 02:38 UTC, ShadowDeath6 commented on code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
> +	if(prob(5))
secret nerf grr

2016-12-19 19:56 UTC, Cruix requested changes

2016-12-19 19:56 UTC, Cruix commented on code/game/objects/items/devices/radio/headset.dm
> +/obj/item/device/radio/headset_medcargo
This needs to be /obj/item/device/radio/headset/medcargo

2016-12-19 19:56 UTC, Cruix commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	new /obj/item/weapon/defibrillator(src)
This needs to be /obj/item/weapon/defibrillator/loaded

2016-12-19 19:56 UTC, Cruix commented on code/modules/jobs/job_types/medical.dm
> +	minimal_access = list(access_medical, access_morgue, access_mining, access_mint, access_mining_station, access_mailsorting, access_mineral_storeroom)
access_cargo is for the cargo bay, access_mailsorting is for the cargo front office. Both should have access_mailsorting, and minimal access at least should not have access_cargo.

2016-12-19 19:57 UTC, Cruix commented
Also you did not push the .dmi changes, so there are no new icons.

2016-12-22 16:36 UTC, Super3222 commented
![](http://image.prntscr.com/image/7d9e6f800a4a4403b040efa1feb90e7b.png)
A vigilant mining medic enjoys his first and last glimpses of calmness before the miners find their way to anarchy.

2016-12-22 17:35 UTC, ShadowDeath6 commented
Shower > washing machine

2016-12-22 18:22 UTC, Super3222 commented
The room's not getting a shower though. Washing machine gives it an at-home feel which is what the room is trying to accomplish.

2016-12-22 18:33 UTC, ShadowDeath6 commented
You say as it's a dirty room with high level medical equipment and metal floors

2016-12-22 21:27 UTC, Super3222 commented
Yeah, and there's more people who play this game than just you, Shadow. I could care less about putting a shower there instead of a washing machine. I think a washing machine is nice, so I put it there. I'm not looking for what cleans your dirty shoes the fastest.

2016-12-22 22:05 UTC, ShadowDeath6 commented
washing machine needs a buff imho

2016-12-27 16:38 UTC, Cruix approved these changes

2016-12-27 21:53 UTC, Super3222 commented
@Cruix Can this be merged, and updated into the game today? I missed that opportunity by a second this morning after being pushed off a cliff by map merges, and this is my oldest PR still open.

2016-12-27 21:56 UTC, Cruix commented
Yes just let me make sure the atvs work

2016-12-27 22:35 UTC, merged