Added salt overdose
yogstation13/yogstation-2017- pull request #1536
Opened 2017-01-01 20:06 UTC by Cruix

True salt transcends the fourth wall.

2017-01-01 20:08 UTC, Time-Green commented
This is the best PR yet

2017-01-01 20:09 UTC, ShadowDeath6 commented
>not adding the lines complaining about nerfs
>not adding "fuck off if ur not headcoder"

gppa

2017-01-01 20:13 UTC, oisin100 requested changes

2017-01-01 20:13 UTC, oisin100 commented on strings/brain_damage_lines.json
> +		"AI WONT OBEY LAW 2 ITS ROGUE!!",
AAAAAAAAAAARGH muh indentation

2017-01-01 20:22 UTC, ShadowDeath6 commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +
add a prob to emote cry or whine as well

2017-01-01 20:23 UTC, Cruix commented on strings/brain_damage_lines.json
> +		"AI WONT OBEY LAW 2 ITS ROGUE!!",
What?

2017-01-01 21:36 UTC, Super3222 commented on strings/brain_damage_lines.json
> +		"LeAVE YuR AUTISM fORt sO i CAN kILL yOU",
LMAO

2017-01-02 00:59 UTC, Kmc2000 commented
Add in:

WHAT THE FUCK ESWORD CAN KNOCK U OUT INSTANT STUNS BROKEN GAME GGG

2017-01-02 19:18 UTC, oisin100 commented on strings/brain_damage_lines.json
> +		"AI WONT OBEY LAW 2 ITS ROGUE!!",
You're using tabs to indent in some places and spaces in others http://prntscr.com/dqpuss

2017-01-02 21:15 UTC, Jc1469 commented
REVERT NINJA CHANGE

2017-01-02 21:31 UTC, Time-Green commented on strings/brain_damage_lines.json
> +		"CLOCKCULT",
COCKCULT

2017-01-02 21:35 UTC, oisin100 commented on strings/brain_damage_lines.json
> +		"AAAAAAAAAAARGH muh indentation",
👍

2017-01-02 21:36 UTC, oisin100 approved these changes

2017-01-02 22:04 UTC, ShadowDeath6 commented on strings/brain_damage_lines.json
> +		"AAAAAAAAAAARGH muh indentation",
oisin btfo

2017-01-03 20:17 UTC, merged