suiciding with a scythe actually beheads you now
yogstation13/yogstation-2017- pull request #1570
Opened 2017-01-04 02:59 UTC by ShadowDeath6

fixes #1555 
dedicated to oisin for adding new emojis to discord

:cl: Suicide Assistance Hotline
bugfix: You now correctly suicide with gardening scythes. Try it out!
/:cl:

2017-01-04 03:06 UTC, Super3222 requested changes
Nothing big. Needs to replace the use of forloops with helpers that were designed for the object they're using.

2017-01-04 03:06 UTC, Super3222 commented on code/modules/hydroponics/hydroitemdefines.dm
> +		for(var/obj/item/bodypart/B in H.bodyparts)
typecast this, and use `get_bodypart` instead of using a for loop.

2017-01-04 03:06 UTC, Super3222 commented on code/modules/hydroponics/hydroitemdefines.dm
> +			if(B.body_zone == "head")
this needs to be handled when you typecast it.

2017-01-05 17:46 UTC, Super3222 approved these changes

2017-01-05 17:47 UTC, Super3222 requested changes

2017-01-05 17:47 UTC, Super3222 commented on code/modules/hydroponics/hydroitemdefines.dm
> +		B = H.get_bodypart("head")
This needs to be combined with the line above it. I don't understand why it's outside.

2017-01-05 22:20 UTC, ShadowDeath6 commented on code/modules/hydroponics/hydroitemdefines.dm
> +		B = H.get_bodypart("head")
I looked at other code and that's how it was done, fixing

2017-01-06 02:40 UTC, Super3222 approved these changes

2017-01-07 21:14 UTC, merged