Adds amazing red dragon pet. And maybe something else.
yogstation13/yogstation-2017- pull request #1681
Opened 2017-01-18 17:46 UTC by Jc1469

Waiting for proper icon before I can add it somewhere.  But admins can feel free to spawn it xd. It looks gr8.  I suggest spawning the /pet though, not the hostile one.

:cl:
rscadd: A new dragon is in town.. and it's red.
/:cl:

2017-01-18 21:03 UTC, ShadowDeath6 commented
Is this a sprite request

2017-01-18 21:05 UTC, Jc1469 commented
One should already be being made. Or I'll just make it myself.  This is just here so I don't forget about it because come friday I'm going to be prettttty busy for a week or so.

2017-01-18 21:11 UTC, ShadowDeath6 commented on code/modules/mob/living/simple_animal/friendly/dragon.dm
> +	if(M.a_intent == "harm")
Eh......................... This seems like a consistency issue and people will think you can't attack it. I'd rather it have a damage threshold that ignores punches over this.

2017-01-18 21:13 UTC, ShadowDeath6 commented on code/modules/mob/living/simple_animal/hostile/reddragon.dm
> +	color = "#FF0000"
We already have all these for ash drake

2017-01-18 21:14 UTC, ShadowDeath6 commented
There are a lot of similarities to ash drake, I'd just make the hostile one a subtype if you're going to use so much of it

2017-01-18 21:15 UTC, Jc1469 commented on code/modules/mob/living/simple_animal/friendly/dragon.dm
> +	if(M.a_intent == "harm")
Considering it'll eat basically everything you try to hit it with regardless, the point is for people to not be able to bully it.
I made it so it can only be damaged by thrown/ranged weapons.  Bigboy form is much less invincible, pet form is just a glorified trashcan that doesn't like mimekitty and turns into a baby ashdrake with weaker ashdrake moves when it gets its collar emagged off.

2017-01-18 21:19 UTC, Jc1469 commented
All of the drake attacks are modified and weakened significantly, and it's also not as bullshit as an ash drake, which is a big part of what I was aiming for.  Trading one emag for an ash drake is pretty insane.  An emag for a worse ashdrake which is adorable, I'd say that's fine, when it dies pretty easily too.

2017-01-18 21:35 UTC, ShadowDeath6 commented on code/modules/mob/living/simple_animal/friendly/dragon.dm
> +				for(var/mob/living/simple_animal/pet/cat/mimekitty/snack in oview(src,3))
Good.

2017-01-18 21:38 UTC, ShadowDeath6 commented
Make sure to add some sort of blacklist so you can't cause bugs with intellicards and eating objective items

2017-01-18 22:27 UTC, Jc1469 commented
I'll get to it all next week. Just add do not merge to this for now. 
Got surgery on friday.

2017-01-19 15:03 UTC, GrayRachnid commented
Since it's a glorified trashcan, make it drop everything it ate when it dies.
And if you're using qdel to transform it, it's going to drop everything it ate when it gets emagged.

2017-01-23 19:04 UTC, X-TheDark commented
I knew I forgot something when I ported the high risk notifications...sorry.

2017-01-23 20:02 UTC, Cruix commented
>Not atomizing PRs

2017-01-24 04:04 UTC, Super3222 requested changes
c/p stuff.
high_risk stuff

2017-01-24 04:04 UTC, Super3222 commented on code/modules/mob/living/simple_animal/hostile/reddragon.dm
> +/mob/living/simple_animal/hostile/reddragon
A lot of it's copy-and-pasted from ashdrakes. If you want an ashdrake, make a subvert, and change number values into variables, and change those variables to the numbers you want in your version of the ashdrake.

2017-01-24 04:04 UTC, Super3222 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +	high_risk = 1
Yeah... some places you're putting this right. Others wrong. As far as I'm considered door remotes, ai intellicard, and etc shouldn't be in this list. It'll fuck up some of the features that already use that variable.

Instead, in conjunction with checking for whether it's a high risk or not, make a check for a blacklist (that you'll need to create in the dragons variables).

2017-01-24 12:22 UTC, Jc1469 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +	high_risk = 1
I should probably add that high_risk was created for and only used for the "high risk item notifications" admin verb, which currently does nothing, because when we rebased, the high_risk var was re-added, but none of the items having it was.

2017-01-24 20:26 UTC, Super3222 approved these changes

2017-01-24 21:03 UTC, ShadowDeath6 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +	high_risk = 1
AI intellicard HOLDING an AI should be considered high risk as it's a traitor steal objective.

2017-02-02 03:43 UTC, Jc1469 commented
its funny. this directly conflicts with my megamegafauna PR.  I guess whoever eventually does/doesn't merge should start with the **mega**fauna one.

2017-03-12 16:27 UTC, closed without merging