Adds the wabbajack to wizard
yogstation13/yogstation-2017- pull request #1697
Opened 2017-01-22 14:32 UTC by Time-Green

Creates a wabbajack statue spawner artefact. Gives this to the wiz for 1 point.

:cl:
rscadd: The wizard federation has started using the wabbajack
/:cl:

2017-01-22 14:46 UTC, AdamElTablawy commented
kinda useless?

2017-01-22 15:27 UTC, Time-Green commented
Well, there's also the wizard spells that turn people into japanese schoolgirl neko's. So I don't see this being more useless then that

2017-01-23 04:03 UTC, Super3222 requested changes
I went ahead, and tested it. It spawns the same two tables.

2017-01-23 04:03 UTC, Super3222 commented on code/game/gamemodes/wizard/artefact.dm
> +	var/obj/structure/table/abductor/wabbajack/left/L = new/obj/structure/table/abductor/wabbajack/left(T_loc)
spawns same table

2017-01-23 04:03 UTC, Super3222 commented on code/game/gamemodes/wizard/artefact.dm
> +	var/obj/structure/table/abductor/wabbajack/right/R = new/obj/structure/table/abductor/wabbajack/left(T_loc)
spawns same table

2017-01-23 04:04 UTC, Super3222 commented
Also... what the heck. The concept is cool until you get to the part where it doesn't do anything at all.

2017-01-23 05:16 UTC, Time-Green commented
Uhm.. it does. Way it works is: 2 people need to get on the table and it starts shooting polymorphs. It seems I made a mistake with the tables, but that only affects the description. It works. I've tested it myself.

2017-01-23 20:51 UTC, Super3222 approved these changes

2017-01-23 20:55 UTC, Super3222 commented
Requiring two people is pretty troublesome for a wizard... eh. Two living people at least.

2017-01-23 21:43 UTC, Time-Green commented
The wabbajack already exists on the special escape shuttle. And within 10 seconds there's 5-10 stacked onto those tables. I also think it MAY fire if it has one, just rarely.
It's kind of a fun thing to keep the crew busy

2017-01-24 03:07 UTC, Super3222 commented
There's nothing wrong with letting it pass, but I doubt that wizards are going to use it compared to the other choices they have.

Honestly, if it was something where the wabbajack was more of a turret that activated every time a living body was forced onto their altar, than that'd make it a really useful weapon (as long as it sensed the wizard as a FRIEND). And at that point - why limit it to the a bolt of polymorph. It should fire bolts of chaos just for  amusement.

2017-01-25 16:50 UTC, AdamElTablawy commented
This is useless

How are you going to get 2 people onto the tables while alive?

What's the point?

Why would anyone bother with this useless thing?

It'd be fine if it was under some sort of 'useless badassery' section but otherwise this is literally both pointless and probably going to kill the wizard trying to use it

2017-01-25 18:00 UTC, Time-Green commented
There's spells that turn people into fucking schoolgirl neko's. Is there a pointless badassery for wiz? Rituals was all I could find.

2017-01-25 21:16 UTC, Super3222 commented
Like I said before, nothing wrong with letting it merge It's just a bad tool, and people aren't going to buy it after seeing it in use.

Also try adding more detail to your changelog message. No one's going to know what you're talking about.

2017-01-26 21:14 UTC, AdamElTablawy commented
@Time-Green There isn't a spell that turns someone into schoolgirl nekos

That's an admin command you dingus

2017-01-26 23:01 UTC, Super3222 commented
If it was a spell, than it'd be apart of the event scroll. Which is useful.

2017-01-29 05:13 UTC, Super3222 commented
Welp. Suit yourself. I've tested this, and it works.

2017-01-29 05:13 UTC, merged