Comms consoles now only work on the station zlevel.
yogstation13/yogstation-2017- pull request #1711
Opened 2017-01-24 16:00 UTC by Jc1469

Not technically a fix as opposed to an outright change, I guess.  but w/e

#1678

:cl:
tweak: We're shit and so are our communications consoles. They now only work on the station.
/:cl:

2017-01-24 16:18 UTC, X-TheDark requested changes
Please use the defines whenever possible. Not a big deal though.

2017-01-24 16:18 UTC, X-TheDark commented on code/game/machinery/computer/communications.dm
> +		if(z != 1)
`if(z != ZLEVEL_STATION)` is what you're looking for

2017-01-24 16:23 UTC, Super3222 requested changes
bool

2017-01-24 16:23 UTC, Super3222 commented on code/game/machinery/computer/communications.dm
> +	var/z_lock = 1//Var that admins can change to 0 if they need to use a comms console for some crap, I dunno.
if this is going to be Boolean use TRUE instead 1.

2017-01-24 16:44 UTC, X-TheDark approved these changes

2017-01-24 20:25 UTC, Super3222 approved these changes

2017-01-25 21:32 UTC, Super3222 commented
Looks good. I would've suggested letting emags break the z lock, but even that would bring up the same problems. In the future, we could make a centcomm version with a broken z lock and etc. Anyway it looks good.

@Cruix

2017-01-25 22:01 UTC, Jc1469 commented
aylmao recall seems pretty detailed to me.  aylmaos and recalling.  it's a good commit name, it gets to the point instantly.

2017-01-25 23:55 UTC, Super3222 commented
The first set of commit names aren't meant to be names. They are meant to get a clear point across to other coders in case they need to experiment, review, or debug earlier code.

2017-01-26 00:42 UTC, Super3222 commented
The first set of commit names aren't meant to be memes. They're meant to get a clear point across to other coders in case they need to experiment, review, or debug earlier code.

2017-01-31 02:44 UTC, merged