nerfs gray's ban list
yogstation13/yogstation-2017- pull request #1715
Opened 2017-01-25 21:48 UTC by Jc1469

makes gray's bans not cause 2 minutes of lag.  probably.
I also removed all the unbanned == 1 from the old code because I'm nice and because there were like 4 PRs on old code removing it :rareparrot:

2017-01-25 21:51 UTC, ShadowDeath6 commented on code/modules/admin/DB_ban/functions.dm
> +			var/unbanned = text2num(select_query.item[10])//Even in integer, we are memes.
afp here we can't let that comment slide

2017-01-25 21:52 UTC, Jc1469 commented on code/modules/admin/DB_ban/functions.dm
> +			var/unbanned = text2num(select_query.item[10])//Even in integer, we are memes.
good because im not done with this yet anyways

2017-01-25 21:59 UTC, Jc1469 commented on code/modules/admin/DB_ban/functions.dm
> +			var/unbanned = text2num(select_query.item[10])//Even in integer, we are memes.
scratch that, im done. we are memes.

2017-01-25 22:11 UTC, oisin100 requested changes

2017-01-25 22:11 UTC, oisin100 commented on code/modules/admin/DB_ban/functions.dm
> +		var/DBQuery/select_query = dbcon.NewQuery("SELECT id, bantime, bantype, reason, job, duration, expiration_time, ckey, a_ckey, unbanned, unbanned_ckey, unbanned_datetime, edits FROM [format_table_na
Why are you putting `step` in parenthesis?

2017-01-25 22:11 UTC, oisin100 commented on code/modules/admin/DB_ban/functions.dm
> +/datum/admins/proc/DB_ban_panel(playerckey = null, adminckey = null, step = 0)
None of this is going to work if you dont edit the admin topic.

2017-01-25 22:11 UTC, oisin100 commented on code/modules/admin/DB_ban/functions.dm
> +		pagination += " ([step*stepSize] - [(step*stepSize)+stepSize]) "
Same goes here for brackets, they aren't needed, BIDMAS, you multiply before adding.

2017-01-25 22:13 UTC, oisin100 commented on code/modules/admin/DB_ban/functions.dm
> +			var/unbanned = text2num(select_query.item[10])//Even in integer, we are memes.
Although funny comments are cool, lets not encourage it, especially when we're getting rid of valid comments and replacing them with memes.

2017-01-25 22:26 UTC, Jc1469 commented on code/modules/admin/DB_ban/functions.dm
> +/datum/admins/proc/DB_ban_panel(playerckey = null, adminckey = null, step = 0)
https://github.com/yogstation13/yogstation/blob/master/code/modules/admin/topic.dm#L174

I don't need to edit stuff that was ported months ago with bits missing.  The bits missing being this.

2017-01-25 22:39 UTC, Jc1469 commented on code/modules/admin/DB_ban/functions.dm
> +		var/DBQuery/select_query = dbcon.NewQuery("SELECT id, bantime, bantype, reason, job, duration, expiration_time, ckey, a_ckey, unbanned, unbanned_ckey, unbanned_datetime, edits FROM [format_table_na
you being triggered about sql formatting is triggering me. it works fine.
this is a port that worked fine.

and you were a coder back then too, did you just skim over this when Eph made it?

2017-01-25 22:50 UTC, oisin100 commented on code/modules/admin/DB_ban/functions.dm
> +/datum/admins/proc/DB_ban_panel(playerckey = null, adminckey = null, step = 0)
ah right.

2017-01-25 22:54 UTC, ShadowDeath6 commented
:^)

2017-01-25 22:54 UTC, oisin100 commented on code/modules/admin/DB_ban/functions.dm
> +		var/DBQuery/select_query = dbcon.NewQuery("SELECT id, bantime, bantype, reason, job, duration, expiration_time, ckey, a_ckey, unbanned, unbanned_ckey, unbanned_datetime, edits FROM [format_table_na
Possibly because its hidden offscreen because that line of code is too long?

Working fine doesn't make it good code.

2017-01-25 23:55 UTC, Super3222 commented
Nerf's grays ban list isn't a good commit name either.

2017-01-26 05:04 UTC, GrayRachnid commented
Does it work with anybody else's banlist tho?

2017-01-31 02:44 UTC, Cruix commented
I the interest of time I am merging this despite the parenthesis thing

2017-01-31 02:44 UTC, merged