Powercell reagent effects framework
yogstation13/yogstation-2017- pull request #1818
Opened 2017-02-13 16:18 UTC by Time-Green

Typing desc...

2017-02-13 16:21 UTC, Time-Green commented on code/__DEFINES/is_helpers.dm
> +#define ispreternis(A) (is_species(A, /datum/species/android))
And this because it's really bothering me this doesn't exist.

2017-02-13 20:22 UTC, Cruix commented
Can't you just put these procs in /datum/reagent?

2017-02-13 20:39 UTC, Time-Green commented
It doesn't actually do much with reagents, it's more based on the powercell. I figured their purposes were to different for it to be a subtype

2017-02-13 23:01 UTC, ShadowDeath6 commented on code/__DEFINES/is_helpers.dm
> +#define ispreternis(A) (is_species(A, /datum/species/android))
why the fuck do you have two defines for the same thing

2017-02-13 23:01 UTC, ShadowDeath6 commented on code/__DEFINES/is_helpers.dm
> +#define ispreternis(A) (is_species(A, /datum/species/android))
why do you have isplant and isphywhatever for the exact same thing, make it isplant or isplantperson or something

2017-02-13 23:02 UTC, ShadowDeath6 commented
If this makes borgs able to irradiate people then :+1:

2017-02-14 06:05 UTC, Time-Green commented on code/__DEFINES/is_helpers.dm
> +#define ispreternis(A) (is_species(A, /datum/species/android))
I wasnt sure wich one to use, and figured people might get confused so I made both

2017-02-14 06:06 UTC, ShadowDeath6 commented on code/__DEFINES/is_helpers.dm
> +#define ispreternis(A) (is_species(A, /datum/species/android))
They can look in ishelpers, that's what the file is for

2017-02-14 06:07 UTC, Time-Green commented on code/__DEFINES/is_helpers.dm
> +#define ispreternis(A) (is_species(A, /datum/species/android))
I guess, I'll go and remove one when I get the chance

2017-02-18 16:02 UTC, Time-Green commented
It does, but at a huge powercost and random stuns

2017-02-18 18:28 UTC, ShadowDeath6 commented
don't make it stun

2017-02-18 19:57 UTC, Time-Green commented
It gets a short stun like every 10 seconds.
Dude, the rads do alot of damage.

2017-03-15 11:15 UTC, Time-Green commented
Dammit, I just now see the merge conflict

2017-03-17 16:47 UTC, Time-Green commented
Fixed the conflict

2017-03-20 12:22 UTC, ArgyleSweatshop commented
This won't work at all. At least I don't think.

You've created a separate datum- powercell_reagents
And done nothing to associate them with actual reagents. Later, when you inject a battery, it checks if what you inject is a powercell_reagent, which it never can be.

2017-03-20 12:27 UTC, ArgyleSweatshop commented
Maybe that's intentional, though, since it's just a framework.

2017-03-20 18:30 UTC, Time-Green commented
I have tested every single bit, and it all works fine. 
I'll absolutely tinker with it once it gets merged, but this works. I tested it and it works. 
I tested the small objects I added, and it works.

Also, I cannot read what or where you commented on my code

2017-03-20 19:06 UTC, ShadowDeath6 commented
@Time-Green 
https://github.com/Time-Green/-tg-station-yog-rebase/commit/801a85a1ff3d7277f93e3244deaa3d0f47fe078e#diff-0eae04c47105ad93b26d765f35fbb175R161

2017-03-25 15:50 UTC, X-TheDark requested changes
You left a little bit of something there.

2017-03-25 15:50 UTC, X-TheDark commented on code/modules/power/cell/powercell.dm
> +	world << "5 [W]"
ZA WARUDO called.

2017-03-25 15:50 UTC, X-TheDark commented on code/modules/power/cell/powercell.dm
> +		world << "6 [W]"
And again...

2017-03-25 15:50 UTC, X-TheDark commented on code/modules/power/cell/powercell.dm
> +		world << "7 [S]"
And again...

2017-03-25 15:50 UTC, X-TheDark commented on code/modules/power/cell/powercell.dm
> +			world << "1 [A]"
You know the drill...

2017-03-25 15:50 UTC, X-TheDark commented on code/modules/power/cell/powercell.dm
> +				world << "3 [A]"
And obviously, you know the world too...

2017-03-25 15:50 UTC, X-TheDark commented on code/modules/power/cell/powercell.dm
> +				world << "4 [R]"
But you seem a bit too desperate...don't call them so often.

2017-03-25 16:10 UTC, Time-Green commented on code/modules/power/cell/powercell.dm
> +				world << "4 [R]"
what the shit, I thought I removed those

2017-03-25 17:18 UTC, X-TheDark approved these changes
Debug code has been removed.

2017-03-27 19:32 UTC, Mrcreepssss commented
the idea would be cool, but what sorts of things would it do? how would it be used? would it be usefull at all? will it not be broken?

2017-03-27 20:04 UTC, ShadowDeath6 commented
Still want this to not stun borgs

2017-03-27 20:25 UTC, Time-Green commented
@Mrcreepssss 
How would it be used?
You inject a needle filled with a reagent, once charge gets removed from the cell, through whatever way, a special effect happens. 
Will it be useful at all? 
Yes, I managed to kill myself and dominus while messing around with it on live.
Will it not be broken?
Of course not, I coded it, what could possibly go wrong?

And shadow, do you have a better idea? I think them giving everyone cancer in a close proximity to them should have some heavy cost.

2017-03-27 20:30 UTC, ShadowDeath6 commented
Make it drain their cells when it pulses or something

2017-03-27 20:31 UTC, Time-Green commented
I'll look at it this week, and that's actually already being done.

2017-03-27 20:40 UTC, ShadowDeath6 commented
then make it drain more idk

2017-04-04 11:19 UTC, Mrcreepssss commented
the main post gives the impression the cell pulses randomly, but you said it happens when emptied so ehm okay that's still not very controllable (imagine putting one of these cells into a defib tho.) maybe there should be a way to trigger it early? perhaps have it trigger if removed without another thing being done? or when emagged?
and perhaps have the rads it emits deal some slight burn damage to the borg? it makes sense enough as there's suddenly a spike of radiation (which heats it up) from the cell.

and ehh, how does this work with slimecells?

2017-04-04 13:38 UTC, closed without merging