Balisong
yogstation13/yogstation-2017- pull request #1833
Opened 2017-02-15 18:15 UTC by Kmc2000

Adds a balisong (butterfly knife) to the game for traitors, it costs 4 tc and does 21 damage when deployed. It is concealable and only clicks when deployed, thus it serves as a more quiet esword or edagger.

It is under the "Stealthy Weapons" tab of the uplink

![](https://i.gyazo.com/9fc1ab182d96a099e15a40e296f2dcb4.png)

![](https://i.gyazo.com/763f54ffd7938d11041bac1f79f9d07d.mp4)

![](https://i.gyazo.com/6d1d4ed37d252c5215a87dbb82094462.png)

What does it do?

It sits halfway between an energy sword and a normal knife, you twirl it around and do tricks when it's deployed and is hard to detect when not deployed, the only sound it makes is a normal click so it's not as obvious/infamous as an energy sword.

##### Changelog

:cl:
rscadd: Adds in a butterfly knife for traitors, watch out for spies!

/:cl:

2017-02-15 18:16 UTC, matskuman5 commented
>4 tc and does 21 damage

>It is concealable

>the only sound it makes is a normal click

beautiful

2017-02-15 18:17 UTC, Kmc2000 commented
>mat

The edagger does 18 for 3 with the swoosh noise.

This is not unreasonable

2017-02-15 20:35 UTC, Super3222 commented
Sounds fun, it could even replace edaggers in the future.

2017-02-15 20:41 UTC, Cruix commented
How is this different from a switchblade?

2017-02-15 20:45 UTC, Kmc2000 commented
>cruix

Higher damage, spinning animation, badassery.

2017-02-15 21:09 UTC, Super3222 commented
It could use something a bit more... unique? No?

2017-02-15 21:10 UTC, Kmc2000 commented
>super

Like...? what exactly?

2017-02-15 21:15 UTC, Super3222 commented
Make it do 30 damage when you attack someone facing the other direction? Normal melee could be reduced to 18 (e dagger). Effectively replacing it.

You should consider letting this fit in ears slots, or at least the case to holster the knife.

2017-02-16 02:15 UTC, drderp3635 commented
> You should consider letting this fit in ears slots, or at least the case to holster the knife.

im not sure if you know what a balisong is, but you wouldn't get one behind your ear comfortably

2017-02-16 03:01 UTC, ShadowDeath6 commented
not a big fan of the red decals tbh, regular white knife would look better

2017-02-16 10:47 UTC, RoboticVodka commented
Shadow I think that's blood... Not decals...

2017-02-16 14:42 UTC, Kmc2000 commented
>shadow

He's correct those are part of the design

2017-02-16 17:06 UTC, AdamElTablawy commented
This is just a better edagger.

The question is why?

2017-02-16 21:09 UTC, ShadowDeath6 commented
Because outdated and obsolete metal knives > beams made of hardlight, obviously

2017-02-17 05:47 UTC, Keekenox commented
Add backstab and less CSGO meme sprite and you will have my vote. 

Or made backstabs always stun

2017-02-17 15:10 UTC, Time-Green commented on code/game/objects/items/weapons/melee/misc.dm
> +		slot_flags = SLOT_BELT //beltisong
Why's this here?

2017-02-17 16:53 UTC, ShadowDeath6 commented
Oh it's based off of csgo shit no wonder I don't like the sprite

2017-02-17 16:54 UTC, ShadowDeath6 commented on code/game/objects/items/weapons/melee/misc.dm
> +		slot_flags = SLOT_BELT //beltisong
Meme comment

2017-02-17 18:26 UTC, Keekenox commented
Kmc, I suggest closing this and rethinking it's gameplay a little bit, I like this, but I like what it could be even more.

2017-02-17 20:04 UTC, Time-Green commented on code/game/objects/items/weapons/melee/misc.dm
> +		slot_flags = SLOT_BELT //beltisong
No, I mean. He set the slot to belt, but why? It was already set to belt, this does absolutely nothing

2017-02-18 14:50 UTC, AdamElTablawy commented
or just make the edagger do whatever shit you wanted this to do

2017-02-19 10:10 UTC, Time-Green requested changes

2017-02-19 10:10 UTC, Time-Green commented on code/game/objects/items/weapons/melee/misc.dm
> +		slot_flags = SLOT_BELT //beltisong
Remove this. It's never actually changed, so this is pointless.

2017-03-28 20:04 UTC, ShadowDeath6 commented
Fix your shit pham

2017-04-01 15:34 UTC, Cruix commented
There is no reason to have this in the uplink when we already have a weapon that fills exactly the same niche. Remove it from the uplink and we can put it in gang or something later.

2017-04-03 20:23 UTC, Mrcreepssss commented
i remember that on a server i used to play on you could craft something similair to this, it used plasteel and metal. don't know the stats though.

2017-04-04 22:51 UTC, closed without merging