Lavaland Overhaul: Part 7 - Lavaland Ruin Cleanup + Cosmic Ashwalker Refactor
yogstation13/yogstation-2017- pull request #1848
Opened 2017-02-17 16:05 UTC by Super3222

https://github.com/yogstation13/yogstation/pull/1773

#### Changelog

rscadd: Abductor Terror Ship is widely exposed to ash storms. It's no longer a safe haven. Likewise, abominations lie behind closed doors between you and the loot.
rscadd: Russian Bunker is now infested with crazy space bears and Hudson, their leader.
rscadd: Medical Outpost now has some extra breathmasks incase some of the doctors have to leave.
rscdel: Cult Ritual ruin has one less free katana.
rscdel: Disabling the hermit role. Nobody plays as the hermit. There's a lot of more good ruins that could spawn instead of it.
rscdel: Removed the Prisoner's ERT suit. I hate how ERT armor is given out like candy.
rscadd: Gave the prisoners multiple barometers. (4 of them)
rscadd: Left a message in Cugganscove congratulating miners for getting in.
rscdel: Disables Cult Ritual Ruin
rscdel: Disables Wizard Den
rscdel: Deletes Autorifle from Weaver Ruin
rscdel: Deletes Hand Tele from Weaver Ruin
rscdel: Deletes Tactical Medkit from Weaver Ruin
rscdel: Deletes Shotgun from Weaver Ruin
rscdel: Deletes ERT Suit from Research Outpost
rscdel: Deletes Revolver (.357) from Russian Bunker
rscdel: Deletes the 2 Armory Contraband Spawners in Cugganscove
rscdel: Deletes 2 stacks of Alien Alloy from the Abductor Terror Ship
tweak: Reduces the human skin/lizard skin/mineral stacks to numbers below 10.
rscdel: The mindflayer in the abductor terror ship has been removed.
rscadd: The Cosmic Ashwalker has been refactored!
rscadd: The New Cosmic Ashwalker can now speak english, and is given derivative that tells them they're seperated from their clan entirely. Able to start anew.
rscadd: The New Cosmic Ashwalker enters a cyrogenic state whenever their health is under 0, they'll crawl into their egg and slowly regenerate.
rscadd: The New Cosmic Ashwalker's cyrogenic state can only work 3 times.
rscadd: The New Cosmic Ashwalker's egg can be attacked by both weapons and targeted by fauna. It's biggest weakness is lava because it will burn their egg to a crisp.
rscadd: Once their egg is destroyed the cosmic ashwalker will be force ejected.
tweak: Ashwalker Chieftain eggs will spawn at the start of the round

Here's my reasoning behind the cosmic ashwalker changes.
It makes the role more interesting rather then it being a mundane ashwalker running around without a leash to a tendril.
The egg itself has drawbacks, destroying it is easy and can be done with 3 KA bolts, megafauna and fauna alike will still target it, and it takes 30 seconds for an entire restoration.
The egg is also flammable so trying to cross a river of lava by regenerating won't do it for you. It'll get you killed faster.
Speaking of getting killed it doesn't work when the cosmic ashwalker is entirely killed.
And they can only enter their regenerative state 3 times.

2017-02-17 16:16 UTC, Jc1469 commented
changelog :balance_scale: :gun: 

idk ruin name but can you remove the antique gun case if the ruin isn't in this mess anywhere.

I also approve of cosmic asswalker changes.  It's now not just a reskinned hermit.  :+1:  

insert ruin bitching from miners here :arrow_down:

2017-02-18 03:59 UTC, Zostroll commented
I liked the combat medkit in the weaver ruin.... It is not to unbalanced.

2017-02-28 16:47 UTC, ShadowDeath6 commented
Make sure to say remove rather than delete in your changelog, delete sounds bad

Good changes though, now all you need to do is make golems spawn more often

2017-03-12 17:48 UTC, Cruix requested changes
I am not sure why, but when I tested this, the cosmic ash walker egg did not start processing and was invisible.

2017-03-12 17:48 UTC, Cruix commented on code/game/objects/structures/ghost_role_spawners.dm
> +	mob_name = "an cosmic ashwalker"
A cosmic ashwalker

2017-03-12 17:48 UTC, Cruix commented on code/game/objects/structures/ghost_role_spawners.dm
> +	var/progress // needs 300
Init this to zero

2017-03-12 17:48 UTC, Cruix commented on code/modules/mob/living/carbon/human/species_types.dm
> +	..()
use . = ..() and do not return ..() down below

2017-03-12 17:48 UTC, Cruix commented on code/modules/mob/living/carbon/human/species_types.dm
> +		if(rebirthcount < 3)
should be > 3

2017-03-12 17:48 UTC, Cruix commented on code/modules/mob/living/carbon/human/species_types.dm
> +	var/rebirthcount
Init this to 0

2017-03-12 17:48 UTC, Cruix commented on code/modules/mob/living/carbon/human/species_types.dm
> +		if(rebirthcount <= 3)
Should be >= 3

2017-03-19 00:39 UTC, Cruix commented on code/game/objects/structures/ghost_role_spawners.dm
> +	..()
You can't call ..() in process unless you know what it is, because the default process() removes the object from processing because of a questionable decision made long, long ago on a space station far, far away.

As a result the egg does not process more than once and the ashwalker slowly suffocates to death because it can't breathe in nullspace.

2017-04-01 15:31 UTC, Cruix commented on code/game/objects/structures/ghost_role_spawners.dm
> +		qdel(src)
Move this qdel to ejectEgg() so the egg does not stick around when it is beat to death

2017-04-09 16:37 UTC, Cruix approved these changes

2017-04-09 17:05 UTC, Cruix commented on code/game/objects/structures/ghost_role_spawners.dm
> +	if(..())
This always fails because /obj/effect/attack_animal returns null, but it hardly matters because simple animals will not attack the egg anyway.

2017-04-09 17:06 UTC, Cruix commented on code/game/objects/structures/ghost_role_spawners.dm
> +	..()
return ..()

2017-04-09 17:06 UTC, Cruix commented on code/game/objects/structures/ghost_role_spawners.dm
> +	qdel(src)
this needs to set the ashwalker's rebirth to FALSE so he can revive again

2017-05-03 02:36 UTC, Cruix commented
Reopen when it is fixed

2017-05-22 03:29 UTC, Cruix commented on code/game/objects/structures/ghost_role_spawners.dm
> +		reset_rebirth()
Move this up to before the ashwalker is null

2017-05-26 21:59 UTC, Super3222 commented on code/game/objects/structures/ghost_role_spawners.dm
> +		reset_rebirth()
okay

2017-06-05 19:29 UTC, X-TheDark commented
Seems to be working fine from the tests:
- [x] All ashwalkers spawn normally
- [x] Cosmic ashwalker respawns upon going into crit 3 times
- [x] Abominations seem to be working

2017-06-05 19:29 UTC, merged