Mentors
yogstation13/yogstation-2017- pull request #1854
Opened 2017-02-18 01:07 UTC by Super3222

Refer to issue https://github.com/yogstation13/yogstation/issues/1810.
I think it's worth noting that i almost ported BUTTBOTS while rebasing.

#### Intent of your Pull Request

From what I understand Mentors are a lower-class admin that are coded entirely differently.
First of all, admins APPOINT mentors. Yes, at will they can choose and demote anyone they want to.
Mentors also have mentorSAY, for chatting like little girls, and mentorMEMOS (similar to admin memos).

And so they get the recognition they deserve their OOC color is also different. I might as well throw in an OOC tag.

Thanks goes out to the hippiestation team.

##### Changelog

:cl:
rscadd: Ported Mentors from HippieStation.
/:cl:

Progress Bar:
Never Tested |o---------------------| Completely Tested

2017-02-18 01:51 UTC, drderp3635 commented
Noice

2017-02-18 09:44 UTC, Jc1469 commented
cool. someone actually adding it.  Now make it use the ticket system :laughing: :gun:

2017-02-18 15:30 UTC, GrayRachnid commented
How does appointing mentors work? Is it a round-by-round basis? Also, does the council know about how it works and did they make any suggestions?

2017-02-19 00:43 UTC, Super3222 commented
> How does appointing mentors work? Is it a round-by-round basis? Also, does the council know about how it works and did they make any suggestions?

Turns out I was a bit wrong. It works off of a database OR it works off of the legacy notepad system.

2017-03-01 18:17 UTC, ShadowDeath6 commented
Port buttbots wtf

2017-03-12 16:49 UTC, oisin100 requested changes

2017-03-12 16:49 UTC, oisin100 commented on SQL/mentor.sql
> +CREATE TABLE `mentor` (
Why is this in an individual file and not in the normal schema file?
We usually prefix all our table names with "erro_" too, could you please do that?

2017-03-12 16:49 UTC, oisin100 commented on SQL/mentor.sql
> +CREATE TABLE `mentor_memo` (
Same goes for the prefixing here.

2017-03-12 16:49 UTC, oisin100 commented on code/modules/client/verbs/who.dm
> -	var/msg = "<b>Current Players:</b>\n"
Why remove this?

2017-04-01 19:58 UTC, GrayRachnid commented
This merged when?

2017-04-01 20:04 UTC, ShadowDeath6 commented
see https://github.com/yogstation13/yogstation/pull/1854#pullrequestreview-26449087

2017-04-01 20:05 UTC, Super3222 commented
Oisin is taking control of this PR.

2017-04-04 10:00 UTC, Mrcreepssss commented
hm, as far as i know mentors are like inbetween admin and player, as in no superpowers. but they do know alot about how the game works and are supposed to help newbies when asked. i personally like to do that occasionally anyway so if/when this becomes a thing i'll be a volunteer.

i'm in for this.

2017-04-20 22:09 UTC, closed without merging