Computer screen cracks
yogstation13/yogstation-2017- pull request #1888
Opened 2017-02-23 16:13 UTC by Time-Green

Adds cracks to computer screens. 
Computer screens can now also be fixed with a welder.
[pictures coming]
:cl:
rscadd: Centcom has cut the computer glass budget.
/:cl:
Remind me to make easy procs for welding etc.

2017-02-23 16:20 UTC, Super3222 commented
Awesome!

2017-02-23 16:45 UTC, oisin100 requested changes

2017-02-23 16:45 UTC, oisin100 commented on code/game/machinery/computer/computer.dm
> +	var/crack = round(computer_health / 5)
What if the computer health isn't a multiple of 5? No cracks would appear if the computer had 1 health.

2017-02-23 16:45 UTC, oisin100 commented on code/game/machinery/computer/computer.dm
> +			computer_health = computer_health_max
Might be worth using `initial()` instead of creating a new variable

2017-02-23 16:46 UTC, oisin100 requested changes

2017-02-23 16:46 UTC, oisin100 commented on code/game/machinery/computer/computer.dm
> +			user << "<span class='notice'>No point in welding a [computer_health ?  "pristine" : "completely broken"] computer.</spawn>"
You made a typo `</spawn>`

2017-02-23 16:47 UTC, Time-Green commented on code/game/machinery/computer/computer.dm
> +	var/crack = round(computer_health / 5)
That's why the round() proc is there.
It would round off to 0, and I made an icon_state for that

2017-02-23 16:47 UTC, Time-Green commented on code/game/machinery/computer/computer.dm
> +			user << "<span class='notice'>No point in welding a [computer_health ?  "pristine" : "completely broken"] computer.</spawn>"
Woops

2017-02-23 16:49 UTC, oisin100 commented on code/game/machinery/computer/computer.dm
> +	var/crack = round(computer_health / 5)
Ah, right

2017-02-23 17:00 UTC, oisin100 approved these changes

2017-02-23 21:40 UTC, Notamaniac commented
Have you checked this doesn't look weird on the purple robo monitors and red sec monitors? Your cracks have a lot of blue in them, and I'm assuming that the overlay is being reused for each monitor

2017-02-23 22:06 UTC, Notamaniac commented
![drr](https://cloud.githubusercontent.com/assets/17688334/23280490/508f962c-fa11-11e6-93d2-d1c95c38102a.PNG)

E.g. I mean this looks more like blue slime on a nucleus of...  pure black. 

I'm no computer screen crack expert, but if I'm being nitpicky, large portions of the screen should be getting disabled, rather than just a crack appearing. Personally I'd take inspiration from a laptop screen cracking, and replicating that weird rainbow fractal effect, but that borders on putting too much effort in.

Then again you could just handwave this as being the future, and all computer screens leave blue goop to seal up their cracks and uh stuff

![image](https://cloud.githubusercontent.com/assets/17688334/23281127/f2893f58-fa13-11e6-819a-5a64cc3c2fd1.png)

2017-02-23 23:02 UTC, Cruix commented
It is the future, so every pixel is a tiny computer screen. The blue is the screens that are damaged showing the blue screen of death.

2017-02-27 04:46 UTC, Dagdammit commented
So does it take more hits to break computer screens now?

2017-02-27 06:23 UTC, Time-Green commented
No. The only non visual change is that you can weld a screen to fix it, if it's not completely broken.

2017-02-27 11:12 UTC, Alek2ander commented
They can already be fixed with a welder though. You just have to take the glass out first.

2017-02-27 12:47 UTC, Time-Green commented
I know. But now it can be done prematurely to avoid it breaking at all.

2017-03-05 23:17 UTC, Cruix commented
If you try to fix a computer that is totally smashed, it says "No point in welding a pristine computer."

2017-03-06 05:40 UTC, Time-Green commented
Oh yeah, a broken PC is a different object...

2017-03-06 16:22 UTC, Time-Green commented
What happened was: You fixed it, wich set it to 25health, wich gave the message when you welded it again.
Apparently | 0  doesn't work. I'll throw up a fix.

2017-03-12 16:31 UTC, Cruix commented on code/game/machinery/computer/computer.dm
> +	if(!(screen_crack && computer_health) || (computer_health == initial(src.computer_health) | 0 ))
Did you mean || 0? anything | 0 does nothing.

2017-03-12 16:32 UTC, Cruix commented on code/game/machinery/computer/computer.dm
> +	if(!(screen_crack && computer_health) || (computer_health == initial(src.computer_health) | 0 ))
Wait that would still not work, you have to do
computer_health == initial(src.computer_health) || computer == 0

2017-03-12 16:33 UTC, Cruix commented
Please do not do commit messages like that

2017-03-12 18:29 UTC, Time-Green commented on code/game/machinery/computer/computer.dm
> +	if(!(screen_crack && computer_health) || (computer_health == initial(src.computer_health) | 0 ))
I split it up, I tested it and now it works properly

2017-03-12 18:31 UTC, Time-Green commented
A while ago you said in coderchat you would like it if someone made a pixel art in their commit names, I wanted to do it for a while, and the commits don't actually change anything.

2017-03-12 18:31 UTC, Cruix commented on code/game/machinery/computer/computer.dm
> +	if(!(screen_crack && computer_health) || (computer_health == initial(src.computer_health) | 0 ))
Remove the | 0 then, as it does nothing and will just confuse people

2017-03-12 18:31 UTC, Cruix commented
I don't remember saying that

2017-03-12 18:31 UTC, Time-Green commented on code/game/machinery/computer/computer.dm
> +	if(!(screen_crack && computer_health) || (computer_health == initial(src.computer_health) | 0 ))
Oh, I just read I never removed that... 
Sure, I'll fix it

2017-03-12 18:33 UTC, merged

2017-03-12 18:35 UTC, Time-Green commented
It was probably oisin or dark then, I thought it was you, sorry...