makes dismembering legs not stun- also makes blood bubble when slaughter demons use it
yogstation13/yogstation-2017- pull request #1901
Opened 2017-02-26 00:11 UTC by ShadowDeath6

wow pseudo more like boohoodo
fixes #1898 somewhat

if you wanna get mad about dismembering leg thing not working remember that it already slows you down

:cl: ShadowDeath6
rscdel: Removed the stun from leg dismemberment.
rscadd: Blood bubbles when slaughter demons are about to pop out of it.
/:cl:

2017-02-26 02:13 UTC, Super3222 requested changes
src pruning.
adjust code to forcemove.
don't be lazy and remove stunning from dismember. just don't.

2017-02-26 02:13 UTC, Super3222 commented on code/modules/surgery/bodyparts/dismemberment.dm
> -		owner.Weaken(2)
Instead of removing this make a variable that ignores pain, and work around it with your dismember code. You'll probably need to create a new variable - or just make it so mobs won't cause you to fall on your face after being dismembered.

2017-02-26 02:13 UTC, Super3222 commented on code/modules/surgery/bodyparts/dismemberment.dm
> -		owner.Weaken(2)
Instead of removing this make a variable that ignores pain.

2017-02-26 02:13 UTC, Super3222 commented on code/modules/mob/living/bloodcrawl.dm
> +		src.loc = B.loc
forceMove(B)

2017-02-26 02:13 UTC, Super3222 commented on code/modules/mob/living/bloodcrawl.dm
> +		src.visible_message("<span class='warning'><B>[src] rises out of the pool of blood!</B>")
visible_message

2017-02-26 02:13 UTC, Super3222 commented on code/modules/mob/living/bloodcrawl.dm
> +		src.visible_message("<span class='warning'><B>[src] rises out of the pool of blood!</B>")
delete src

2017-02-26 02:13 UTC, Super3222 commented on code/modules/mob/living/bloodcrawl.dm
> +		qdel(src.holder)
holder

2017-02-26 02:13 UTC, Super3222 commented on code/modules/mob/living/bloodcrawl.dm
> +		src.holder = null
holder

2017-02-26 02:32 UTC, ShadowDeath6 commented on code/modules/surgery/bodyparts/dismemberment.dm
> -		owner.Weaken(2)
why would I add a pain variable
would you prefer it to do stamina or something

2017-02-26 02:46 UTC, Super3222 commented on code/modules/surgery/bodyparts/dismemberment.dm
> -		owner.Weaken(2)
`if(pain) owner.Weaken(2)`
`/obj/item/bodypart/r_leg/drop_limb(special,var/pain = TRUE)`
make it set pain as false.

2017-02-26 15:44 UTC, Super3222 commented
After talking with Shadow yesterday he makes a pretty good point that it's more a universal problem then just slaughter demons.

2017-02-26 15:44 UTC, Super3222 approved these changes

2017-02-26 19:02 UTC, Time-Green commented
You mean getting hit once and get your leg dismembered, and then getting instantly killed?
Yeah that's a problem.

2017-02-27 15:43 UTC, AdamElTablawy commented
Legstun dismember was even nerfed on /tg/ it's such an issue.

Dual eblade is always a 100% stun on melee range, as it will always dismember the leg on the first hit. Or, almost always. 

This in addition to it having a 75% blockchance means that the only reliable way to down them is to be in melee range, where they are immune to disarms and you need a melee weapon like a stunbaton to block it.

2017-03-06 01:58 UTC, merged