Golem traits
yogstation13/yogstation-2017- pull request #2147
Opened 2017-04-22 14:32 UTC by Time-Green

(TYPING DESC NOW)

2017-04-22 15:03 UTC, Jc1469 reviewed
I like but I don't like.

2017-04-22 15:03 UTC, Jc1469 commented on code/modules/golem/golem_spawners.dm
> +		message_admins("[key_name_admin(G)](<A HREF='?_src_=holder;adminmoreinfo=\ref[G]'>?</A>) has been summoned by [key_name_admin(user)](<A HREF='?_src_=holder;adminmoreinfo=\ref[user]'>?</A>), an anta
Considering xenobiology can now make cancer golems, can you add an admin message for whenever a uranium/plasma one is made too?

2017-04-22 15:03 UTC, Jc1469 commented on code/modules/golem/golem_types.dm
> +	info_text = "As a <span class='danger'>Silver Golem</span>, you are resistent to burn!"
_resistent_

2017-04-22 15:03 UTC, Jc1469 commented on code/modules/golem/golem_types.dm
> +/datum/species/golem/uranium/spec_life(mob/living/carbon/human/H)
as much as I love this, I can see this becoming so bad so quickly, same as the plasma one on death really.

tbh i just think we should replace all golems with uranium ones

2017-04-22 15:03 UTC, Jc1469 commented on code/modules/golem/golem_types.dm
> +	info_text = "As a <span class='danger'>Glass Golem</span>, you're vulnerable to brute attacks, but resistent to burn and you reflect lasers!"
_resistent_

Also pretty insane.. Glass doesn't reflect lasers. Normally they just pass through it. :thinking:

2017-04-22 15:03 UTC, Jc1469 commented on code/modules/golem/golem_types.dm
> +/datum/species/golem/sand/bullet_act(obj/item/projectile/P, mob/living/carbon/human/H)
This one for example is balanced in my eyes.  _glass_ reflecting lasers though, not so much.

2017-04-22 15:03 UTC, Jc1469 commented on code/modules/golem/golem_types.dm
> +/datum/species/golem/wood
Does the wood golem die in darkness or is it just a better plant person in every possible way?

2017-04-22 15:03 UTC, Jc1469 commented on code/modules/golem/golem_types.dm
> +/datum/species/golem/mythril/bullet_act(obj/item/projectile/P, mob/living/carbon/human/H)
Info text doesn't mention magic immunity, a nice touch though, in the one in a million chance someone actually gets mythril and a golem shell.

2017-04-22 15:09 UTC, Time-Green commented on code/modules/golem/golem_types.dm
> +/datum/species/golem/wood
It dies in the dark

2017-04-22 15:11 UTC, Jc1469 commented on code/modules/golem/golem_types.dm
> +/datum/species/golem/wood
Doesn't make that very clear anywhere.  

> You regenerate in light, but are weak to fire

2017-04-22 15:13 UTC, Time-Green commented
Ill fix the rest tomorrow

2017-04-22 15:13 UTC, Cruix commented
That's a nice xenobio buff you got there

2017-04-22 15:23 UTC, matskuman5 commented
Honestly xenobio is so strong right now it should probably be split to 2 jobs.

Golems and slimes

2017-04-22 23:17 UTC, Time-Green commented
Ill find some way to make lasers pass through.
Also, yeah the xenobiolist is really OP now.
Should I just revert the golemrune or do you guys have something else in mind?

2017-04-23 07:14 UTC, Jc1469 commented
Why not leave adamantine runes as they are and add Mythril Runes?  Adamantine slim slam with liquid mythril injected.  And make mythril be the activator for the custom shells, whereas plain adamantine with plasma is just a static golem rune.

Reason for mythril is like I said, the odds of scientists getting it is fairly slim, and we really don't want to see this every single round.

2017-04-23 08:06 UTC, ShadowDeath6 commented on code/modules/golem/golem_spawners.dm
> +	desc = "A strange rune used to create golem artifacts. /n Maybe you can manipulate the material..."
I don't like the newline here, what's it purpose? if you want it to be a prompt for them to wonder if they can do it add it in the examine proc with a different span, like notice

2017-04-23 08:07 UTC, ShadowDeath6 commented on code/modules/golem/golem_spawners.dm
> +	playsound(src.loc, 'sound/effects/meteorimpact.ogg', 100, 1)
try using the rock break sound 4 flavor

2017-04-23 08:08 UTC, ShadowDeath6 commented on code/modules/golem/golem_types.dm
> +	info_text = "As an <span class='danger'>Iron Golem</span>, your punches pack a punch!"
words

2017-04-23 08:09 UTC, ShadowDeath6 commented on code/modules/golem/golem_types.dm
> +	info_text = "As an <span class='danger'>Adamantine Golem</span>, you are not special!"
>making generic metal golem better than magical uncreatable meme material

for reference the adamantine coin is worth 1000 and iron coins are worth 1, so the obvious choice is to give them 55000 armor

2017-04-23 08:10 UTC, ShadowDeath6 commented on code/modules/golem/golem_types.dm
> +	info_text = "As a <span class='danger'>Golden Golem</span>, your armor is weaker, but are faster!"
words.wav

2017-04-23 08:11 UTC, ShadowDeath6 commented on code/modules/golem/golem_types.dm
> +	info_text = "As a <span class='danger'>Silver Golem</span>, you are resistant to burn!"
burning*

2017-04-23 08:11 UTC, ShadowDeath6 commented on code/modules/golem/golem_types.dm
> +	info_text = "As a <span class='danger'>Uranium Golem</span>, you radiate!"
words.png

2017-04-23 08:12 UTC, ShadowDeath6 commented on code/modules/golem/golem_types.dm
> +	H.visible_message("<span class='danger'>[H]'s glass body shaters into pieces...</span>")
shaters

2017-04-23 08:12 UTC, ShadowDeath6 commented on code/modules/golem/golem_types.dm
> +	info_text = "As a <span class='danger'>Reinforced Glass Golem</span>, you reflect lasers and have a weaker armor!"
have a weaker armor

2017-04-23 08:12 UTC, ShadowDeath6 commented on code/modules/golem/golem_types.dm
> +	info_text = "As a <span class='danger'>Reinforced Glass Golem</span>, you reflect lasers and have a weaker armor!"
also make sure to note that you move faster

2017-04-23 08:15 UTC, ShadowDeath6 commented on code/modules/golem/golem_spawners.dm
> +		G << "<span class='userdanger'>Despite your servitude to another cause, your true master remains [user.real_name]. This will never change unless your master's body is destroyed.</span>"
this will never change ever, remove the last part

2017-04-23 08:18 UTC, ShadowDeath6 commented
using "liquid mythril" which isn't a thing won't help because golems kind of have a thing that they stick into an autolathe to mass produce shells and since getting the tech disk from golems is about 16 million times easier than getting mythril from ashwalkers there's no benefit in going after the ashwalkers just to fuel xenobio's autism

2017-04-23 11:41 UTC, Time-Green commented on code/modules/golem/golem_spawners.dm
> +		G << "<span class='userdanger'>Despite your servitude to another cause, your true master remains [user.real_name]. This will never change unless your master's body is destroyed.</span>"
This was copypasted

2017-04-23 11:42 UTC, Time-Green commented on code/modules/golem/golem_types.dm
> +	info_text = "As an <span class='danger'>Iron Golem</span>, your punches pack a punch!"
I'm never changing that one

2017-04-23 11:46 UTC, Time-Green commented
What about strange reagent?

2017-04-23 19:41 UTC, ShadowDeath6 commented
nobody makes strange reagent ever

I wish we had logging for the gold slime strange reagent reaction, I bet it's never been done in the past 2 weeks

2017-04-23 19:42 UTC, ShadowDeath6 commented on code/modules/golem/golem_spawners.dm
> +		G << "<span class='userdanger'>Despite your servitude to another cause, your true master remains [user.real_name]. This will never change unless your master's body is destroyed.</span>"
what does copypasting have to do with it

2017-04-23 21:29 UTC, Time-Green commented
Then we can give it a purpose!
TODO: 
Fix golem ruin object paths
Add bananium golem
Re-add the adamantine rune
Add a strange reagent rune capable of making all golems

2017-04-24 15:16 UTC, drderp3635 commented
What does the gold+strange reagent even do?

I did it once and nothing happened.

2017-04-24 15:21 UTC, ShadowDeath6 commented
Secret

2017-04-26 11:25 UTC, Time-Green commented
This is now merge ready

2017-04-26 12:03 UTC, Cruix commented on code/modules/golem/golem_types.dm
> +	traits = "As a <span class='danger'>Plasma Golem</span>, you dissolve on death!"
"As a <span class='danger'>Plasma Golem</span>, you <strike>dissolve</strike> get banned for bomb griefing on death!"

2017-04-26 12:10 UTC, Time-Green commented on code/modules/golem/golem_types.dm
> +	traits = "As a <span class='danger'>Plasma Golem</span>, you dissolve on death!"
Should I just reduce the plasma amount created or actually add that as the description?

2017-04-26 12:23 UTC, Cruix commented on code/modules/golem/golem_types.dm
> +	traits = "As a <span class='danger'>Plasma Golem</span>, you dissolve on death!"
No, it is fine the way it is, just a joke.

2017-04-27 11:06 UTC, Time-Green commented
I forgot to remove the WIP in the title, I cant fix it because im on my own, just imagine its not there

2017-05-18 12:01 UTC, Super3222 commented
I can test this if needs be.

2017-05-18 12:55 UTC, Time-Green commented
You don't trust me not to kill the powernet again?

2017-06-09 16:18 UTC, Cruix requested changes

2017-06-09 16:18 UTC, Cruix commented on code/modules/golem/golem.dm
> +	return golemTypes[S.type]
You need to use istypes here so children like /obj/item/stack/sheet/mineral/*/fifty will work as well

2017-06-09 16:18 UTC, Cruix commented on code/modules/golem/golem_types.dm
> +	C << "<span class='notice'>[traits]</span>"
Traits are never shown to golems spawned from a spawner, because the spawner sets the species before putting the client in the mob

2017-06-09 16:18 UTC, Cruix commented on code/game/objects/radiation.dm
> +		if(!silent && !(blocked == 100))
Golems are still getting the "your skin feels warm" message

2017-06-09 16:18 UTC, Cruix commented on code/modules/golem/golem_types.dm
> +	traits = "As a <span class='danger'>Reinforced Glass Golem</span>, you reflect lasers, but have a weaker armor!"
Don't they have more armor?

2017-06-09 16:18 UTC, Cruix commented on code/modules/golem/golem_types.dm
> +	playsound(src, "shatter", 70, 1)
The sound should play from H, not src

2017-06-09 16:18 UTC, Cruix commented on code/modules/golem/golem_types.dm
> +	C.weather_immunities |= "lava"
I think you meant -=

2017-06-09 16:18 UTC, Cruix commented on code/modules/golem/golem_types.dm
> +	punchdamagehigh = 20
I hope you realize that this means they have a 90% chance to stun every punch

2017-06-09 16:18 UTC, Cruix commented on code/modules/golem/golem_types.dm
> +	honker.removed(C)
qdel the implant as well

2017-06-09 16:33 UTC, Time-Green commented on code/modules/golem/golem_types.dm
> +	traits = "As a <span class='danger'>Reinforced Glass Golem</span>, you reflect lasers, but have a weaker armor!"
Less then the average golem

2017-06-12 17:54 UTC, Time-Green commented
Fixed the stuff

Also, about the rad stuff, it was always returning zero, so I made it skip the message with RADIMMUNE aswell
this was tested

2017-06-12 18:53 UTC, ShadowDeath6 commented on code/modules/golem/golem_types.dm
> +	punchdamagehigh = 20
you're being punched by a fist completely comprised of metal though

2017-06-12 23:07 UTC, X-TheDark commented on code/modules/golem/golem_spawners.dm
> +		G << "<span class='userdanger'>Despite your servitude to another cause, your true master remains [user.real_name]. This will never change unless your master's body is destroyed.</span>"
Yeah, you still serve the guy's orders, even if he died. If he told you to revive him if he dies, you need to do it when he does die.

2017-06-12 23:14 UTC, X-TheDark commented on code/modules/golem/golem_types.dm
> +	reflective = FALSE
You forgot the `.., you reflect lasers, ...` part

2017-06-12 23:19 UTC, X-TheDark commented
Is it possible for Xenobiology to make these golems?
I don't see anywhere in the code from where you can get the golem shell.

2017-06-13 00:37 UTC, Cruix commented on code/modules/golem/golem_types.dm
> +	reflective = FALSE
Glass golems do not reflect lasers, lasers go right through them

2017-06-13 00:40 UTC, Cruix commented on code/modules/golem/golem_types.dm
> +	honker = null
qdel it first

2017-06-13 00:49 UTC, ShadowDeath6 commented
Still should revise/remove the "unless your master's body is destroyed" message, it makes no sense that a golem suddenly stops caring about their master if their body is destroyed.

2017-06-13 01:13 UTC, X-TheDark commented on code/modules/golem/golem_types.dm
> +	reflective = FALSE
If that's the case then the `traits` message should be changed to not include this part.

2017-06-13 01:13 UTC, X-TheDark commented on code/modules/golem/golem_types.dm
> +	traits = "As a <span class='danger'>Reinforced Glass Golem</span>, you reflect lasers, but have a weaker armor!"
Remove the `you reflect lasers` part, as it seems that this is not the case.

2017-06-13 05:07 UTC, Time-Green commented on code/modules/golem/golem_types.dm
> +	honker = null
It's unqdellable-
Wait fuck nevermind I realize why it didn't work earlier

2017-06-27 01:06 UTC, merged

2017-06-27 18:59 UTC, Super3222 commented
A wikia page with all the different types of golems would be pretty awesome.

2017-06-27 19:46 UTC, Time-Green commented
Ah, yes