Vampire Mode
yogstation13/yogstation-2017- pull request #2240
Opened 2017-05-29 20:02 UTC by Super3222

### Vampire Mode

A gamemode focused on atrocious vampires draining the life out of the crew and advancing their objectives.

Depending on the amount of blood a vampire collects they will automatically unlock new sets of abilities/skills. Sometimes new, and sometimes strengthening old ones.

-----

### Gamemode

The design doc for the gamemode itself can be examined here: http://piratepad.net/HvCBjcZcAR

The gamemode will regularly begin with 3 vampires who's goals are to collect a certain amount of blood by the end of the shift, the vampire has a chance of getting a steal or kill objective (never together), and instead of an escape on the shuttle objective they have to survive until the end.

Vampires work alone; they have no reason to work together. Therefore, the gamemode does not have any mechanics that would help vampires work together. At the same time, there is no penalty for vampires that choose to fight against one another.

-----

### Progress

- [ ] Gamemode
- [ ] Code Review
- [ ] Live Testing

-----

### Credits

**Adam El-Tablawy** - Design Lead
**Super3222** - Coder, helped with design
**ShadowDeath6** - Coder
**Maya/Larissa** - Spriter

The design doc also includes who did what. [DONE by] indicates it was coded by. If anything happens to the doc, please contact me. I may also be issuing another one to collect bug reports.

Big thanks to Maya, without them the project would've been stuck in development limbo. They were incredibly efficient.

#### Changelog

:cl:
rscadd: Vampire Mode!
/:cl:

2017-05-29 20:03 UTC, matskuman5 commented
cool

2017-05-29 20:25 UTC, Time-Green commented
Incredible work super, shadow and Maya.

God I can't wait for all this to get merged, so much. new and exciting content

2017-05-29 20:28 UTC, ShadowDeath6 commented
I didn't actually do anything don't fool yourselves

2017-05-30 08:01 UTC, Alek2ander commented
Cool.
Can we remove slings now?

2017-05-30 09:56 UTC, oisin100 commented on code/game/objects/items/weapons/grenades/spawnergrenade.dm
> +/obj/item/weapon/grenade/spawnergrenade/clownbugs
UNDOCUMENTED FEATURE?!?!

2017-05-31 04:19 UTC, Super3222 commented on code/game/objects/items/weapons/grenades/spawnergrenade.dm
> +/obj/item/weapon/grenade/spawnergrenade/clownbugs
vampire mode was only a trojan horse for clownbugs

2017-06-01 15:56 UTC, Time-Green commented
Make sure they can't use mirrors

2017-06-01 15:58 UTC, Time-Green commented
Make sure they are invisible photographs and can't use mirrors

2017-06-02 03:10 UTC, Super3222 commented
> Make sure they are invisible photographs and can't use mirrors

Yup! We got appearing invisible in photographs down. Mirrors I'll jot down.

2017-06-02 03:55 UTC, ShadowDeath6 commented
mirrors might actually hurt them p bad because they can't change their appearance at all

2017-06-04 08:25 UTC, Mrcreepssss commented
maybe mirror should randomize look instead? seeing as they could still change their appearance technically, it'd just be a mess without mirror.

2017-06-27 17:00 UTC, Super3222 commented on code/_onclick/click.dm
> -				security_scan_status(src, A, allowed_access)
uhuh

2017-06-27 17:00 UTC, Super3222 commented on code/_onclick/click.dm
> +			if((1 in I))
merg conflicts

2017-07-27 20:51 UTC, Super3222 commented
This mode was completed a long time ago

2017-07-30 17:31 UTC, Time-Green commented
Happy 2 months anniversairy!

2017-07-31 03:13 UTC, X-TheDark commented on code/game/gamemodes/vampire/vamp_powers/vamp_400.dm
> +		R.take_damage(100)
Why are reinforced glass windows damaged in 12 tile radius instead of 7 as normal windows?

2017-07-31 03:14 UTC, X-TheDark commented on code/game/gamemodes/vampire/vamp_powers/vamp_400.dm
> +		C.take_damage(100)
Same question, why 12 instead of 7?

2017-07-31 03:18 UTC, X-TheDark commented on code/game/gamemodes/vampire/vamp_powers/vamp_600.dm
> +			chosenone = O
Minor point - at some point in the future, implement Aghosted admin checking. Don't want vampires sucking off admin ghosts. Not a showstopper.

2017-07-31 03:20 UTC, X-TheDark commented on code/game/gamemodes/vampire/vamp_powers/vamp_800.dm
> +		var/mob/living/simple_animal/hostile/mimic/copy/C
Nothing is assigned to this.

2017-07-31 03:21 UTC, X-TheDark commented on code/game/gamemodes/vampire/vamp_powers/vamp_800.dm
> +		C.check_obj = FALSE
C doesn't exist at this point, you need to move `new()` up.

2017-07-31 03:22 UTC, X-TheDark commented on code/game/gamemodes/vampire/vamp_powers/vamp_800.dm
> +		charm.faction += "Vampire"
`faction |= "Vampire" for both, instead of `+`

2017-07-31 03:25 UTC, X-TheDark commented on code/game/gamemodes/vampire/vampire.dm
> +	recommended_enemies = 0 // 1
Notice for after testmerge - change these to the proper values.

2017-07-31 03:27 UTC, X-TheDark commented on code/game/gamemodes/vampire/vampire.dm
> +	vampire.current << "<B><span class='announcevampire'>You are a Vampire.</font></B>"
Are you sure it's `</font>` instead of `</span>`?

2017-07-31 03:36 UTC, X-TheDark commented on code/game/gamemodes/vampire/vdatum.dm
> +/datum/vampire/proc/add_blood(amount, amthigh, amtlow)
I'm curious because I don't see the other two parameters currently used:
Anything specific planned for the parameters that are used for random amount of blood giving?

2017-07-31 03:37 UTC, X-TheDark commented on code/game/gamemodes/vampire/vdatum.dm
> +	vampire.faction += "Vampire"
`faction |= "Vampire"` to prevent duplicate entries in the list.

2017-07-31 03:42 UTC, X-TheDark commented on code/game/gamemodes/vampire/vdatum.dm
> + their coffin.
According to documentation, BYOND comments don't work this way, you can't add lines via an endline `\`
Prepend both 212 and 214 with `//`

2017-07-31 03:48 UTC, X-TheDark commented on code/game/gamemodes/vampire/vdatum.dm
> +	if(bloodcount >= 1000) limit = 1000
Make this dependent on your current unlock stages `hundred_unlock`/etc, otherwise this is useless for regeneration purposes (where it's currently used), as it always returns a number less than your current bloodcount.

2017-07-31 03:52 UTC, X-TheDark commented on code/modules/client/verbs/suicide.dm
> +				H << "<span class='vampirealert'>[src] has attempted to suicide, but was prevented!</span>"
Might want to ask around admin staff if this should be logged.

2017-07-31 03:57 UTC, X-TheDark commented on code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
> +		B.switchonCD(150)
Move `qdel` to the end for safety. It's bad practice to try to access variables of something you're deleting, even if it's queued.

2017-07-31 03:57 UTC, X-TheDark commented on code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
> +		B.switchonCD(150)
Move `qdel` to the end for safety. It's bad practice to try to access variables of something you're deleting, even if it's queued.

2017-07-31 03:59 UTC, X-TheDark commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	race = /datum/species/plant
Hmmm?

2017-07-31 04:04 UTC, Cruix requested changes

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/objective.dm
> +				pass = owner.vampire.eighthundred_unlocked
These are backwards

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/objective.dm
> +		if(I.faction == "Vampire")
Factions are lists, so this will always be false

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_misc/vamp_structures.dm
> +			STOP_PROCESSING(SSobj, src)
All of this should be in Destroy(), not process()

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/basic.dm
> +	if(L.weakened || L.stunned || L.sleeping || L.stat == DEAD || L.stat == UNCONSCIOUS || get_dist(L, T) > 1 || !L.pulling)
use L.incapacitated() and L.stat == CONCIOUS

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/basic.dm
> +		L << "<span class='noticevampire'>[T] has ran out of blood.</span>"
run out of blood

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/vamp_100.dm
> +		if(get_dist(user, living) > 7) // 7 range
Should this be < 7 instead of > 7?

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/vamp_300.dm
> +	var/transformed = FALSE
This verb is never set to TRUE, so I would guess that you could transform into a bat if you are already one

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/vamp_300.dm
> +	var/transformed = FALSE
This ability should reuse code from the wizard shapeshifting spell instead of copypasting it, since it is doing exactly the same thing

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/vamp_300.dm
> +			continue
This will never be true

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/vamp_300.dm
> +			continue
This will never be true

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/vamp_300.dm
> +		if(T && T.flags & NOJAUNT) // aka blessed.
T.flags & NOJAUNT should be in parenthesis

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/vamp_300.dm
> +			for(var/obj/item/device/radio/radio in living.contents)
use GetAllContents()

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/vamp_400.dm
> +		if(istype(T, /obj/structure/window))
This will never be true, because windows are not turfs

2017-07-31 04:04 UTC, Cruix commented on code/modules/client/verbs/suicide.dm
> +				H << "<span class='vampirealert'>[src] has attempted to suicide, but was prevented!</span>"
attempted to commit suicide

2017-07-31 04:04 UTC, Cruix commented on code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
> +	vamp.status_flags &= GODMODE
&= ~GODMODE

2017-07-31 04:04 UTC, Cruix commented on code/modules/paperwork/photography.dm
> +		if(M.mind.vampire)
M.mind might be null

2017-07-31 04:04 UTC, Cruix commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	description = "A miracle chemical. One that's never been seen before."
One that has never been seen before

2017-07-31 04:04 UTC, Cruix commented on code/game/gamemodes/vampire/vamp_powers/vamp_300.dm
> +		vbat.verbs += /mob/living/simple_animal/hostile/bat/vampire/verb/humanform
This is a verb, so all vampire bats will have this by default

2017-07-31 04:15 UTC, X-TheDark commented on code/_onclick/click.dm
> +				security_scan_status(src, A, allowed_access) // check hud.dm
What does this change do, if you don't mind me asking?

2017-07-31 04:42 UTC, X-TheDark commented on code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
> +	vamp.status_flags &= GODMODE
Pretty sure it's `status_flags -= GODMODE`, actually, as status_flags is a list now.

2017-07-31 07:55 UTC, ShadowDeath6 commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	description = "A miracle chemical. One that's never been seen before."
if it's never been seen before wouldn't it be better to call it an unidentified reagent or something

2017-07-31 12:50 UTC, AdamElTablawy commented on code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
> +	vamp.status_flags &= GODMODE
Why does the bat get godmode

2017-07-31 13:40 UTC, X-TheDark commented on code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
> +	vamp.status_flags &= GODMODE
Not the bat, it's the vampire inside that gets GODMODE, presumably, so the vampire doesn't get double-damage from explosions (even small ones).

2017-08-01 21:17 UTC, Super3222 commented on code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
> +	vamp.status_flags &= GODMODE
It's to prevent their human mob from suffocating from being placed inside of the bat. Shapeshift (wizard spell) does something similar to this.

2017-08-01 21:18 UTC, Super3222 commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	race = /datum/species/plant
It seems to have been fuckery from a merge conflict.

2017-08-01 21:19 UTC, Super3222 commented on code/game/gamemodes/vampire/vdatum.dm
> +/datum/vampire/proc/add_blood(amount, amthigh, amtlow)
When I was designing the vampire datum I wanted to leave potential for the future so in case someone (or even Adam) comes up with a crazy idea it could have a system for it.

2017-08-01 21:20 UTC, Super3222 commented on code/game/gamemodes/vampire/vampire.dm
> +	vampire.current << "<B><span class='announcevampire'>You are a Vampire.</font></B>"
Probably, yeah.

2017-08-01 21:21 UTC, Super3222 commented on code/game/gamemodes/vampire/vamp_powers/vamp_400.dm
> +		R.take_damage(100)
I wanted to make it as loud as possible, and more powerful than a shadowling or horrorform shriek (w/o horrorforms intense stun). But if you want it to be 7 instead of 12 just to keep things in close range I can do that.

2017-08-01 21:23 UTC, Super3222 commented on code/game/gamemodes/objective.dm
> +				pass = owner.vampire.eighthundred_unlocked
They make pass TRUE or re-assign it as FALSE though. How're they backwards?

2017-08-01 21:25 UTC, Super3222 commented on code/_onclick/click.dm
> +				security_scan_status(src, A, allowed_access) // check hud.dm
Merge conflict covfefe. I was probably trying to keep my changes to vampire click abilities.

2017-08-02 13:46 UTC, X-TheDark commented on code/game/gamemodes/objective.dm
> +				pass = owner.vampire.eighthundred_unlocked
Cruix meant this
    if(800)
        pass = owner.vampire.>>thousand_unlocked<<

2017-08-02 13:48 UTC, X-TheDark commented on code/game/gamemodes/vampire/vamp_powers/vamp_400.dm
> +		R.take_damage(100)
It's not the number that bothers me, it's that it's different for several types of stuff. 7 for one, 12 for some others.

Either make all of them 7 or make all of them 12.

2017-08-05 17:08 UTC, AdamElTablawy commented on code/game/gamemodes/vampire/vamp_powers/vamp_100.dm
> +		if(get_dist(user, living) > 7) // 7 range
IIRC this means a vampire can hit anyone outside of 7 tiles, which is hysterical but not what anyone wants

2017-08-06 13:00 UTC, Super3222 commented on code/game/gamemodes/vampire/vdatum.dm
> + their coffin.
This is what it looks like in the code (I'm still reverting it though): https://image.prntscr.com/image/9eraY7QJRP_dB2q300doCQ.png

2017-08-06 22:51 UTC, ShadowDeath6 commented
now you just need to add the stone mask item so people in lavaland can become vampires

2017-08-07 16:30 UTC, Cruix approved these changes

2017-08-07 18:43 UTC, Cruix commented
Vampires do not show up in check-antags
There is no click delay on biting
Cannot add or remove vampires in the traitor panel
Vampires cannot see their ability cooldowns
Vampires to not take damage in the chapel
Selecting hypnotize for fast-casting puts it on cooldown
During the testmerge, one of the vampires lost all his abilities for no apparent reason

Complaints specifically from Adam:
Vampires die way to fast in light
I cannot pull my own coffin
I cannot select the ghost I want to eat
Sucking all the blood out of someone does not kill them if they ate tons of oxyloss healing chemicals

2017-08-07 20:47 UTC, AdamElTablawy commented
ok, the problems with this mode:

bite has no delay before you bite, meaning you can grab someone and immediately chomp them for -70 blood, and can constantly chain this to kill people in less than two seconds with skillful grab + bite spam

70 blood drain is probably too much

you can bite through hardsuits 

bite doesn't seem to give a notification to anyone nearby

selecting hypnotize puts hypnotize on cooldown, and it has a delay of a while before it actually works, does not have a progress bar, and doesn't need you to be near the guy when using

you cannot swap between vampiric gaze and hypnotize because you can't deselect an ability while it's on cooldown

there's no 'vampire' tab where you can view the cooldowns of abilities

there's no notification for the new abilities you gain, just they suddenly pop up

there's no brief descriptor when you spawn as to what you can do/what you're weak to

you die in the hallways almost immediately, scrap the 'weak to bright lights' shit

you cannot move your own designated coffin

it takes like 15 people to get 700 blood

there's no blood counter so you can't see how much you have or how much an ability will consume

2017-08-10 22:47 UTC, Super3222 commented
# Testmerge Patch

- Added a click delay to bite
- There is now a 3 second delay for bites before you start draining them.
- Vampires are now in check antagonist
- Vampires are now in traitor panel (where you can make someone a vampire or remove it from them)
- Vampires take burn damage (5 every tick) from being in the chapel
- Vampires taking damage from light idea scrapped
- Scrapped the 'coffin can only be summoned by vampire, and not pulled around' idea. Now only the vampire can drag it around. Anyone else's grab will get cancelled out
- While draining blood from someone, if the target runs out of blood their reagents will b drained
- Bat Swarm fixed (shadow you spawn something on a turf of a thing that wasn't been created yet!)
- Draining blood is loud, like it always should have been.
- Vampires can no longer bite through hardsuits
- Hypnotize mechanics are explained better. Ie. after using it your target has to be within rang for four seconds.
- Bat Swarm now randomizes 6-8 bats
- Added CoD to sixhundred unlock. For some reason it wasn't added.
- Drainrate:Drainpayoff ratio deduced from 55:10 -> 30:10
- Hypnotize no longer immediately goes on cooldown
- Added a blood hud so you can track how much blood you have
- Added a vampire tab where you can keep track of cooldowns.

## Images:

![](https://image.prntscr.com/image/ziHOQ9FaQoOXo6e_ymVirw.png)
![](https://image.prntscr.com/image/wo55VxzHS86FAfWGjKQ8tg.png)
![](https://image.prntscr.com/image/t77pfasNT2yOPaab8ie6Cg.png)
![](https://image.prntscr.com/image/IEbGtgASRt60fdZH1xh07A.png)
![](https://image.prntscr.com/image/YEXKySkWQlGe7tQEulEA5Q.png)
![](https://image.prntscr.com/image/5p0T5AYvQH24oGMEZiCC_g.png)
![](https://image.prntscr.com/image/aK6M8yFpRLmdBxhRTV0RiA.png)

### Other stuff:

- For ghost rend to work you need a ghost adjacent to you.
- I have no idea what caused that vampire to lose all of their abilities. Hopefully it comes up again in the future.

2017-08-10 23:29 UTC, ghost commented
how loud is bite

because if i can hear someone sipping blood through a bendy straw in another room that's dumber than the hilarious instant bloodloss meme

2017-08-11 00:49 UTC, ShadowDeath6 commented on code/game/gamemodes/vampire/vamp_misc/vamp_structures.dm
> +			pulledby << "<span class='notice'>You oddly lose grip of [src].</span>"
oddly?

2017-08-11 00:49 UTC, ShadowDeath6 commented on code/game/gamemodes/vampire/vamp_powers/basic.dm
> +		H << "<span class='alertvampire'>This one has a strange odor. It won't do much for you because they're dead.</span>"
remove the first sentence here

2017-08-11 00:51 UTC, ShadowDeath6 commented on code/game/gamemodes/vampire/vamp_misc/vamp_structures.dm
> +			pulledby << "<span class='notice'>You oddly lose grip of [src].</span>"
say somehow or something, not oddly

2017-08-11 00:51 UTC, ShadowDeath6 commented on code/game/gamemodes/vampire/vamp_powers/basic.dm
> +		H << "<span class='alertvampire'>This one has a strange odor. It won't do much for you because they're dead.</span>"
remove the first sentence here if you're saying they're dead outright

2017-08-11 02:15 UTC, ShadowDeath6 commented
@Super3222 in the screenshot it says "The Jalen Beck is now under your control", is that fixed

2017-08-11 02:18 UTC, Super3222 commented
Yes.

2017-08-29 09:43 UTC, nichlas0010 commented
![image](https://user-images.githubusercontent.com/20558591/29814843-032ac344-8caf-11e7-81ee-a985bd66cddc.png)
 👌

2017-08-30 01:19 UTC, ShadowDeath6 commented
what's the status on this pr anyway

2017-09-01 21:16 UTC, Super3222 commented
ready for merge

2017-09-02 01:13 UTC, Cruix commented
Please remove the change to the gamemode file so I don't have to change it back to extended every time I pull from this branch.

I pulled this, made myself a vampire in the traitor panel, and then tried using every ability, as I expected you had already done while testing it yourself.
* You cannot un-vampire a person who did not start the round as a vampire, because making them a vampire does not add them to the vampire list. You can, however, vampire a person more than once, in which case they will get all of the vampire abilities multiple times.
* When you get to the blood level that lets you see ghosts, you will no longer be able to see them if you update your vision (such as by putting on or removing glasses). While you can see them, however, you can also see pipes under the floor. Trying to fix this by calling the level-up proc again on my vampire datum worked, but also gave me more copies of the abilities earned at that level.
* Blood tracking does not work at all. This is probably because the blood_DNA variable is for the DNA of any blood on an object that was put there by hitting someone with it, and as such, neither humans nor blood drips have it set, because they are never used to hit things. Also, blood trails are not of the /obj/effect/decal/cleanable/blood type, so you cannot even try to use the ability on them.
* Cloak of darkness runtimes whenever it is used and does nothing.
* When you use hypnotize, you twirl your finger when the ability is selected but not when you use it. I am not sure if this is intentional. You can also try to put things to sleep that cannot sleep, such as cyborgs and simple animals.
* Charm creature, when used on a friendly mob (I used a corgi), does not delete the mob and spawns a crate mimic. It really should not be deleting mobs in the first place. Also, it should not work on player-controlled mobs at all.
* You do not get a message when you lose your grip on a vampire's coffin.
* Whenever your shriek nearby a grille you hear "Agonizing Shriek whips back and forth repelling the scream!"

2017-09-02 16:02 UTC, Super3222 commented
I checked the code for cloak of darkness (in mutations.dm) and its defines, and nothing looks off. Can I get more information on that runtime.

2017-09-09 20:27 UTC, Super3222 commented
how the new blood track works
![](https://image.prntscr.com/image/WzcZIKK3Q0WDNLwkWBSIQQ.png)

2017-09-11 01:46 UTC, ShadowDeath6 commented on code/game/gamemodes/vampire/vamp_powers/basic.dm
> +		H << "<span class='alertvampire'>You couldn't find who the blood belonged too.</span>"
to

2017-09-11 01:46 UTC, ShadowDeath6 commented on code/game/gamemodes/vampire/vamp_powers/basic.dm
> +			H << "<span class='noticevampire'>[caughthuman] is in the [get_area(caughthuman)], just [dir2text(get_dir(get_turf(caughthuman), get_turf(H)))] from your location.</span>"
I don't think you need the word "just" in this sentence

2017-09-11 01:46 UTC, ShadowDeath6 commented on code/game/gamemodes/vampire/vamp_powers/basic.dm
> +		H << "<span class='alertvampire'>You search for who the blood belongs too.</span>"
to

2017-09-11 01:47 UTC, ShadowDeath6 commented on code/game/gamemodes/vampire/vamp_powers/vamp_100.dm
> +	H.visible_message("<span class='warning'>[H] twirls their finger in a circlular motion.</span>",\
I don't think this is a good idea for a toggleable thing, it should only display a message when you use it. Making it show a message really fucks the stealth aspect and leads to dumb stuff where you hide in a locker and do it to avoid the message

2017-09-11 01:49 UTC, ShadowDeath6 commented on code/game/gamemodes/vampire/vamp_powers/vamp_1000.dm
> +	name = "Set Summon Turf"
I'd say "location" rather than turf, it's preferential though

2017-10-05 02:59 UTC, Slinky5890 commented
Siiigh, and we were so close

2017-10-05 03:22 UTC, ShadowDeath6 commented
let him rest

2017-10-14 00:36 UTC, AdamElTablawy commented
GIVE ME THE SUCC.

2017-11-16 20:12 UTC, Slinky5890 commented
Monthly reminder we almost had this

2017-11-19 02:10 UTC, Cruix commented
* The default gamemode is still Vampire when it should be extended.
* You still cannot un-vampire a person who did not start the round as a vampire, and you still can vampire them more than once, in which case they will get all of the vampire abilities multiple times.
* While having ghost vision no longer lets you see pipes, it does make your darkness vision no longer work.
* Cloak of darkness still runtimes whenever it is used and does nothing.
* When you use hypnotize, you still twirl your finger when the ability is selected but not when you use it.
* Charm creature, when used on a friendly mob will teleport the mimic to you.
* Blood tracking now crashes the server.

Please test every ability once as a bare minimum of testing before reopening this.

2017-11-19 02:10 UTC, closed without merging

2017-11-30 11:35 UTC, AdamElTablawy commented
@Super3222 LI V E

2017-12-25 23:52 UTC, Super3222 commented
![image](https://user-images.githubusercontent.com/16735500/34343628-a30a6084-e9a4-11e7-9051-9507ef2ab5ae.png)