Boomerang & Frisbee
yogstation13/yogstation-2017- pull request #2272
Opened 2017-06-08 17:16 UTC by Time-Green

[typing desc k??? k]

2017-06-08 18:10 UTC, Cruix commented on code/game/objects/items/toys.dm
> +	var/new_y = target.y*2 - thrower.y
Do you know what this is going to do if you stand above and to the right of 128,128?

2017-06-08 18:33 UTC, Time-Green commented on code/game/objects/items/toys.dm
> +	var/new_y = target.y*2 - thrower.y
Create a new variable with the new coordinate?

2017-06-08 18:42 UTC, Jc1469 commented on code/game/objects/items/toys.dm
> +	var/new_y = target.y*2 - thrower.y
are target coordinates relative or actual station coordinates.

2017-06-08 18:44 UTC, Cruix commented on code/game/objects/items/toys.dm
> +	var/new_y = target.y*2 - thrower.y
It is going to make the Frisbee fly out of bounds if you throw it at the edge of the map

2017-06-08 18:48 UTC, Time-Green commented on code/game/objects/items/toys.dm
> +	var/new_y = target.y*2 - thrower.y
For jc:
They are the actual coordinates, not relative.

Way it works is, it takes the difference between the two, and then add that to the target loc

To cruix: shit, thats a problem I assume
target.x - thrower.x would be relative.
To make it accurate, you'd need to add the targets coordinates. And instead of using target + target - thrower, I just made it target*2 - thrower since that looks cooler

2017-06-08 18:59 UTC, Jc1469 commented on code/game/objects/items/toys.dm
> +	var/new_y = target.y*2 - thrower.y
/me raises hand.  

what if you throw it from say 100,100 to 95,95.  what then?

2017-06-08 19:38 UTC, Alek2ander requested changes

2017-06-08 19:38 UTC, Alek2ander commented on code/game/objects/items/toys.dm
> +	..()
Is it supposed to call parent proc twice?

2017-06-08 19:38 UTC, Alek2ander commented on code/game/objects/items/toys.dm
> +	var/new_y = target.y*2 - thrower.y
You should use get_turf just in case, target atom might have weird coords because that always happens for some reason. And yeah, needs to be clamped to valid x/y values, or target will be null.

2017-06-08 20:16 UTC, Time-Green commented on code/game/objects/items/toys.dm
> +	..()
Oh, haha, I forgot the make it return ..()
Nah, not intended

2017-06-08 20:19 UTC, Time-Green commented on code/game/objects/items/toys.dm
> +	..()
I cant actually comment on the other comment, so ill do it here.

Turf one is a good idea, and the clamp thing was told by jc of all people
>Also, totally spin=1 for both of them.

Thats not how frisbee works

2017-06-09 08:27 UTC, Frostben commented
totally make a syndie version of these that can chop off a limb when you throw it at someone.

2017-06-10 16:52 UTC, Time-Green commented
I used clamping and it works.
I tested it, and throwing at the edge just makes it land at the edge, instead of falling right under you

2017-06-12 11:36 UTC, Alek2ander approved these changes

2017-06-12 12:23 UTC, drderp3635 commented
Add a syndicate boomerang that comes with a free safari hat, that does a knockdown/short stun when thrown at legs or head respectively, and 3 times more damage to carps

2017-06-12 13:44 UTC, Time-Green commented
Drderp, I thought about the concept of adding a traitor weapon, then I realized how disgustingly OP that would be. I really like the idea, but it would need a serious downside for it to not be death on a boomerang

2017-06-12 21:43 UTC, Nickvr628 commented
It has a downside. You have to pick it up every time or else you lose it.

5 TC would be a fair price.

2017-06-13 05:12 UTC, Time-Green commented
Not really, the point of a boomerang is that it comes back, and you automagicly catch it

2017-06-21 19:31 UTC, Frostben commented
How about the boomerang has a certain range when you throw it before it flies back to you. If it hits someone however then it won't come back to you because hey it just hit a solid object.

2017-06-27 01:19 UTC, merged