Reduces brain damage caused by adminhelp.
yogstation13/yogstation-2017- pull request #2331
Opened 2017-06-26 23:04 UTC by Jc1469

Reduces brain damage caused by using ahelp.  

This is a balance change and nothing more.  Ahelp should not be causing brain damage.

2017-06-26 23:04 UTC, MayhemSailor commented
All of this.

2017-06-26 23:09 UTC, AshCorr commented on code/modules/admin/tickets/admin_ticket_verbs.dm
> +	var/obscurevariablebeingusedforthis = alert("Which do you wish to use?", "Admin-help Redirect", "Adminhelp", "Wiki", "Bug Report")
I hate you.

2017-06-26 23:13 UTC, MayhemSailor commented on code/modules/admin/tickets/admin_ticket_verbs.dm
> +	var/obscurevariablebeingusedforthis = alert("Which do you wish to use?", "Admin-help Redirect", "Adminhelp", "Wiki", "Bug Report")
It helps with player induced brain damage...

2017-06-26 23:14 UTC, AshCorr requested changes

2017-06-26 23:14 UTC, AshCorr commented on code/modules/admin/tickets/admin_ticket_verbs.dm
> +		usr << "<span class='ticket-status'>Here is a link to the TGStation wiki: https://tgstation13.org/wiki/Main_Page</span>"
I think you made a typo here, wiki.yogstation.com is spelt W-I-K-I-.-Y-O-G-S-T-A-T-I-O-N-.-C-O-M

2017-06-27 05:16 UTC, Time-Green commented
Did you even test this? What the code is gonna do:
1. Type a message
2. Ask the wiki, bug report something
This is gonna make worse then it already is.
Also, if I were already talking with an admin, what would prevent me from getting THAT prompt everytime?

2017-06-27 07:43 UTC, Kmc2000 commented
You da man

2017-06-27 10:45 UTC, Jc1469 commented on code/modules/admin/tickets/admin_ticket_verbs.dm
> +		usr << "<span class='ticket-status'>Here is a link to the TGStation wiki: https://tgstation13.org/wiki/Main_Page</span>"
We agreed to not use the yogstation wiki, and to use the TG one instead.  In a few places ours looks like spaghetti was thrown at the screen.

2017-06-27 10:47 UTC, Jc1469 commented
> Also, if I were already talking with an admin, what would prevent me from getting THAT prompt everytime?

Maybe the fact that every time you ahelp it might not be for the same thing.  ?

2017-06-27 16:16 UTC, Time-Green commented
If I am talking to an admin I really dont want to type out my whole message, and then have a stupid pop-up questioning what for.

At least make this not happen in an active ticket and make it give the pop-up before prompting to enter a text. Right now, it makes you type a message, and then it asks you what for.

You really didn't test this, did you?

2017-06-27 17:10 UTC, Jc1469 commented
It doesn't happen if you use the ticket button. It happens if you use the adminhelp verb which isn't actually an adminhelp verb. 

I did test it, thank you very much. nitpick nitpick

2017-06-27 17:24 UTC, Time-Green commented
eh that's fine

2017-06-28 02:55 UTC, Super3222 commented on code/modules/admin/tickets/admin_ticket_verbs.dm
> +		usr << "<span class='ticket-status'>Here is a link to the TGStation wiki: https://tgstation13.org/wiki/Main_Page</span>"
TGstations wiki covers content that Yogstation doesn't have, but at the same time I can see why John wants to link tgs instead of yogs. Our wiki mods need a direction because there's been a big stagnation in wiki development.

The wikia needs
- to promote me to a system administrator with the same powers as Oisin
- to promote all of the wiki mods on the discord channel to a special rank, and make two new channels. one public wiki channel, and another private.
- coders need to have a rank on the wiki, so after getting their PR merged they can jump on it to edit in their changes.
- say we can add an [Update Wiki] tag for wiki editors to monitor.
- the wiki application is outdated and needs to be revamped. for example, it still requires you to state your irl name... which is ridicolous
- a completely different theme, so we can kick off wiki development with a fresh looking wiki instead of what we have now
- possibly MOTIVATION. i don't know what started the drive to sign up to be a wiki mod in the first place, but the most successful wikias out there did it by putting a bargain for antag tokens w/ limits. which is exactly what we need to do for our own. possibly.

2017-06-28 02:56 UTC, Super3222 commented on code/modules/admin/tickets/admin_ticket_verbs.dm
> +		usr << "<span class='ticket-status'>Here is a link to the TGStation wiki: https://tgstation13.org/wiki/Main_Page</span>"
somebody pitch that to groudon

2017-06-28 08:18 UTC, Time-Green commented on code/modules/admin/tickets/admin_ticket_verbs.dm
>  /client/verb/admin_ticket(ticket_title as text)
This gives the person a text pop-up

2017-06-28 08:18 UTC, Time-Green commented on code/modules/admin/tickets/admin_ticket_verbs.dm
> +	var/obscurevariablebeingusedforthis = alert("Which do you wish to use?", "Admin-help Redirect", "Adminhelp", "Wiki", "Bug Report")
And then it asks for what it is.

reverse this

2017-06-28 19:28 UTC, Jc1469 commented
il make a new var entirely so that this doesn't even have to touch the ticket system later
busy for now though

2017-06-28 19:28 UTC, closed without merging