Never option for ghost role pop-up's
yogstation13/yogstation-2017- pull request #2350
Opened 2017-07-01 22:21 UTC by Time-Green

Highly requested by literally everyone including me.
Now that when someone spams for their fucking mining drone to become sentient, you can hit never and you will wont be prompted about that shit again. And you can still get your xenoheadslug! 

For some reason most ghost role spawns used ROLE_ALIEN, wich was defined as "xenomorph". I thought that was retarted and gave them their own ROLE_SPECIAL

:cl:
rscadd: When a ghost role gets prompted, also gives another option: "Never", clicking this will never send you a notification for that kind of mob ever again. Unless you re-join the living in wich case it resets.
tweak: Gives sentience potions and etc their own preference called BE_SPECIAL, instead of sharing the xenomorph preference
/:cl:

2017-07-01 23:57 UTC, Cruix commented
Did you test this?

2017-07-02 00:21 UTC, Cruix requested changes

2017-07-02 00:21 UTC, Cruix commented on code/__HELPERS/game.dm
> +			continue
This will runtime if M is null, which it is for the vast majority of pollCandidates() calls

2017-07-02 00:21 UTC, Cruix commented on code/modules/client/preferences_savefile.dm
> +		var/B_special = 65536
This number is too large for a BYOND bitflag

2017-07-02 00:21 UTC, Cruix commented on code/modules/mob/dead/observer/observer.dm
> +	var/list/rejectedRoles = list()
This should be in the Client, or a subsystem, not in a ghost mob.

2017-07-02 08:11 UTC, Time-Green commented on code/modules/client/preferences_savefile.dm
> +		var/B_special = 65536
What should I do then? Revert it to use the xenomorph preference?

2017-07-02 15:50 UTC, Cruix commented on code/modules/client/preferences_savefile.dm
> +		var/B_special = 65536
It worked on local because you never had to load it from the preferences file. Every time someone connects it will be set to zero.

You can add a new bitflag like we did for PDA bitflags or you can refactor the current system to use a list instead of a bitflag like we did for status_flags.

2017-07-03 19:01 UTC, Time-Green commented
The variable has been moved and the runtime patched.
About the byte storage, I reverted it to alien. It's complicated and something for another PR

2017-07-05 20:54 UTC, Cruix approved these changes

2017-07-05 21:02 UTC, merged