AIs can now change their core lights!
yogstation13/yogstation-2017- pull request #2379
Opened 2017-07-11 23:12 UTC by Kmc2000

### Intent of your Pull Request

Ais can now make their floor light up different colours, comes in a few colours and also PARTY mode

To see it in action, go here:
https://drive.google.com/file/d/0B9VUbibptgF2ek9PNDV3Y3RERGM/view?usp=sharing

#### Changelog

:cl: Kmc2000
rscadd: AIs can now change their floor lights! check your AI commands tab.
tweak: Mappers, the AI floor will only change /turf/open/floor/bluegrid/AI, not the regular one, keep that in mind.
/:cl:

2017-07-11 23:14 UTC, ShadowDeath6 commented
cool

I'd disable the move during the malf countdown

also party mode seems like it would lag a bit

2017-07-11 23:16 UTC, Kmc2000 commented
>countdown

Meh, could do but i dunno if it's a massive issue.

2017-07-11 23:35 UTC, krgii commented
Looks good.

2017-07-12 00:02 UTC, Jc1469 commented
tbh AI has enough ways to kill people, irl with epilepsy seems a bit OP.

balance police do not approve.

2017-07-12 00:03 UTC, Kmc2000 commented
Balance police have no jurisdiction here, this case falls under the Federal Balance Institute's authority

2017-07-12 02:46 UTC, ShadowDeath6 commented on code/modules/mob/living/silicon/ai/ai.dm
> +			src << "ERROR lighting circuits overriden by outside forces, perhaps the self destruct sequence has been activated?."
?.

2017-07-12 07:54 UTC, Alek2ander requested changes

2017-07-12 07:54 UTC, Alek2ander commented on code/modules/mob/living/silicon/ai/ai.dm
> +	for(var/turf/open/floor/bluegrid/AI/A)
Iterating over everything in world = no
There's a list of nuke_tiles

2017-07-12 07:54 UTC, Alek2ander commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +		for(var/turf/open/floor/bluegrid/AI/A)
Iterating over everything in world = no
There's a list of nuke_tiles

2017-07-12 07:54 UTC, Alek2ander commented on code/game/turfs/simulated/floor/misc_floor.dm
> +	var/nuking = 0 //is a nuke active?
Why are you storing redundant copies of the nuking state in a dozen floor tiles? Put that in ticker.

Actually, I'm pretty sure this is already somewhere in ticker, just use that.

2017-07-12 16:26 UTC, Qustinnus commented
atleast your code isn't full of whitespace this time

2017-07-12 19:00 UTC, drderp3635 commented
would this change the color of the tiles in the xeno kill chamber?

2017-07-12 19:17 UTC, matskuman5 commented
I like it, but

Can't you just make it check for tiles in the AI core and upload area? To prevent what Alek and Drderp brought up?

2017-07-12 19:17 UTC, matskuman5 commented
>Add more commits by pushing to the master branch on Kmc2000/yogstation-1.

fucking UNCLEAN MASTER BRANCH REEEEEEEEEEEEE

2017-07-13 05:48 UTC, Kmc2000 commented
These are seperate tiles that ONLY affect the AI's core

2017-07-13 05:54 UTC, Kmc2000 commented
moving this from master branch

2017-07-13 05:54 UTC, closed without merging