Fixes a crate
yogstation13/yogstation-2017- pull request #2415
Opened 2017-07-23 09:23 UTC by Zostroll

A crate is no longer 450 credits were the return price for a crate was 500 it also randomly picks one of the new shoes added.

2017-07-23 09:44 UTC, ghost requested changes

2017-07-23 09:44 UTC, Qustinnus commented on code/modules/cargo/packs.dm
> +	switch(loot)
What the fuck dont do it like this

2017-07-23 09:51 UTC, Zostroll commented on code/modules/cargo/packs.dm
> +	switch(loot)
Yeah this is like my third time coding... What is a better way you would suggest?

2017-07-23 10:08 UTC, Jc1469 commented on code/modules/cargo/packs.dm
> +	switch(loot)
contains = rand(1,10)
switch(contains)
      (big block of 1-10's)

I do kind of agree that this is a bit excessive for a box of shoes though.

Reason for errors I imagine is the parenthesis before var/loot because there isn't a closing one anywhere.

2017-07-23 10:37 UTC, Time-Green commented on code/modules/cargo/packs.dm
> +	switch(loot)
Why use a var at all?
switch(rand(1,10))

2017-07-23 11:51 UTC, AshCorr requested changes

2017-07-23 11:51 UTC, AshCorr commented on code/modules/cargo/packs.dm
> +	contains = pick(/obj/item/clothing/shoes/sneakers/nmd/collab,/obj/item/clothing/shoes/sneakers/nmd,/obj/item/clothing/shoes/sneakers/yeezy/black,/obj/item/clothing/shoes/sneakers/yeezy/orange,/obj/i
`/datum/supply_pack/misc/yeezy` This part of the code is called the `initializer` and it only lets you define and initialize variables, and it wont let you run any normal code in it such as `pick()`

If you want the crate to have a random sneaker in it you need to use what is called a constructor `/datum/supply_pack/misc/yeezy/New()`

```
/datum/supply_pack/misc/yeezy/New()
	contains = list(pick(/obj/item/clothing/shoes/sneakers/nmd/collab,/obj/item/clothing/shoes/sneakers/nmd,/obj/item/clothing/shoes/sneakers/yeezy/black,/obj/item/clothing/shoes/sneakers/yeezy/orange,/obj/item/clothing/shoes/sneakers/yeezy)
```

2017-07-23 11:54 UTC, AshCorr commented
Changelog please.

2017-07-23 13:25 UTC, Super3222 commented
Could you perhaps delete the crate altogether?

2017-08-10 18:46 UTC, Cruix commented
Leave a comment

2017-08-10 18:46 UTC, closed without merging