Removes /tg/
yogstation13/yogstation-2017- pull request #2420
Opened 2017-07-24 21:08 UTC by nichlas0010

### Intent of your Pull Request

The cargo computer used to say "/tg/ station 13 Cargo Department". Now it says "[station-name-here] Cargo Department"

![image](https://user-images.githubusercontent.com/20558591/28544849-0382cc70-70c5-11e7-931b-fb21756e88c2.png)

#### Changelog

:cl:
/:cl:

2017-07-24 21:36 UTC, Qustinnus commented
good branch name

2017-07-24 22:24 UTC, Cruix requested changes

2017-07-24 22:24 UTC, Cruix commented on code/game/objects/items/devices/PDA/cart.dm
> +			var/logged_in = "[station_name] Cargo Department"
This should be station_name(), not station_name. The proc will generate the name if it is currently blank.

2017-07-24 22:24 UTC, Cruix commented on code/modules/stock_market/computer.dm
> +	dat += "<span class='user'>Welcome, <b>[station_name] Cargo Department</b></span><br><span class='balance'><b>Credits:</b> [balance()] </span><br>"
Same here

2017-07-24 22:31 UTC, Cruix approved these changes

2017-07-26 19:32 UTC, ShadowDeath6 commented
good pr

2017-07-29 00:04 UTC, merged