Donators can now use their custom borg/ai skins!
yogstation13/yogstation-2017- pull request #2438
Opened 2017-07-30 01:52 UTC by Kmc2000

Refer to: https://forums.yogstation.net/index.php?threads/calling-all-donors.14306/
### Intent of your Pull Request

See above, 

As @Cruix  was busy, I did it myself, the code could likely use improvement, and I can't think of a way around donors without custom skins being able to go invisible, so please review this, thanks.

As the title implies, the first batch of custom skins are now in. The bolt/unbolt addition is for kurugii, as his skin wouldn't work without it.

I would like extra testers for this to double check the ckeys are good to go, if you are a donor and I got your ckey wrong DM/PM me and I'll correct it.

So, it works as intended, but I need to think of a way to get around people picking the "custom" skin when they don't have one, so they go invisible. I would also like to add HUDs to the borgs so people know what they are (most of them are pretty wacky/weird)

#### Changelog

:cl: Kmc2000
rscadd: Donators can now apply for a custom borg and AI skin, go here for details :https://forums.yogstation.net/index.php?threads/calling-all-donors.14306/
/:cl:

2017-07-30 08:47 UTC, ShadowDeath6 commented on code/modules/mob/living/silicon/ai/ai.dm
> +		if(ckey == "kurugii") //snowflake check here, as he's the only one who needs this custom animation, add more as you wish with ||
Don't do it like this. This makes it annoying to maintain and looks really sloppy.

2017-07-30 08:48 UTC, ShadowDeath6 commented on code/modules/mob/living/silicon/robot/robot.dm
> +	if(CustomSkinCheck) // if theyre a donator, who should have a custom borg skin
Can you not just use (is_donator) here instead?

2017-07-30 08:49 UTC, ShadowDeath6 commented on code/modules/mob/living/silicon/robot/robot.dm
> +			desc += "They appear to be a standard borg" //testing
Move all of these to a single module check in robot/examine.dm and it should work

2017-07-30 08:51 UTC, ShadowDeath6 commented on code/modules/mob/living/silicon/robot/robot.dm
> +		src << "<span class='warning'><font size=3>Oh hi [src.ckey], thanks for donating! If you have NOT had a custom borg skin made for you, do not pick the skin option with your ckey, and message Kmc#74
If they don't have a custom skin it shouldn't let them pick a custom skin at all

2017-07-30 10:14 UTC, Time-Green commented on code/modules/mob/living/silicon/ai/ai.dm
> +		if(ckey == "kurugii") //snowflake check here, as he's the only one who needs this custom animation, add more as you wish with ||
I agree with shadow, couldn't you just make a .txt file with what ckey gets what skin?

2017-07-30 16:45 UTC, Time-Green commented on code/modules/mob/living/silicon/ai/ai.dm
> +				if(A == ckey && is_donator(src))
Split this up. 
if(A == ckey)
     if(is_donator(src))
     else if
      else

I made a mistake, this would mean that the person gets the message in else for every single line in that txt file, till it hits the right one at least

2017-08-03 09:59 UTC, AshCorr requested changes

2017-08-03 09:59 UTC, AshCorr commented on code/modules/mob/living/silicon/ai/ai.dm
> +					if(is_donator(src))
Unecessary.

2017-08-03 09:59 UTC, AshCorr commented on code/modules/mob/living/silicon/ai/ai.dm
> +					else if(is_donator(src))
this code in pseudocode looks like this
```
if player is a donator
    Do Something
if they're not a donator but are a donator
    Do something else.
```
The elseif code is never going to get ran

2017-08-03 09:59 UTC, AshCorr commented on code/modules/mob/living/silicon/ai/ai.dm
> +						src << " You are not a donator, no custom skin for you!, donate at https://www.yogstation.net/index.php?do=donate"
This code will most likely never get ran, donators are only updated when server restarts, move it elsewhere and get rid of all the unecessary calls to ìs_donator`

2017-08-03 09:59 UTC, AshCorr commented on code/modules/mob/living/silicon/ai/ai.dm
> +	if(icontype == "Custom")
Did you test this? There is no `Custom` icontype in the input list, this code seems obsolete anyways because of the above code.

2017-08-03 09:59 UTC, AshCorr commented on code/modules/mob/living/silicon/robot/robot.dm
> +	if(is_donator(src)) // if theyre a donator, who should have a custom borg skin
if, they're, a, donator, who, should, have, a, custom, borg, skin

I think you see where im going with this

2017-08-03 09:59 UTC, AshCorr commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +			else if(is_donator(R))
More unecessary is_donator calls, its only updated between rounds unless an admin intervenes

2017-08-03 09:59 UTC, AshCorr commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +				src << " You are not a donator, no custom skin for you!, donate at https://www.yogstation.net/index.php?do=donate"
If you really want to send them a message you need to move it to the parent ìf`` else chances are its never going to be called

2017-08-03 09:59 UTC, AshCorr commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> -	donator_skins = list("Eve" = "eve")
Why remove Eve?

2017-08-03 11:34 UTC, Time-Green commented
Cruix already made this. I don't think this PR is needed anymore

2017-08-03 11:34 UTC, closed without merging