Introduces Weeping angels, Mutation toxin for the mob and a fix to an NTP admin issue.
yogstation13/yogstation-2017- pull request #2455
Opened 2017-08-03 02:12 UTC by sam0oneau

**Fixed NTP Admin Issue:**
Whenever NTPs spawn now their crimes are told to admins. This ensures NTPs must follow their RP roles and can't just murderbone.

**Adds new mob (Weeping angel):**
Introduces a new mob for use with the transformation toxin (Serum of despair). Mob's Ai is strictly similar to statues created by wizards.

**Adds new mutation toxin for chemists:**
The new mutation toxin will transform the user into a new mob (Weeping_angel) if they are unconscious. If they are conscious it deals toxin damage unless they have 60+ brute/toxin and then instead it will transform them into a cat (Cause why not, its fun :P). It is crafted with 10u of uranium, 10u of Charcoal, 10u of Plasma, 10u of frost oil, 10u of corn oil, 10u of methamphetamine and is designed for high level chemists.

First time using Github Pull function so maybe be a mistake in location if doesn't compile.

Refer to issue #0.

### Intent of your Pull Request

Type here what the purpose of your PR is. Also set the issue number above, or delete the line if this PR is not related to an issue. You can type "Fixes issue #6" and issue 6 will be automatically closed as your pull request is merged. Much easier for everyone if you do that.

#### Changelog

:cl:
rscadd: Changelog template, please edit me.
/:cl:

2017-08-03 02:42 UTC, MenacingManatee commented
I'm not understanding your choice in reagents for the mutation toxin, or why you want them to become a cat if they're conscious and have enough damage. I also don't really like the prisoner admin log, as that seems like something that'll just add to the admin log spam. Prisoner crimes are already recorded in their notes which an admin can view in their panel. Weeping angel seems like a cool mob though

2017-08-03 02:57 UTC, MenacingManatee commented on code/modules/reagents/chemistry/recipes/others.dm
> +	required_reagents = list("uranium" = 10, "charcoal" = 10, "plasma" = 10, "frostoil" = 10, "cornoil" = 10, "methamphetamine" = 10) //Placeholder name and recipe
You've got the toxin itself as a subset of stable slime toxin, but you don't actually include any slime toxins. Is this intentional?

2017-08-03 03:06 UTC, MenacingManatee commented on code/modules/mob/living/simple_animal/hostile/weeping_angel.dm
> +	harm_intent_damage = 70
this seems like a pretty absurd amount of damage, though if they're made of stone I suppose it makes sense

2017-08-03 07:17 UTC, AshCorr requested changes

2017-08-03 07:17 UTC, AshCorr commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		if(method != TOUCH && H.stat == UNCONSCIOUS){
Dont use `{` just use tabs to indent it, brackets are unecesarry

2017-08-03 07:17 UTC, AshCorr commented
> Adds new mob (Weeping angel):
> Introduces a new mob for use with the transformation toxin (Serum of despair). Mob's Ai is strictly similar to statues created by wizards.

But....why? we have a mob for weeping angels already... You've just copied its code and tinkered with a few variables, if you want to edit its health then create a subtype for the existing angels

````
/mob/living/simple_animal/hostile/statue/minor
    health = 50
    maxhealth = 50
````

2017-08-03 07:18 UTC, AshCorr requested changes
i swear if i ever use githubs review system properly it'll be a miracle

2017-08-03 07:18 UTC, AshCorr commented on code/modules/reagents/chemistry/recipes/others.dm
> +////////////////////////////////// Test Chemical ///////////////////////////////////////////////////////////
Dont forget to remove your placeholder names...

2017-08-03 07:18 UTC, AshCorr commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +//Test Toxin
Dont forget to remove your placeholder names...

2017-08-03 07:18 UTC, AshCorr commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +////////////////////////////////// Test Chemical ///////////////////////////////////////////////////////////
Dont forget to remove your placeholder names...

2017-08-03 07:55 UTC, ShadowDeath6 commented on code/modules/mob/living/simple_animal/hostile/weeping_angel.dm
> +	desc = "An incredibly lifelike marble carving. Its eyes seems to follow you.." // same as an ordinary statue with the added "eye following you" description
...

2017-08-03 08:08 UTC, AshCorr commented on code/modules/mob/living/simple_animal/hostile/weeping_angel.dm
> +	desc = "An incredibly lifelike marble carving. Its eyes seems to follow you.." // same as an ordinary statue with the added "eye following you" description
https://github.com/yogstation13/yogstation/pull/2455/files#diff-37c9a4b0e01ce56486c150228c427e14R601

2017-08-03 11:19 UTC, Mrcreepssss commented
so ehh, how do they play?

2017-08-03 11:43 UTC, sam0oneau commented on code/modules/reagents/chemistry/recipes/others.dm
> +	required_reagents = list("uranium" = 10, "charcoal" = 10, "plasma" = 10, "frostoil" = 10, "cornoil" = 10, "methamphetamine" = 10) //Placeholder name and recipe
So yes and no, Originally it used aslimemutation and tried to branch off the original mutation toxin code. I think in its current state that I could cut ties. But thought for accessibility reasons it should part of the slime toxin as it is a mutation toxin. Its not a hard chance to give its own subset.

2017-08-03 11:50 UTC, sam0oneau commented on code/modules/reagents/chemistry/recipes/others.dm
> +////////////////////////////////// Test Chemical ///////////////////////////////////////////////////////////
Will do. More put up push to see if people could discover issues. Will fix this, thanks.

2017-08-03 11:50 UTC, sam0oneau commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		if(method != TOUCH && H.stat == UNCONSCIOUS){
Yeah from a C++ background, was talking to friend about this about how Byond is about indentation instead of curly brackets. Yeah I think this is the only place where this mistake occurs as later on I was more use to byond, thanks

2017-08-03 12:39 UTC, Ratvar commented
They cannot move when people see them, they can inflict blindness and flicker lights ala ghost boo in area,  sees things through wall, have nightvision and decent melee. Currently made by staff of animating turntostone statues in wizerd mode or with used book of forcewall and magicarps of xenobio.

2017-08-03 15:19 UTC, Mrcreepssss commented
but, if they can't move when seen, how can they deal damage? with the lights stuff what about nightvision stuff? and blindness leaves vision to the tiles right next to you, does that count as seen?

2017-08-03 17:14 UTC, Ratvar commented
Blind people cannot see you. Next to you thing is mehy stuff, doesn't count. Just blind anyone with nightvision. They have weakness-in wiz mode, they rewert back when turn to stone spell time ends, on other hand, they serve wiznurd loyally and also player controlled. In all other cases-RCD them in cube of walls and work in team, cause they got long KD on spells. They also have immensive health,or something

2017-08-03 17:58 UTC, Jc1469 commented
On the NTP thing.  We actually do have that logged via their memories.  And having it on spawn for them isn't going to do anything at all except make us scroll up a bunch, probably to only see that it's gone.
Staff just need to notice that it's in their memories really.

2017-08-03 19:23 UTC, sam0oneau commented
@Ratvar I think I partially agree with you that they do seem quite weak with the current implementation. I'll try add some interesting magic ability to them for gameplay purposes. One of the things I may add tonight while I fix the other edits, is maybe a way for angels to move items but in a interesting way like teleportation. This would give some interesting gameplay for antags, as they can use weeping angels to get objects. I'll play around with a few things to make them more interesting, mainly released the push to get people's opinions.

2017-08-09 20:17 UTC, AdamElTablawy commented
wowie!

this can go in the 'shit idea' pile because it's a reskinned normal statue with barely any important tweaks for no particular reason

bye

2017-08-10 21:11 UTC, sam0oneau commented
Adam read the comments you autistic, I only pushed the pull to see what people's opinions were, this is nowhere near finished.

2017-08-10 21:11 UTC, sam0oneau commented
Autist* phone autocorrect :'(

2017-08-10 21:26 UTC, sam0oneau commented
@AdamElTablawy so currently im working on trying to make it an interesting antag item. The push was a PoC to get attention from the community, then sometimes when I have time to work on it I like to add to it and improve it. Yeah I think when I made it I tried to make clear it was initially a mostly a conversion from other code. The final version I hope, will be an interesting mob. Currently I've been toying with lots of ways to make it interesting (teleportation stuff, improvements to how it can deal with high light scenarios (fix to original code), an idea of pulling dead corpses into angels and a few other smaller things like moving antag items). Those features are all things I have working/partially working and when I get back home on Monday I can show you the code if you need something to liven up your dull life. When you want to shut down something don't be a dick.... you really are hated by so many.

2017-09-17 18:15 UTC, closed without merging

2017-09-17 18:16 UTC, Cruix commented
Reopen this when you fix it