A lot of var logging for airlocks and airlock related things.
yogstation13/yogstation-2017- pull request #2458
Opened 2017-08-05 23:08 UTC by Jc1469

i hate airlocks

2017-08-05 23:22 UTC, Qustinnus commented
good pr. might port that to FTL actually

2017-08-06 23:43 UTC, AshCorr requested changes

2017-08-06 23:43 UTC, AshCorr commented on code/datums/wires/airlock.dm
> +	var/obj/machinery/door/airlock/A = holder
:(

2017-08-06 23:44 UTC, Jc1469 commented on code/datums/wires/airlock.dm
> +	var/obj/machinery/door/airlock/A = holder
.

2017-08-06 23:59 UTC, AshCorr approved these changes

2017-08-07 18:12 UTC, merged

2017-08-08 13:40 UTC, Mrcreepssss commented
wai uhh, why is AI control disabled done twice?

2017-08-08 14:28 UTC, Jc1469 commented
Because there's two seperate functions to disable it per instance.  And 2 instances.