Adds in new clothing options (cosmetic pr)
yogstation13/yogstation-2017- pull request #2471
Opened 2017-08-09 13:15 UTC by Kmc2000

### Intent of your Pull Request

Adds in a variety of new clothes, and fixes up the shitty shoes I made so that they're less horrifyingly out of place.

All these items can be found in autodrobes, search for track jacket and trainer and they'll pop up.

I also added a ferrari for fun

PLEASE NOTE:

https://drive.google.com/file/d/0B9VUbibptgF2dW5ta3g4VmRqMnc/view?usp=sharing

The showcase video has some bugged stuff and some sprites that just didn't in it, that's all been fixed for this PR.

Example outfits:

![](https://i.gyazo.com/aea0c968833719cb1190d778b8351912.png)

![](https://i.gyazo.com/f2d8d3e8a70bc3625b801ec8023172a3.png)

![](https://i.gyazo.com/f237b574efbb0d79df6975c34fd79655.png)

![](https://i.gyazo.com/fdc6c232aed273826366e5c7911b1bcb.png)

![](https://i.gyazo.com/3ab8febff044454d978889047bbddbf3.png)

![](https://i.gyazo.com/81c3e4f739bfe3f31e63a9c55ad3e8fd.png)

#### Changelog

:cl:
rscadd: Changelog template, please edit me.
/:cl:

2017-08-09 13:24 UTC, Qustinnus commented
i should ban you from ftl for this

2017-08-09 13:29 UTC, matskuman5 commented
Clothes look fine

Ferrari is stupid but since it's admin only it's ok

Shoes look stupid as always and do we really need references to 2010's fashion that will be out of date in 3.4 seconds

2017-08-09 13:44 UTC, Jc1469 commented
add ferrari to autodrobe tbh

2017-08-09 17:02 UTC, Super3222 commented
England is my city

2017-08-09 17:11 UTC, Oakboscage commented
Please stop adding these fucking sneakers.

2017-08-09 17:31 UTC, Ratvar commented
add fereari themed sneakers and sneaker-themed ferrari

2017-08-10 06:35 UTC, AshCorr commented
cOsMEtIc pR

2017-08-10 06:45 UTC, AshCorr requested changes

2017-08-10 06:45 UTC, AshCorr commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A sporty coat that can be unzipped, it features blue accents."
Using periods at the end of the description here but not at the end of the description on sneakers.

2017-08-10 06:46 UTC, AshCorr commented on code/modules/clothing/shoes/colour.dm
> +
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE I swear im just going to make a script to find all the extra newlines and remove them...

2017-08-10 10:36 UTC, Kmc2000 commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A sporty coat that can be unzipped, it features blue accents."
fixed

2017-08-10 13:25 UTC, matskuman5 commented on code/modules/clothing/head/soft_caps.dm
> +	desc = "A baseball hat with the word superb on the front, this one word is apparently worth 200 credits shipped."
A baseball hat with the word "superb" on the front. This one word is apparently worth 200 credits shipped.

2017-08-10 13:25 UTC, matskuman5 commented on code/modules/clothing/shoes/colour.dm
> +	desc = "Wait a minute these look...ehh probably not, the syndicate only wear combat boots."
Wait a minute, these look... eh, probably not. The syndicate only wear combat boots.

2017-08-10 13:25 UTC, matskuman5 commented on code/modules/clothing/shoes/colour.dm
> +	desc = "Stylish running shoes, the comfy soles give you a spring in your step."
Stylish running shoes. The comfy soles give you a spring to your step.

2017-08-10 13:25 UTC, matskuman5 commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A sporty coat that can be unzipped, it features blue accents."
A sporty coat that can be unzipped. It features blue accents.

2017-08-10 13:25 UTC, matskuman5 commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A track jacket that has a paint splat design on it, it looks kinda like a galaxy, neat."
A track jacket that has a paint splat design on it. It looks kinda like a galaxy, neat.

2017-08-10 13:25 UTC, matskuman5 commented on code/modules/vehicles/sportscar.dm
> +	desc = "A beautiful car, merging the modern nanotrasen ideals with the classic Italian sports car aesthetic, this thing goes F A S T"
A beautiful car, merging the modern NanoTrasen ideals with the classic Italian sports car aesthetic. 
This thing goes F A S T!

2017-08-10 13:26 UTC, matskuman5 commented on code/modules/clothing/head/soft_caps.dm
> +	desc = "A baseball hat with the word superb on the front, this one word is apparently worth 200 credits shipped."
Direct references to real life stuff like this is kinda bullshit.

2017-08-10 14:08 UTC, Qustinnus commented
theres not 20 lines of whitespace between every object you added 2/10

2017-08-10 15:32 UTC, AshCorr approved these changes

2017-08-10 15:43 UTC, Amelia0010 requested changes
Remember to add spaces after dots

2017-08-10 15:43 UTC, nichlas0010 commented on code/modules/clothing/shoes/colour.dm
> +	desc = "Stylish running shoes.The comfy soles give you a spring in your step."
What even are spaces

2017-08-10 15:43 UTC, nichlas0010 commented on code/modules/vehicles/sportscar.dm
> +	desc = "A beautiful car, merging the modern NanoTrasen ideals with the classic Italian sports car aesthetic.This thing goes F A S T!"
Space, the final frontier

2017-08-10 16:08 UTC, Jc1469 commented
ra ra rasputin still missing space it seems

`aesthetic.This`

2017-08-10 16:16 UTC, Amelia0010 requested changes
*sigh*

2017-08-10 16:16 UTC, nichlas0010 commented on code/modules/vehicles/sportscar.dm
> +	desc = "A beautiful car,merging the modern NanoTrasen ideals with the classic Italian sports car aesthetic.This thing goes F A S T!"
you actually removed a space from somewhere it should be, instead of adding a space that's needed. :thailand:

2017-08-10 17:28 UTC, Amelia0010 requested changes
why...

2017-08-10 17:28 UTC, nichlas0010 commented on code/modules/vehicles/sportscar.dm
> +	desc = "A beautiful car, merging the modern NanoTrasen ideals with the classic Italian sports car aesthetic.This thing goes F A S T!"
you still haven't put a space after the bloody dot, god dammit KMC

2017-08-11 00:05 UTC, Kmc2000 commented
![](https://cdn.discordapp.com/attachments/285460304819781632/345356960977125386/merge_my_pr.gif)

2017-08-13 17:29 UTC, merged

2017-08-13 18:27 UTC, Kmc2000 commented
WOOHOO 🎉