Increased water turf-wetting time
yogstation13/yogstation-2017- pull request #2477
Opened 2017-08-11 02:21 UTC by Cruix

Fixes #2109 
Closes #2454 

Water turf-wetting time is now increased by a factor of ten, but it is capped at 50 (approximately 90 seconds). This is how long a full mop will wet a floor for.

:cl: Oakboscage  
rscadd: Wet floors take longer to dry
/:cl:

2017-08-11 03:12 UTC, ghost requested changes
use the define instead.

2017-08-11 03:12 UTC, Qustinnus commented on code/game/turfs/open.dm
> +	if(wet_time >= max_wet_time)
cruix there's already a define for this, Oak's PR was fine. change the define instead

2017-08-11 04:00 UTC, Cruix commented on code/game/turfs/open.dm
> +	if(wet_time >= max_wet_time)
The define is for all things that make a turf "wet", including lube and ice. This only affects water specifically.

2017-08-11 04:02 UTC, Qustinnus commented on code/game/turfs/open.dm
> +	if(wet_time >= max_wet_time)
is there really a need for that..? seems extremely snowflakey. also if so change the defines and variables to max_slip_time etc and turn max_wet_time into a define so this remains readable

2017-08-11 04:10 UTC, Cruix commented on code/game/turfs/open.dm
> +	if(wet_time >= max_wet_time)
"Snowflake" refers to code that does a specific check in a way that is not reusable. Adding a new parameter in this way is generic enough for other pieces of code to use.

The define MAXIMUM_WET_TIME and the max_wet_time parameter serve two different purposes. The define is a blanket check that affects all MakeSlippery() operations, while this parameter can be used for individual operations, such as water's reaction_turf(), to reduce the significance of their effect without inhibiting the maximum signifigance of other operations, such as lube.

2017-08-11 04:11 UTC, Qustinnus commented on code/game/turfs/open.dm
> +	if(wet_time >= max_wet_time)
whats the purpose of limiting it in the first place though

2017-08-11 04:12 UTC, Qustinnus commented on code/game/turfs/open.dm
> +	if(wet_time >= max_wet_time)
if someone goes through the effort to make a tile that wet just crowbar it

2017-08-11 04:14 UTC, Cruix commented on code/game/turfs/open.dm
> +	if(wet_time >= max_wet_time)
To reduce the power of a ubiquitously available method of stunning and murdering people and griefing.

2017-08-11 04:14 UTC, Qustinnus commented on code/game/turfs/open.dm
> +	if(wet_time >= max_wet_time)
that's the point

2017-08-11 04:16 UTC, Cruix commented on code/game/turfs/open.dm
> +	if(wet_time >= max_wet_time)
Or you could just walk.

2017-08-11 04:17 UTC, Qustinnus commented on code/game/turfs/open.dm
> +	if(wet_time >= max_wet_time)
see!

2017-08-11 13:52 UTC, Oakboscage commented
Capping it at 50 is terrible. Dumping a bucket of water out on the floor is now just the same as mopping it, and the wet time for mopping is still rather lame. Just use my PR instead.

2017-08-11 14:09 UTC, Cruix commented
Having a bucket add 6 minutes of wetness to a tile is not acceptable.

2017-08-11 15:31 UTC, Oakboscage commented
A) The odd puddle from someone running around with a bucket slipping is very acceptable
B) All you need to do to remove it is crowbar the floor tile

2017-08-11 15:53 UTC, Cruix commented
I am not going to force everyone to carry around a crowbar because the janitor is being a dick.

2017-08-11 15:55 UTC, Qustinnus commented
1/2th the max slippery time then

2017-08-11 16:00 UTC, Oakboscage commented
Crowbars are literally everywhere. And there's this new radical concept of WALKING that you can use to avoid wet floors entirely. And if the janitor is being a dick he'll get arrested or robusted. It really isn't that terrible having a wet floor.

2017-08-11 22:26 UTC, AdamElTablawy commented
i don't feel like there should be a cap-if you're enough of a nutjob to dump 1000u of water on one tile it deserves to be wet forever-but cruix has a point, oak. i can easily forsee tiles being wet for-fucking-ever in escape and hysterical as the image of a bunch of people constantly slipping and sliding for ten minutes as they desperately try to get onto the shuttle only to slip on someone else is, botany already does that and it's fucking cancerous.

2017-08-11 23:29 UTC, X-TheDark commented
Unfortunately, the "proper" solution would be for it to work like a chem grenade if you dump a bucket of water and have it splash across multiple tiles.

Unfortunately No.2, this isn't exactly a simple solution, plus I fear what would happen if this would be applied to things like High-Capacity Water Tank making the entire station slippery or somesuch.

2017-08-12 02:54 UTC, Oakboscage commented
There already is a cap, it's at 300.

2017-08-12 03:05 UTC, Cruix commented
300 is around 8 minutes on a server that is not lagging. 50 is just less than a minute and a half.

2017-08-12 03:06 UTC, Oakboscage commented
Can we agree on 150?

2017-08-13 17:31 UTC, merged