[Clown Traitor Item] Bikehorn esword
yogstation13/yogstation-2017- pull request #2483
Opened 2017-08-13 15:47 UTC by Time-Green

A clown can now buy an esword disguised as a bikehorn through his uplink for 7 tc. (Same price as normal eswords)

It actives through alt-clicking.

I know this is a straight buff to normal eswords because of the hiding factor, but fuck that only clowns have it.

:cl:
rscadd: adds a new clown traitor item: A bikehorn esword. Activate it by alt-clicking.
/:cl:

[wait for the picture]

2017-08-13 16:25 UTC, Ratvar commented
Foresee security, assistants, scientists and mimes harmbatoning clown for "illegal harrasment" and accidently clicking his bikehorn with alt button on every minute

2017-08-13 16:33 UTC, nichlas0010 commented
![image](https://user-images.githubusercontent.com/20558591/29251487-d284bf2a-8055-11e7-9f2d-7f96dc533dda.png)
that, as well as making it activate on use, like a normal e-sword

2017-08-13 16:34 UTC, Partheo commented
Yes,a honk sound on activation is crucial. And pink esword? Yes.

2017-08-13 17:10 UTC, Ratvar commented
Make people without clumsyness honk their hand off if they try to activate it.

2017-08-13 20:43 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
Traitor clowns are free of clumsiness. 

You should mix the esword activation sound and honking somehow

2017-08-13 20:58 UTC, Time-Green commented
I'm fine with making it pink, but I'm not letting it activate like a normal esword or have it fucking honk on slashing someone

2017-08-13 21:07 UTC, AdamElTablawy commented
what the fuck, time green

why

2017-08-13 21:09 UTC, Time-Green commented
Do people really want it to honk on it?

2017-08-13 21:44 UTC, Partheo commented
yes

2017-08-13 22:00 UTC, AdamElTablawy commented
YES ITS THE FUCKING CLOWN

2017-08-15 16:45 UTC, ShadowDeath6 commented
make it honk on attack as well as the normal esword sound if you don't want to make it cost more, since making it sound like a normal horn would be a huge buff

2017-08-15 17:29 UTC, Time-Green commented
Right, updated.
Now it's pink, honks on slashing and instead of alt activating it, it toggles wheter activating extends the blade or honks

2017-10-19 00:01 UTC, ghost requested changes

2017-10-19 00:01 UTC, MoreRobustThanYou commented on code/game/objects/items/weapons/melee/energy.dm
>  		user << "<span class='warning'>You accidentally cut yourself with [src], like a doofus!</span>"
to_chat

2017-10-19 00:01 UTC, MoreRobustThanYou commented on code/game/objects/items/weapons/melee/energy.dm
>  		user << "<span class='notice'>[src] can now be concealed.</span>"
to_chat

2017-10-19 00:01 UTC, MoreRobustThanYou commented on code/game/objects/items/weapons/melee/energy.dm
> +			L << "<span class='notice'>You squeeze the [name]. It functions like a normal bikehorn again.</span>"
to_chat

2017-10-19 00:01 UTC, MoreRobustThanYou commented on code/game/objects/items/weapons/melee/energy.dm
> +			L << "<span class='notice'>You squeeze the [name]. Honking it will now extend an esword.</span>"
to_chat

2017-11-01 05:09 UTC, Drakkon commented
*sad horn or airhorn on killing blow*

2017-11-29 20:18 UTC, Time-Green commented
@AshCorr Merge conflicts were fixed

2017-12-01 20:34 UTC, merged