Super's Spectacular Sunnyday Successful Safety Satisfaction Sarcastic Scarce Scientific Selection Special Intents PR
yogstation13/yogstation-2017- pull request #2512
Opened 2017-08-25 21:51 UTC by Super3222

### Intent of your Pull Request

Hello everyone! Let me introduce the idea of Special Intents.

Special Intents are different options you can choose when you select one of the main 4 intents. SI's range from hugs to handshakes, punches to kicks, and disarms to parrys.

The addition of SI's to the game will open a gateway of potential for the future. But for this PR alone I will stick to nothing too game changing.

Help Intent:
- Hug
- Brofist
- Handshake

Harm Intent:
- Punch
- Kick
- Bite

Disarm Intent:
- Disarm
- Parry (will be done in second PR)
- Defend (will be done in second PR) 

Grab Intent:
- Only Grab.

There also has been other changes in conjunction with SI's such as:
- Lizards bite damage is now 6-10! Watch out for their fucking bites.
- There's an overlay for kicks (it appears on your hand).
- Kicking someone on the ground adds more damage! Wearing the right shoes makes it hurt!
- You can now kick EVERYTHING! From your own ID card to vending machines!
- Some shoes add more KICKING POWER (jackboots, magboots, swat shoes, clownshoes, etc) like previously mentioned, but also can aid you in PUNTING THINGS farther away.
- Kick a super matter core on meltdown, and there's a 1% chance you'll stabilize it. Might as well if you don't know what the fuck you're doing. Take one for the team!

#### Changelog

:cl:
rscadd: Introducing a new system to the game - Special Intents!
rscadd: SI's are an extension of your normal intents, allowing you to do more than just one command / action while in an intent state.
rscadd: The hotkey for si's is shift + spacebar. If anyone has any better ideas please tell me.
rscadd: Help SI's are hug, handshake, brofist, and give.
rscadd: Harm SI's are punch, kick, and bite.
rscadd: Disarm SI's are disarm, parry, and defend. Parry and Defend won't do anything until my follow up PR.
rscadd: Grab doesn't have any SI's.
Kicks!
rscadd: You can now kick EVERYTHING!
rscadd: Kick the nukedisk across the floor and through an airlock leading into space!
rscadd: Kick a bot punting them through the air!
rscadd: Attempt to kick heavy machinery!
rscadd: Attempt to kick the super matter engine (albeit, it IS possible to stabilize it from kicking it)
rscadd: Kick over a vending machine!
rscadd: Kicking eyeglasses CRUSHES them under your boot.
/:cl:

#### Gameplay / Footage

![](https://image.prntscr.com/image/VvCU7b68Twy1SGjnKqfs2g.png)
--
https://gyazo.com/fe6ffa221f9c630dac034ef1247dab20 - Kicking beepsky
--
https://gyazo.com/12db341b6e494e1fa1e14c6af1e7c54e - Kicking nukedisk
--
![](https://image.prntscr.com/image/dp4AnSfcRSyurgrv2E-6PQ.png)
--
![](https://image.prntscr.com/image/GztRDtSwQoSMjsPw74YBTg.png)
--
![](https://image.prntscr.com/image/IvW843XqSeKZ2WIH2b4Rzw.png)
--

2017-08-25 21:58 UTC, AdamElTablawy commented
>being able to default to throw mode w/o aggressive grabs

>being able to kick simple mobs away

>being able to punt a full grown human with your feet

Bad

2017-08-25 22:05 UTC, Super3222 commented
You can't kick every simple mobs away. I made sure only specific ones could be kicked. (ie, bots, pets like ian, crabs, etc.). I kept it realistic.

You also can't punt humans. Kicking them only does damage.

2017-08-25 22:20 UTC, Super3222 commented
You can't kick every simple mob away. I made sure only specific ones could be kicked. (ie, bots, pets like ian, crabs, etc.). I kept it realistic.

You also can't punt humans. Kicking them only does damage.

2017-08-25 22:23 UTC, Kmc2000 commented
This is a pretty intents pr...

2017-08-25 23:26 UTC, ShadowDeath6 commented
Did you mean: Fistbump?

2017-08-25 23:55 UTC, Kmc2000 commented
can you kick the nuke?

2017-08-26 00:05 UTC, Super3222 commented
> Did you mean: Fistbump?

Yes.

> can you kick the nuke?

Yes, if it's un-anchored. It'll only move 1 tile though.

2017-08-26 01:15 UTC, Jc1469 commented
Fistbumping :thinking: 
clawed lizards do more damage with bites even though some are aquatic :thinking: 
kicking beepsky away is a feature, that thing that's meant to arrest people. :thinking: 
kicking nuke disk out of airlocks is a feature :thinking: 
shitcurity, clown, or anyone that walks into dorms can now kick people for more damage :thinking: 

>// Super: No

2017-08-26 01:15 UTC, Jc1469 commented
I'm trying to see the good in this, but the fact that you're highlighting the bad things makes that a lot harder.

2017-08-26 01:21 UTC, Kmc2000 commented
>1 agree
>2 Fuck lizards who needs to be concerned with them the only good lizard is a pile of ashes
>3 Feature, but may want to make that stun you.
>4 You could always throw it out, it'll just respawn anyways
>5 Implying youre unrobust enough to get kicked/hit at all in the first place

2017-08-26 02:55 UTC, Super3222 commented
Basically what KMC said.

> shitcurity, clown, or anyone that walks into dorms can now kick people for more damage

Kick damage's max and min values are by default lower than punch damage's max and min damage. For all instances in a normal round your kick damage still won't be strong enough to surpass 9 brute damage (which is the default punches maximum amount of damage).

2017-08-26 03:38 UTC, Cruix requested changes

2017-08-26 03:38 UTC, Cruix commented on code/_onclick/other_mobs.dm
> +		if(istype(A, /obj) && !(A in GetAllContents())) // so we don't kick anything on ourselves
Check if A.loc is a turf instead, otherwise you could drop a backpack on the ground, open it, and kick the things inside it. It would also be less expensive.

2017-08-26 03:38 UTC, Cruix commented on code/__DEFINES/combat.dm
> +#define BITE "bite"
I would prefer if all of these defines were more long and specific, things like "PUNCH" and "DEFEND" are too likely to be used somewhere else. Something like SPECIAL_INTENT_PUNCH, etc.

2017-08-26 03:38 UTC, Cruix commented on code/game/machinery/machinery.dm
> +	H.visible_message("<span class='danger'>[H] kicks \the [src].</span>", "<span class='danger'>You kick \the [src].</span>")
\the is unnecessary, putting the object in brackets will add a the when necessary.

2017-08-26 03:38 UTC, Cruix commented on code/game/machinery/machinery.dm
> +				sleep(3)
addtimer()
also why did you not just to spawn(3)?

2017-08-26 03:38 UTC, Cruix commented on code/game/objects/items.dm
> +		spawn()
addtimer()

2017-08-26 03:38 UTC, Cruix commented on code/game/objects/items.dm
> +				sleep(5)
All this stuff should probably be done with a new parameter to throw_at() or a new throw_at_arc() proc

2017-08-26 03:38 UTC, Cruix commented on code/game/objects/structures.dm
> +				sleep(3)
addtimer()

2017-08-26 03:38 UTC, Cruix commented on code/game/objects/structures.dm
> +/obj/structure/kick_act(mob/living/carbon/human/H)
This proc is exactly the same as the /obj/machinery one, make a global proc that you pass the object being kicked and the person doing the kicking into, and have  /obj/machinery and /obj/structure call that proc in kick_act().

2017-08-26 03:38 UTC, Cruix commented on code/game/objects/structures/tables_racks.dm
> +	visible_message("<span class='warning'>[H] kicks [src]!<span>")
\</span\>

2017-08-26 03:38 UTC, Cruix commented on code/game/turfs/simulated/walls.dm
> +/turf/simulated/wall/kick_act(mob/living/carbon/human/H)
.turf/simulated should not exist anymore, it was replaced with /turf/closed and /turf/open

2017-08-26 03:38 UTC, Cruix commented on code/modules/clothing/clothing.dm
> +	var/can_be_crushed = FALSE
This var does not seem to do anything

2017-08-26 03:38 UTC, Cruix commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +		if(istype(shoes, /obj/item/clothing/shoes))
istype() will always return false if given a null, the enclosing if() is not necessary.

2017-08-26 04:34 UTC, ShadowDeath6 commented
I'm :-1:ing this pr until you change brofist to fistbump

2017-08-26 13:09 UTC, Iamgoofball commented on code/__DEFINES/combat.dm
> +#define BROFIST "brofist"
2008 is calling

2017-08-26 13:14 UTC, Qustinnus commented on code/__DEFINES/combat.dm
> +#define BROFIST "brofist"
goof go back to ur election :^)

2017-08-26 13:15 UTC, Qustinnus commented
pls dont make it open a menu, make it toggle between the options each time you click.

2017-08-27 17:13 UTC, Super3222 commented on code/modules/clothing/clothing.dm
> +	var/can_be_crushed = FALSE
It's meant to be used for glasses.

2017-08-27 19:09 UTC, Time-Green commented
What floyd said, I really don't want to open up a menu mid-combat
Otherwise I really like this 👍

2017-08-27 19:18 UTC, Cruix approved these changes

2017-08-27 19:36 UTC, Chuggachar commented
Don't like the lizard damage change or kicking bots away but the rest is good, especially the increased kick damage depending on your footwear.

2017-08-27 19:37 UTC, Super3222 commented
I could make right clicking the HUD toggle between the options.

2017-08-28 15:43 UTC, matskuman5 commented
:+1: 

I really like the idea of right clicking to change intent

2017-08-28 18:13 UTC, Super3222 commented
I’ll give you guys the benefit of the doubt, and make it so left clicking (normal click) shifts it to the next special intent and right clicking it opens the menu.

2017-08-29 03:53 UTC, ShadowDeath6 commented
I'd prefer the MMB to open the menu if that's possible over right click

2017-08-29 10:12 UTC, Super3222 commented
It is, I’ll do that.

2017-09-07 15:53 UTC, Cruix requested changes

2017-09-07 15:53 UTC, Cruix commented on code/modules/mob/living/carbon/carbon.dm
> +			M.visible_message("<span class='notice'>[M] starts handing [M.get_active_hand()] to [src].</span>",\
first make sure that M.get_active_hand() is not null so you cannot give nothing to people

2017-09-07 15:53 UTC, Cruix commented on code/modules/mob/living/carbon/carbon.dm
> +		var/mob/living/carbon/target = locate(href_list["target"]) // he's trying to do something too you
Make sure target is not null and that no one is incapacitated

2017-09-07 15:53 UTC, Cruix commented on code/modules/mob/living/carbon/carbon.dm
> +						var/obj/O = locate(href_list["obj"])
Make sure O is not null to avoid runtimes

2017-09-09 20:39 UTC, Super3222 commented
travis broke

2017-09-11 16:10 UTC, Qustinnus commented
dont use MMB, I know some people don't have MMB.

2017-09-12 22:35 UTC, Super3222 commented
I can make an alternative hud that switches your special intent to the next one in order.

2017-09-13 04:03 UTC, Cruix approved these changes

2017-09-13 11:53 UTC, Jc1469 commented
Really don't like special intents making stuff not able to be picked up with left click.
Still don't like being able to keep beepsky.

2017-09-13 13:51 UTC, Jc1469 commented
Kicking things like banana peels does slip you, but only after the banana stops travelling... which is.. weird to say the least.

2017-09-13 14:57 UTC, Ratvar commented
why hugs now show hearts
why you did that
you monster

2017-09-13 16:39 UTC, monster860 commented
Grab could include strip, remove headset, pickpocket, and take shit from hands. Would mainly be a shortcut for clockdrag.

2017-09-13 18:42 UTC, Jc1469 commented
changing special intent and then changing normal intent after can make you get stuck on an intent if you change to disarm or grab.  In my case, I got stuck with my grab biting, so no grabbing for me.

2017-09-15 13:23 UTC, matskuman5 commented
When someone offers me a handshake and I accept it says

"You shake hands with [my characters name]"

2017-09-17 22:16 UTC, Super3222 commented
Mini SI Buttons:

![](https://images-ext-2.discordapp.net/external/fg8BBlLxAPZpExX-tS4i_q89cWgx4cOLXTJzun_rLis/https/image.prntscr.com/image/0dt-04DxSXCtAVLnplUeqg.png)
![](https://images-ext-1.discordapp.net/external/1uhbzgRtyE2AT2KblnmOnL-W-9vh25yEhqS8T_npLfA/https/image.prntscr.com/image/e5I60rVJQ3_MPUXZYncqaw.png)

2017-09-18 17:15 UTC, Qustinnus commented
pls no keep 1 button

2017-09-19 21:44 UTC, Super3222 commented
@Qustinnus To address controversy I'll add another hud that can collapse or expand the mini buttons.

2018-01-24 13:30 UTC, grubstank commented
I really dislike how much UI complexity this adds - new players already have a hard enough time figuring the intent system out. 
I feel like it's better to have the menu/minibuttons/cycle occur/appear on a hotkey separate from the intents. That way it's a separate, more modular feature that's available but not crammed into the already complicated UI.

2018-05-20 08:57 UTC, closed without merging