Adds holographic item projector
yogstation13/yogstation-2017- pull request #2612
Opened 2017-09-20 16:47 UTC by 1fbff5f83b23d39d38b1dfcb4cac8d9b

Adds the holographic item projector: A traitor device which allows you to scan any item then create a holographic clone of it. The clone disappears when interacted with in any way. Here is an example:

![image](https://user-images.githubusercontent.com/16842348/30656281-d952e2e0-9e33-11e7-9439-8d096e0c8980.png)
I've stolen several important things from that table, yet at first glance it looks like nothing is missing. Feedback would be appreciated!

2017-09-20 16:49 UTC, Amelia0010 commented
[6:49 PM] 🍆💦🍑: offsets should be doable
[6:49 PM] 🍆💦🍑: comment in the pr so I don't forget

2017-09-20 16:49 UTC, Ratvar commented
allow it to make fake gibs, vomit, blood splats? Fake uranium floortiles? Fake machinery?

2017-09-20 16:51 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
You can have 5 decoys at once, but I'm considering making it upgradeable with better capacitors, so you can have stupid amounts holographs if you work a bit. The TC cost will be <=5.

2017-09-20 17:23 UTC, Partheo commented
Can you make holograms of holograms? What happens if you hologram fake objects, like the holodeck or chameleon fakes?

2017-09-20 18:02 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
If you attempt to scan a hologram it will break, you can scan fake items and they will work normally (disappear on touch)

2017-09-20 19:46 UTC, Time-Green commented
Like the item, but I'm not spending 3-4 tc for something I'll only need once. 
Perhaps make it 1 tc and able to imitate one object

2017-09-20 19:54 UTC, Ratvar commented
=>not spending my TC for something i only need once
=>sleepypen

2017-09-20 21:38 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
Additions! You can now upgrade the projector with better capacitor and microlaser. Installing better parts will allow you to:
- Project more things at once, up to 32
- Scan more things (enough upgrading will allow you to create fake mobs) 
- Scan and project from further away! Plant that bomb inside the brig while hanging outside and watch the panic!

2017-09-21 16:27 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
cannot reproduce compilation errors

2017-09-22 03:26 UTC, Cruix commented
You did not commit your changes to yogstation.dme, so the file that the holoprojector is in is not included in the build.

2017-09-22 04:13 UTC, Cruix requested changes
Leave a comment

2017-09-22 04:13 UTC, Cruix commented on code/game/objects/items/devices/holoprojector.dm
> +	var/atom/current_item = null
Make this a mutable_appearance instead of an atom

2017-09-22 04:13 UTC, Cruix commented on code/game/objects/items/devices/holoprojector.dm
> +	if(istype(target,/turf/open))
Add a target in view(range, user) check to this. It really should not be necessary, but for some reason I am able to spawn holograms through walls. Make sure the error message is not shown if the check fails.

2017-09-22 04:13 UTC, Cruix commented on code/game/objects/items/devices/holoprojector.dm
> +				desc += " <span class='italics'>It seems to be shimmering a little...</span>"
Make it always have the description, otherwise people will just remove and recreate the item until it does not.

2017-09-22 04:13 UTC, Cruix commented on code/game/objects/items/devices/holoprojector.dm
> +/obj/item/device/holoprojector/proc/create_holograph(mob/user, turf/open/floor/target)
change turf/open/floor to turf/open, because that is what the only caller of this proc sends.

2017-09-22 04:13 UTC, Cruix commented on code/game/objects/items/devices/holoprojector.dm
> +/obj/effect/dummy/holograph/New(loc, parent)
parent should be of the proper type for clarity.

2017-09-22 04:13 UTC, Cruix commented on code/game/objects/items/devices/holoprojector.dm
> +
All holograms should be destroyed in the device's Destroy() proc.

2017-09-22 04:13 UTC, Cruix commented on code/game/objects/items/devices/holoprojector.dm
> +	desc = "A device which has the ability to scan objects and create stationary holographs of them."
Change every instance of "holograph" to "hologram" or "holographic". A holograph is a specific type of written document and has nothing to do with holographic objects.

2017-09-22 10:43 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/game/objects/items/devices/holoprojector.dm
> +	desc = "A device which has the ability to scan objects and create stationary holographs of them."
english is dumb

2017-09-22 11:12 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
I think that was all of them

2017-09-22 16:04 UTC, Cruix approved these changes

2017-09-22 16:04 UTC, Cruix commented
Looks good.

2017-12-27 20:22 UTC, merged