Mentors vol. 2
yogstation13/yogstation-2017- pull request #2635
Opened 2017-09-30 16:58 UTC by 1fbff5f83b23d39d38b1dfcb4cac8d9b

Pretty much a reboot of #1854. From the PR:

From what I understand Mentors are a lower-class admin that are coded entirely differently.
Mentors are appointed by the council. They work off of a notepad file.
Mentors also have mentorSAY, for chatting like little girls, and SHOW mentor memos (those are set by admins).
Mentors also have the ability to follow players. This'll set their entire perspective on that player.

Players will have the ability to use mentorhelps in order to communicate with mentors. Mentors will also have the ability to PM players, and communicate back.

And so they get the recognition they deserve their OOC color is also different. I might as well throw in an OOC tag.

Thanks goes out to the hippiestation team.

Ports:

HippieStation/HippieStation13#22
HippieStation/HippieStation13#73
HippieStation/HippieStation13#170
Changelog

:cl:
rscadd: Ported Mentors from HippieStation.
/:cl:

2017-09-30 21:40 UTC, ShadowDeath6 commented
put a name in the changelog so people don't see "1fbff5f83b23d39d38b1dfcb4cac8d9b" in game, please

2017-09-30 22:40 UTC, drderp3635 commented
1fbff5f83b23d39d38b1dfcb4cac8d9b is a beautiful name, don't let them bully you

2017-10-01 03:40 UTC, Super3222 commented
You should just sign the changelog under your username. RN it looks like Hippiestation is doing the porting which is confusing. Either way nice job.

2017-10-01 09:15 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
Doesn't feel right to attribute this to myself when I essentially copy-pasted your work to be honest

2017-10-02 12:20 UTC, Alexandria404 commented
Where are the logs for their actions and what is logged, and can it be in it´s own file?

2017-10-02 15:02 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
It goes in the server log. The following are logged: following, unfollowing, people mentorhelping and replies to those, and mentorsay. The logs could be stored in a separate file if need be (but pls dont ask for that i dunno how to)

2017-10-02 19:08 UTC, nichlas0010 commented
pleeeeeeaaaaasee put it in the admin log, rather than the regular log

2017-10-03 20:59 UTC, Xantam-13 commented
Forgive me if I'm being silly, but, I'm assuming this will now include 2 ticket systems, one for ahelps and one for mentor helps? Both will be separate and not buggy together? Or will ahelps use tickets and mentor helps use the old style PM'ing without tickets?

2017-10-03 21:24 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
Mentorhelp will work via oldschool PMs

2017-10-18 23:59 UTC, ghost requested changes

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/client/verbs/ooc.dm
> +				C << "<font color='[ooc_color]'><span class='ooc'><span class='prefix'>OOC:</span> <EM>[keyname]:</EM> <span class='message'>[msg]</span></span></font>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/client/verbs/who.dm
>  	src << msg
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/follow.dm
> +	admins << "<span class='mentor'><span class='prefix'>MENTOR:</span> <EM>[key_name(usr)]</EM> is now following <EM>[key_name(M)]</span>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/follow.dm
> +	usr << "<span class='info'>You are no longer following [following].</span>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/follow.dm
> +	usr << "<span class='info'>You are no longer following [following].</span>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentor_memo.dm
> +		src << "<span class='danger'>Failed to establish database connection.</span>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentor_memo.dm
> +		src << "<span class='danger'>Failed to establish database connection.</span>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentor_memo.dm
> +		src << "<span class='danger'>Failed to establish database connection.</span>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentor_memo.dm
> +				src << "You already have set a memo."
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentor_memo.dm
> +				src << "No memos found in database."
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentor_memo.dm
> +				src << "No memos found in database."
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentor_memo.dm
> +			src << output
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentor_memo.dm
> +				src << "No memos found in database."
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentorhelp.dm
> +		src << "<font color='red'>You are unable to use mentorhelp (muted).</font>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentorhelp.dm
> +		A << mentor_msg
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentorhelp.dm
> +		X << mentor_msg
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentorpm.dm
> +		src << "<font color='red'>Error: Mentor-PM-Panel: Only Mentors may use this command.</font>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentorpm.dm
> +			src << "<font color='green'>Mentor PM to-<b>[key_name_mentor(C, C, 1, 0, show_char)]</b>: [msg]</font>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentorpm.dm
> +			src << "<font color='green'>Mentor PM to-<b>[key_name_mentor(C, C, 1, 0, 0)]</b>: [msg]</font>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentorpm.dm
> +			src << "<font color='green'>Mentor PM to-<b>[key_name_mentor(C, C, 1, 0, 0)]</b>: [msg]</font>"
to_chat

2017-10-18 23:59 UTC, MoreRobustThanYou commented on code/modules/hippie/mentor/verbs/mentorsay.dm
> +		admins << msg
to_chat x4 here

2017-12-11 21:42 UTC, morrowwolf commented
OK Council has agreed to this as soon as it's observer only.  I was thinking dementor them when they get a job and then not allowing rementor until they are observer again.  Someone else probably has a better solution.

2017-12-12 05:15 UTC, Koffheatalt commented
isn't it better to use 
if(!isliving(user))

2017-12-12 05:17 UTC, morrowwolf commented
Yeah probably best to just put that literally every place that mentors have abilities.

2017-12-12 11:01 UTC, Koffheatalt commented
fair point it would create a lot of lagg

2017-12-12 14:47 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
what would create lag

2017-12-12 15:12 UTC, Koffheatalt commented
constantly checking if(!isliving(target)) for each mentor

2017-12-12 17:13 UTC, nichlas0010 commented
You'd only need to check it everytime someone mentorhelps or uses mentorsay or something similar. And doing one if statement really wouldn't lag that much.

2017-12-12 17:45 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
ayy lmao doesnt work

2017-12-12 18:48 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
this should work but i cant test rihgt now

2017-12-21 16:38 UTC, Koffheatalt commented
did you test it yet

2018-02-09 18:31 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
how did you get into my git mainframe and when is this getting testmerged

2018-05-20 08:57 UTC, closed without merging