Long term storage
yogstation13/yogstation-2017- pull request #2644
Opened 2017-10-04 17:04 UTC by 1fbff5f83b23d39d38b1dfcb4cac8d9b

Didn't roll antag? Feeling like a dick for wasting a job slot while looking for murderbone ghost roles? Fear no more!
Introducing the cryptosleep casket! Simply remove any important and unique (traitor objective) items and place them in a secure spot, then stand in front of the machine and activate it! Accidental death and dismemberment insurance sold separately.
The casket will delete your character and free up a job slot for other players to sign up as.
:cl:
rscadd: Considering suicide or going braindead? Go to dorms and enter long term storage instead. Your job slot will become available to latejoin players.
/:cl:

2017-10-04 18:08 UTC, Jc1469 requested changes
To add, that thing I said about using high_risk instead of a list of blacklisted things.

2017-10-04 18:08 UTC, Jc1469 commented on code/game/objects/structures/longtermstorage.dm
> +	if(j) j.current_positions--
what is this unnatural coding practice

2017-10-04 18:08 UTC, Jc1469 commented on code/game/objects/structures/longtermstorage.dm
> +	if(j) msg += ", [target.mind.assigned_role], "
every fibre of my being having done byond code hates this.  the other parts don't mind, the byond part no like

2017-10-04 18:08 UTC, Jc1469 commented on code/game/objects/structures/longtermstorage.dm
> +	if(alert(user, "Are you sure you want to enter storage? This action cannot be undone!", , "Yes", "No") == "No") return
newline for return :badminton:

2017-10-04 18:08 UTC, Jc1469 commented on code/game/objects/structures/longtermstorage.dm
> +		if(FI) found += FI
wake me up inside

2017-10-04 18:11 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/game/objects/structures/longtermstorage.dm
> +		if(FI) found += FI
remnant of the way i checked items before

2017-10-04 18:11 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/game/objects/structures/longtermstorage.dm
> +	if(alert(user, "Are you sure you want to enter storage? This action cannot be undone!", , "Yes", "No") == "No") return
no

2017-10-04 18:11 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/game/objects/structures/longtermstorage.dm
> +	if(j) j.current_positions--
my dad beats me every 50 lines of code

2017-10-04 18:13 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/game/objects/structures/longtermstorage.dm
> +	if(j) msg += ", [target.mind.assigned_role], "
sigh fine

2017-10-04 18:27 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
I don't  want to use high risk items cause some of these are not high risk yet they shouldn't be deleted, like spaecsuits

2017-10-04 18:28 UTC, Jc1469 commented
fair enough.

2017-10-04 19:13 UTC, 05rhardy commented
Good!

2017-10-04 19:30 UTC, Jc1469 commented
I await the inevitable grief where people dismantle R&D or something then go and delete themselves

2017-10-04 19:31 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
it's just as easy to space R&D or something

2017-10-04 19:42 UTC, Ratvar commented
Can you delete posibrains, soulshards, MMI's and such shit this way? You cannot just kill posi and it still can radio from shitty places, and those interactions are commonly bugged

2017-10-04 19:44 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
it should delete everything you have in your inventory when you enter it, i'll need to test that

2017-10-05 00:50 UTC, KrabSpider commented
Will there also be a console that dispenses

2017-10-05 07:49 UTC, Kmc2000 commented
Perhaps it could disposal the items to cargo instead? thinking about assustants grabbing all the cuffs and guns from the armoury and then deleting themselves. Thisll also need rules to acompany it

2017-10-05 11:55 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
I don't think that is necessary. If an assistant can grab guns and delete themselves they might as well space them or throw them into the grinder and continue griefing.

2017-11-29 16:08 UTC, KrabSpider commented
Has it been tested yet?

2017-12-01 23:25 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
@AshCorr No Merge Conflict :^)

2017-12-03 09:10 UTC, AshCorr commented
You've fucked up the map now @1fbff5f83b23d39d38b1dfcb4cac8d9b , make sure you use the mapmerge tool.

2018-05-20 08:57 UTC, closed without merging