John's Incredibly Spiteful Admin Balldance
yogstation13/yogstation-2017- pull request #2666
Opened 2017-10-09 19:45 UTC by Jc1469

:cl:  
bugfix: AO now can't view a lot of shit.
/:cl:

2017-10-09 19:46 UTC, Slinky5890 commented
One day AO will become just an OOC tag

2017-10-09 19:51 UTC, Partheo commented
AOsquad dream is dead.

2017-10-09 20:36 UTC, Alexandria404 commented
The AO hordes shall grow, nothing can stop them now.

2017-10-10 16:56 UTC, Kmc2000 commented
-1 your last balldance removed SeniorMin.

2017-10-11 18:41 UTC, Slinky5890 commented
I think matsku was the one that removed seniormin

2017-10-18 10:39 UTC, ghost requested changes

2017-10-18 10:39 UTC, MoreRobustThanYou commented on code/modules/admin/admin.dm
> +		admins << msg
to_chat

2017-10-18 10:39 UTC, MoreRobustThanYou commented on code/modules/admin/admin.dm
> +		validmins << msg
to_chat

2017-11-28 20:44 UTC, AshCorr commented on code/modules/admin/admin.dm
> +		msg = "<span class=\"admin\"><span class=\"prefix\">ADMIN LOG:</span> <span class=\"message\">[msg]</span> - MESSAGE NOT SENT TO PEOPLE WITHOUT +BASIC</span>"
You dont need to yell`- MESSAGE NOT SENT TO PEOPLE WITHOUT +BASIC` to the world

2017-12-03 21:06 UTC, merged