Fixes small text issue
yogstation13/yogstation-2017- pull request #2738
Opened 2017-10-27 20:14 UTC by 1fbff5f83b23d39d38b1dfcb4cac8d9b

![image](https://user-images.githubusercontent.com/16842348/32123340-151c3dd8-bb64-11e7-9427-abeea063ba46.png)

2017-10-27 20:15 UTC, nichlas0010 commented
SPEED BLOODY MERGE WHEEEEEEEEEEEE

2017-10-27 20:20 UTC, Partheo commented
What the fuck

Someone wake me up

This isn't real

2017-10-27 20:47 UTC, ActualRory commented
Is...

Is this real life?

2017-10-27 20:54 UTC, Ratvar commented
russian servers fixed it three years ago

2017-10-27 21:12 UTC, AsV9 commented
The fix is such a hack though but whatever I do not care.

2017-10-28 00:12 UTC, Partheo commented
![31676544-f8d06536-b335-11e7-9982-c1c135634ae1](https://user-images.githubusercontent.com/10659549/32129260-31cf51ba-bb53-11e7-8572-164c6d04db7e.gif)

2017-10-28 05:04 UTC, ShadowDeath6 commented
call the proc fix_apostrophes to retain some semblance of professionalism within admin code

2017-10-30 00:16 UTC, Slinky5890 commented
holy


shit

2017-11-18 18:50 UTC, AshCorr requested changes

2017-11-18 18:50 UTC, AshCorr commented on code/modules/admin/tickets/admin_ticket.dm
> +/datum/ticket_log/proc/fix_apostrophes()
You might want to move this code to a proc that can be used everywhere.

If you put the code in https://github.com/yogstation13/yogstation/blob/master/code/__HELPERS/text.dm and make it take a string as a parameter you can then return the santizied string.

2017-11-22 21:20 UTC, AshCorr approved these changes

2017-11-25 17:53 UTC, merged