Re-ports tg's port of vg's temperature gun
yogstation13/yogstation-2017- pull request #2747
Opened 2017-10-31 19:30 UTC by ToGWtF

### Intent of your Pull Request

Before we go on, go ahead and read this fancy infographic

https://cloud.githubusercontent.com/assets/7573912/4605468/84cf561c-51e3-11e4-9912-fea92231110e.png

With this, we can nerf the xenobiology consoles (or remove entirely if you want to be that evil) without people crying too much.

#### Changelog

:cl:  

tweak: Massive tweak of the temperature gun. Now its actually useful / lethal!

/:cl:

2017-10-31 20:15 UTC, ShadowDeath6 commented
this doesn't make managing slimes any easier, hosing them down with the extinguisher was literally the easiest part. The annoying part is wading through 3+ slimes to get the one you want

2017-10-31 20:20 UTC, ToGWtF commented
It will only make managing slimes easier if we didn't have xenobio camera consoles. But they are fun for other science related things

2017-10-31 21:04 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/modules/projectiles/guns/energy/temperature.dm
> +		user << "<span class='caution'>You double the gun's temperature cap ! Targets hit by searing beams will burst into flames !</span>"
No spaces before punctuation

2017-10-31 21:04 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/modules/projectiles/guns/energy/temperature.dm
> +		desc = "A gun that changes the body temperature of its targets. Its temperature cap has been hacked"
period

2017-10-31 21:04 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/modules/projectiles/guns/energy/temperature.dm
> +	SSobj.processing |= src
why not START_PROCESSING(SSobj, src) instead?

2017-10-31 21:04 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/modules/projectiles/guns/energy/temperature.dm
> +	SSobj.processing -= src
STOP_PROCESSING

2017-10-31 21:39 UTC, ToGWtF commented on code/modules/projectiles/guns/energy/temperature.dm
> +		desc = "A gun that changes the body temperature of its targets. Its temperature cap has been hacked"
I'm more concerned with it being visible emagged

2017-10-31 21:53 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/modules/projectiles/guns/energy/temperature.dm
> +		desc = "A gun that changes the body temperature of its targets. Its temperature cap has been hacked"
I agree, you should remove it

2017-10-31 22:24 UTC, Super3222 commented
trick or treat!!!!1111!!

2017-11-01 08:15 UTC, killerx09 commented
I have an idea.

Why don't we just remove the Xenobio coldroom?

So this will become a thing, and now scientists can choose between fire extinguishing the slimes, shooting them with those fancy new guns or build their own cold room with NO and Freezer boards.

2017-11-01 15:29 UTC, Partheo commented
I'm a fan. Did you make the graphic?

2017-11-01 16:12 UTC, AdamElTablawy commented
No.

2017-11-01 23:50 UTC, Ratvar commented
Or they can RCD hole to spess in xenobio and put glass around to make coldroom that works 100% of time

2017-11-25 15:00 UTC, AshCorr requested changes

2017-11-25 15:00 UTC, AshCorr commented on code/modules/projectiles/guns/energy/temperature.dm
> +			var /mob/living/carbon/M = loc
Thats an interesting space there.

2017-11-25 15:00 UTC, AshCorr commented on code/modules/projectiles/guns/energy/temperature.dm
> +			temperature = target_temperature
Make sure you update the temperature and e_cost of the chambered round after temperature is changed. During testing the first 1-2 shots after changing the temperature would still be at the same values as the initial temperature.

2017-11-25 15:00 UTC, AshCorr commented on code/modules/projectiles/guns/energy/temperature.dm
> +	switch(temperature)
These switches should be done after temperature changes are processed.

2018-05-20 08:57 UTC, closed without merging