Fixes a couple bugs pointed out by Kojuh
yogstation13/yogstation-2017- pull request #2785
Opened 2017-11-16 19:29 UTC by 1fbff5f83b23d39d38b1dfcb4cac8d9b

2017-11-17 05:58 UTC, ShadowDeath6 commented on code/modules/surgery/prosthetic_replacement.dm
> +		to_chat(user, "<span class='warning'>[tool] isn't the right thing to replace [target]'s [parse_zone(target_zone)] with.</span>")
can you just say "part" instead of "thing"

2017-11-18 20:03 UTC, AshCorr requested changes

2017-11-18 20:03 UTC, AshCorr commented on code/modules/surgery/prosthetic_replacement.dm
> +		to_chat(user, "<span class='warning'>[tool] isn't the right thing to replace [target]'s [parse_zone(target_zone)] with.</span>")
`to_chat(user, "<span class='warning'>[tool] cant be used to replace [target]'s [parse_zone(target_zone)].</span>")`

2017-11-18 21:05 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/modules/surgery/prosthetic_replacement.dm
> +		to_chat(user, "<span class='warning'>[tool] isn't the right thing to replace [target]'s [parse_zone(target_zone)] with.</span>")
`to_chat(user, "<span class='warning'>Well hello there Mr player. Unfortunately, it has come to my attention that you are attempting to use [tool] to replace [parse_zone(target_zone)] of the poor [target]. Don't you think it's quite a strange idea? You'd be able to use any body part or any prosthetic to replace people's limbs. This would allow players to attach 10 arms to each other, so they can wield eswords forever and become absolutely unkillable. Doesn't sound nearly as fun, does it? Now, go ahead and grab \a [parse_zone(target_zone)] to replace [target]'s missing limb properly, ya silly goose.</span>")`

2017-11-19 00:10 UTC, AshCorr approved these changes

2017-11-19 00:10 UTC, merged