Survival is rewarded with antag weight increase
yogstation13/yogstation-2017- pull request #2857
Opened 2017-12-17 15:15 UTC by AlpacaGoesCrazy

This PR is to force players to value their life and to actually play in a round and not go braindead.
Antag weight (probability to become antag in next round) increases now at round end. Only alive, not braindead people who didnt roll antag are eligible for antag weight increase.

:cl:    
tweak: Increased probability to become an antagonist is now awarded for non-antag players who were active during the round and were able to survive until round end.
/:cl:

2017-12-17 15:17 UTC, Alexandria404 commented
What´s the amount of the increase. What if I just leave it open and afk in a locker?

2017-12-17 15:20 UTC, matskuman5 commented
Say hello to more rampant powergame and murderbone

How does this work? Does it stack? Does it last forever, or decay over time or what?

2017-12-17 15:23 UTC, AlpacaGoesCrazy commented
The amount is not changed. It used to be that all people who were eligible for antag but didnt have it got that increase. Now only alive and not braindead people will get it, others will not.

As for how much is that increase:
`weight = min(400, weight * 1.5)`
I didnt touch this part. it increases but has a maximum limit at 400.

2017-12-17 15:28 UTC, Jc1469 commented
I don't think punishing antag targets for being antag targets is a particularly nice thing to do.

2017-12-17 15:33 UTC, AlpacaGoesCrazy commented
>  What if I just leave it open and afk in a locker?
@Alexandria404 yes you can do that with this PR, but currently its even more simple: press ready and you get antag weight increase if you didnt get antag.

@Jc1469 on other hand not punishing players who dont value their lifes and go validhunting, jumping out of airlocks or simply going braindead is even worse thing to do

2017-12-17 15:48 UTC, Alexandria404 commented
I don´t care which way, but we need to somehow not reward afkers

2017-12-17 16:53 UTC, Alexandria404 commented
possbile solutions:
alive+escaped
afk var

2017-12-18 02:16 UTC, drderp3635 commented
Alive + escape would just fuck things up if someone succeeds on hijack

2017-12-18 05:50 UTC, AlpacaGoesCrazy commented
> Alive + escape would just fuck things up if someone succeeds on hijack

@drderp3635 Antags dont get weight increase anyway, so if noone gets weight increase nothing will change and no things will be fucked up.

2017-12-18 07:42 UTC, ShadowDeath6 commented
:-1:

a very big part of this game is learning from your mistakes and dying. Someone being unlucky or new to the game being gimped out of antag chances is extremely poor conduct. 

if someone is going braindead at roundstart as an important job then it's up to admins to deal with them, not coders.

2017-12-18 17:44 UTC, Super3222 commented
jexp

2017-12-18 21:13 UTC, Jc1469 commented
400 rounds

2017-12-19 12:26 UTC, AdamElTablawy commented
it's a fucking video game and sometimes people don't want to play

this is going to encourage powergame for people who want to be antag more than anything else, and god help EVERYONE if it's like, a fucking nuke round/blob round/clock round/cult round because everyone is going to die in those cases

so in THOSE cases it's a catch-22 because if you don't actually try to stop the cult or whatever and you die doing it you get nothing, and if you don't stop the cult you get nothing anyway

you're going to end up with the same few people powergaming it if they want antag because rather than being braindead the WHOLE round they'll be braindead the majority of it then board the shuttle when it arrives and not be counted as braindead

and they won't actively participate in the round at all, because they won't want to die to the antagonist at risk of losing their antag weight, so it'll end up with a bunch of people quietly jerking off in their departments with no security because nobody wants to be security at risk of being killed by the traitor and losing their antag weight gain for the round, completely unwilling to interact or actually try to stop the antagonist

you've gained no form of activity here, because it'll go one of two ways:

people powergame to the extreme to not die and you accomplish the opposite of what you intended and people circumvent the braindead thing by only not being braindead when whatever amount gets tallied

or 2

people hide away and do nothing when the antagonist shows up which leads to boring rounds and easy wins, and nobody plays security at risk of losing their antag weight because they run the risk of getting killed pretty much every fucking round. i forsee a majority of the crew fleeing to mining pretty much every wiz round rather than actively participate in it at risk of losing their sweet, sweet, antag rolls, because that's all they care about



on top of THAT, you've pretty much guaranteed that nobody but the most robust people will get antagonist, which goes against why antag weight was implemented in the first place: so that everyone had a fair shot at actually getting antagonist at some point, so that you wouldn't have month long dry streaks and the other guy got it constantly. in this case, only people who survive get it, which either means the ones who hide and don't participate but are technically still there, ie mason miami, or the ones who are too robust to die.

shit PR.

2017-12-19 21:05 UTC, Ratvar commented
If you are trying to punish antagrollers-how you will punish people who go and get borged roundstart if they didn't roll antag in attempt to roll malf AI/clockcult/emagged borg?

2017-12-27 19:28 UTC, AsV9 commented
I'm a bit skeptical. I believe leaving the system unchanged is probably wise for now. I'd rather have the admins enforce powergaming rules instead of trying to apply a technical solution.

2018-01-01 13:46 UTC, AlpacaGoesCrazy commented
> I'd rather have the admins enforce powergaming rules instead of trying to apply a technical solution.

This is just VERY wrong thinking here.

I suggest i change it so antag weight will be added to everyone who is non-braindead at round end. So you dont have to be alive but you cant just close game and wait for next round ping on discord to try rolling antag again. (Sorry i didnt reply earlier, was really busy)

2018-01-01 16:27 UTC, AsV9 commented
I don't think making admins properly enforce powergaming rules is quote 'very wrong' here, but I'd be alright with a solution that just encourages people to stay around for another round.

Then again, your argument for preventing powergame or encouraging people to value their lives doesn't work in this case.

2018-01-01 19:55 UTC, AlpacaGoesCrazy commented
Enforcing rules thru game mechanics is easier for everyone: less works for admins and lesser chance that someone manages to break that mechanic. Thinking that a few additional rules will do the trick is just wrong. Rules are not always enforced, they are hard to memorize for newer players (at this point there are too many), they are not always clear and finally there always some rulebreakers who dont get caught.
On other hand its hard to trick a game mechanic and if someone manages to do so you can just adjust it  so it wont be possible to take advantage on said mechanic in the future.

Anyway, @AsV9  what do you think about my last solution:

> i change it so antag weight will be added to everyone who is non-braindead at round end.

Will this do the trick? It surely doesnt punish those who died but encourages people to actually play the game (or not close the client and at least pay /some/ attention to game process)

2018-01-02 11:28 UTC, AsV9 commented
Sure, I'd be alright with trying that.

2018-01-02 14:37 UTC, AsV9 requested changes

2018-01-02 14:37 UTC, AsV9 commented on code/game/gamemodes/game_mode.dm
> +					to_chat(candidate.current, "<font color='green'><b>For playing thru the whole round your chance to become an antagonist increased!</b></FONT>")
Grammar police.

2018-01-02 14:41 UTC, Alexandria404 commented
Still issues with implementation, we are discussing a possible fix.

2018-01-02 15:06 UTC, AlpacaGoesCrazy commented on code/game/gamemodes/game_mode.dm
> +					to_chat(candidate.current, "<font color='green'><b>For playing thru the whole round your chance to become an antagonist increased!</b></FONT>")
I am bad at grammar, please suggest how it should be :(

2018-01-02 20:08 UTC, Partheo commented on code/game/gamemodes/game_mode.dm
> +					to_chat(candidate.current, "<font color='green'><b>For playing thru the whole round your chance to become an antagonist increased!</b></FONT>")
Honestly I feel like this should be hidden. I don't feel like it should display a message.

2018-01-02 21:22 UTC, AsV9 commented on code/game/gamemodes/game_mode.dm
> +					to_chat(candidate.current, "<font color='green'><b>For playing thru the whole round your chance to become an antagonist increased!</b></FONT>")
`thru` is too informal to use in this context, use `through` instead.

2018-01-05 19:56 UTC, AdamElTablawy commented
Enforcing rules through game mechanics is a cute idea that doesn’t work in practice. It’s shoddy, mostly nonfunctional, and leaves a lot of area for particular oddities or exceptions that an administrator would be able to discern. And that’s with a good system, not this shit.

You’ve also failed to address half my points.

2018-01-07 21:50 UTC, AsV9 approved these changes

2018-02-01 13:37 UTC, ThatLing commented
I'm gonna close this since it's been pretty dead and you haven't implemented the requested changes yet. Feel free to reopen it or make a new PR if you do.

2018-02-01 13:37 UTC, closed without merging