Fixes paintballs!
yogstation13/yogstation-2017- pull request #2898
Opened 2018-01-02 16:01 UTC by Kmc2000

Refer to issue #2890

### Intent of your Pull Request

This PR fixes paintballs! I got rid of the shitty overlay thing I did and they now just make your clothes progressively more bloody with each hit. The casings now POP when you walk on them, covering the tile below in paint, with a small chance to cover EVERYTHING around it in paint (1/100), it also has a 1/10 chance to colour you in when hit, which won't be easy to remove. 

You have been warned!

My copy of yogstation lagged pretty badly so I didn't get footage :^(

#### Changelog

:cl:Kmc2000
tweak: Paintballs are now less shitty overall
/:cl:

2018-01-02 17:18 UTC, Amelia0010 requested changes

2018-01-02 17:18 UTC, nichlas0010 commented on code/modules/projectiles/guns/projectile/paintball.dm
> +/obj/item/ammo_casing/paintball/Crossed(atom/movable/mover)
I get a strange flashback to tanks running over ghosts :-/

2018-01-02 17:18 UTC, nichlas0010 commented on code/modules/projectiles/guns/projectile/paintball.dm
> +	if(spreadem < 2 || spreadem == 1)
if it's between 1 and 100, and it's under 2, then it's 1. Why the first spreadem is there, I have no clue.

2018-01-02 17:18 UTC, nichlas0010 commented on code/modules/projectiles/guns/projectile/paintball.dm
> +	var/spreadem = rand(1,100)
Why not just do 
>if(prob(1))

 instead of the spreadem thing?

2018-01-02 17:18 UTC, nichlas0010 commented on code/modules/projectiles/guns/projectile/paintball.dm
> +		for(var/atom/movable/T in orange(3, src))
Including ghosts?

2018-01-02 17:19 UTC, Kmc2000 commented on code/modules/projectiles/guns/projectile/paintball.dm
> +/obj/item/ammo_casing/paintball/Crossed(atom/movable/mover)
OH HI

2018-01-02 17:58 UTC, Amelia0010 approved these changes

2018-01-02 20:04 UTC, Partheo commented
Your copy of Yogstation was lagging? That does not bode well.

2018-01-02 22:11 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on code/modules/projectiles/guns/projectile/paintball.dm
> +			src.visible_message("[src] explodes in a shower of paint! covering everything around it in sticky horridness.")
maybe change this to "[src] explodes in a shower of paint, covering..."

2018-01-03 00:01 UTC, Kmc2000 commented
>partheo

It's to do with me using weird versions of BYOND and having maps that I'm currently working on in the main folder.

2018-01-15 18:03 UTC, merged