Change the PR template
yogstation13/yogstation-2017- pull request #2963
Opened 2018-01-20 17:30 UTC by ThatLing

Adds more information to the PR template. Open for any suggestions/feedback.

2018-01-20 17:53 UTC, AsV9 requested changes

2018-01-20 17:53 UTC, AsV9 commented on .github/PULL_REQUEST_TEMPLATE.md
> +Mention if you tested your changes. Make sure they atleast compile.
Replace: `Mention if you tested your changes. Make sure they atleast compile.`

With: `Mention if you tested your changes.`

Because travis checks if something compiles, and the coders shouldn't be *that* lazy.

2018-01-20 18:01 UTC, ThatLing commented
The [admin] thing will work as soon as YogBot stops being mean.

2018-01-20 18:01 UTC, AsV9 approved these changes

2018-01-21 17:15 UTC, Amelia0010 approved these changes

2018-01-31 18:10 UTC, merged