Stunbatons faintly glow when turned on
yogstation13/yogstation-2017- pull request #2967
Opened 2018-01-21 15:09 UTC by retrosquid64

This PR makes stunbatons glow softly when turned on. Barely enough to see anything in the dark, but the wielder will be visible. Luminosity is 0.9 .
#### Changelog

:cl:  retrosquid64
tweak: Stunbatons now glow faintly when turned on
/:cl:

2018-01-21 15:13 UTC, Time-Green commented on code/game/objects/items/weapons/stunbaton.dm
> +	if(status == 1)
You can do if(status) without the == 1
if(status) just checks if it's true. That being literally anything but null, 0 and FALSE
If status actually goes further then 0 and 1, ignore me

2018-01-21 15:14 UTC, retrosquid64 commented on code/game/objects/items/weapons/stunbaton.dm
> +	if(status == 1)
I see, thanks.

2018-01-21 15:15 UTC, ThatLing commented on code/game/objects/items/weapons/stunbaton.dm
> +	if(status == 1)
It's can only be 0 or 1. See ![this](https://github.com/retrosquid64/yogstation/blob/e9d7167f9c312e2a4f2207a6c347f09427a6ae36/code/game/objects/items/weapons/stunbaton.dm#L88).

2018-01-21 15:16 UTC, retrosquid64 commented on code/game/objects/items/weapons/stunbaton.dm
> +	if(status == 1)
I could change it, but does it really matter for now?

2018-01-21 16:37 UTC, Time-Green commented on code/game/objects/items/weapons/stunbaton.dm
> +	if(status == 1)
It's technicly not wrong, but it's against standards and honestly it's really bothering me to the point I will make a seperate PR to fix it if you dont

2018-01-21 17:30 UTC, nichlas0010 commented
If you activate the stunbaton so it glows, then drop it on the ground, the light stays on the user, and the stunbaton lies in darkness

https://gyazo.com/0f5891083ccb577017d3bf10876ef89f

2018-01-21 17:32 UTC, retrosquid64 commented on code/game/objects/items/weapons/stunbaton.dm
> +	if(status == 1)
If it's against the standards I will happily edit this PR to accommodate them.

2018-01-21 17:32 UTC, retrosquid64 commented
On it.

2018-01-21 17:34 UTC, Time-Green commented
It may be because you made the user light up, and not the actual baton
Same with the turf, you're making the turf glow, not the user

2018-01-21 17:44 UTC, Amelia0010 requested changes

2018-01-21 17:44 UTC, nichlas0010 commented on code/game/objects/items/weapons/stunbaton.dm
> +			user.SetLuminosity(0.9)
Please us [AddLuminosity](https://github.com/yogstation13/yogstation/blob/6c3d36b0fc06c2a7a874d0d45fb84008695ac9c7/code/modules/lighting/lighting_system.dm#L218) instead.

If you use SetLuminosity, you run into this issue: https://gyazo.com/a9c7f8677478c572547a137941ef2f6f

2018-01-21 21:40 UTC, AdamElTablawy commented
Does veil turn off the stunbaton if a shadowling uses veil.

2018-01-22 02:52 UTC, Qustinnus commented on code/game/objects/items/weapons/stunbaton.dm
> +			user.SetLuminosity(0.9)
or instead maybe point out that he's changing the luminosity of the fucking character lmao

2018-01-23 17:01 UTC, retrosquid64 commented on code/game/objects/items/weapons/stunbaton.dm
> +			user.SetLuminosity(0.9)
I think the flashlight does this too, that's what I based it on.

2018-05-20 08:57 UTC, closed without merging