Adds a tip
yogstation13/yogstation-2017- pull request #3028
Opened 2018-01-30 12:59 UTC by nichlas0010

2018-01-30 13:03 UTC, simonset55 commented
I'm a retard and don't understand this code change, please provide a description

2018-01-30 13:34 UTC, simonset55 commented
Don't mock me for my defects REEEEEEEEE

2018-01-30 13:44 UTC, simonset55 commented on config/sillytips.txt
> +Meth can be ignited while inside people, causing it to blow up.
Could change it to pyrotechnic chems instead of meth, since any chemical can be heated inside of people

2018-01-30 13:46 UTC, nichlas0010 commented on config/sillytips.txt
> +Meth can be ignited while inside people, causing it to blow up.
🤔 config/sillytips.txt

>sillytips

2018-01-30 13:48 UTC, simonset55 commented on config/sillytips.txt
> +Meth can be ignited while inside people, causing it to blow up.
But it ain't really silly doe is it

2018-01-30 13:49 UTC, ThatLing approved these changes

2018-01-30 13:58 UTC, ThatLing commented on config/sillytips.txt
> +Meth can be ignited while inside people, causing it to blow up.
Move it to config/serioustips.txt

2018-01-30 17:46 UTC, Time-Green commented
I think we had a problem with tips before, since you’ll need to manually change them on the host

2018-01-30 17:48 UTC, nichlas0010 commented
it's the config folder, so yeah

2018-01-31 16:40 UTC, Time-Green commented
add:
You can't break the rules if there's no admins

2018-01-31 18:36 UTC, ThatLing requested changes

2018-01-31 18:36 UTC, ThatLing commented on config/sillytips.txt
> +You can't break the rules if there are no admins to enforce them.
Nuke this

2018-01-31 18:37 UTC, nichlas0010 commented on config/sillytips.txt
> +You can't break the rules if there are no admins to enforce them.
😕

2018-01-31 18:47 UTC, ThatLing approved these changes

2018-01-31 19:45 UTC, matskuman5 commented
Please no
retards will think that's real and grief

2018-02-19 10:35 UTC, nichlas0010 commented
![image](https://user-images.githubusercontent.com/20558591/36373629-f99c625e-1568-11e8-8af9-899640cc4993.png)

2018-05-20 08:57 UTC, closed without merging