Adds uplink preferences
yogstation13/yogstation-2017- pull request #3051
Opened 2018-02-02 16:04 UTC by nichlas0010

Ports: https://github.com/tgstation/tgstation/pull/23190/files

:cl: MrStonedOne
rscadd: Traitors can now choose where their uplink spawns, in their character settings. The options are limited to the PDA, Pen and Radio.
/:cl:

2018-02-02 16:20 UTC, ThatLing requested changes

2018-02-02 16:20 UTC, ThatLing commented on code/modules/paperwork/pen.dm
> +
Forgot something here

2018-02-02 16:58 UTC, ThatLing approved these changes

2018-02-02 19:46 UTC, Time-Green commented
You ruined my personal strat. Quickly removing my PDA before initializing for that sweet secret radio uplink

2018-02-03 20:47 UTC, Ratvar commented
add a pref to start with uplink implant with cut to tc, like you already can do ingame?

2018-02-03 21:44 UTC, Time-Green commented
@Ratvar https://github.com/yogstation13/yogstation/blob/e13de1f45bdb23bf3db773c6e10a9dfe6e58a567/strings/brain_damage_lines.json#L55

2018-02-08 20:16 UTC, merged