borers can no longer force their hosts to commit suicide
yogstation13/yogstation-2017- pull request #3097
Opened 2018-02-09 05:52 UTC by ShadowDeath6

:cl: ShadowDeath6
bugfix: Borers can no longer force their hosts to suicide
/:cl:

I don't actually know if the previous fix worked because I didn't bother to test it, this does though

compiling took longer than coding or testing this

2018-02-09 06:09 UTC, Smudged commented
Thanks shadow, the reign of nick ends

2018-02-09 14:43 UTC, AsV9 requested changes
Looks good, but I felt like being a grammar nazi.

2018-02-09 14:43 UTC, AsV9 commented on code/modules/client/verbs/suicide.dm
> +		to_chat(src, "Something is preventing you from suiciding.")
I mean it doesn't really matter but it should be `commiting suicide` instead of `suiciding` because we generally treat suicide as a noun and not a verb.

2018-02-09 15:27 UTC, ShadowDeath6 commented on code/modules/client/verbs/suicide.dm
> +		to_chat(src, "Something is preventing you from suiciding.")
I can't edit while I'm not at home, feel free to do it yourself if you want to merge it asap, I'll fix it when I get home if not

2018-02-09 17:55 UTC, Nickvr628 commented
This is a bad PR. How will I keep my hosts from suppressing me if I cannot kill them the moment they put sugar in their mouths?

2018-02-17 08:57 UTC, ShadowDeath6 commented
bad pr

2018-05-20 08:57 UTC, closed without merging