brings back limited ammo for secborgs
yogstation13/yogstation-2017- pull request #841
Opened 2016-09-20 23:51 UTC by ShadowDeath6

disable my ass daddy

:cl: ShadowDeath6
rscadd: Due to loud outcry from Grayshirts Organized, NanoTrasen has reverted the upgrade providing their security cyborgs with unlimited disabler beams.
/:cl:

2016-09-21 19:16 UTC, X-TheDark commented on code/modules/projectiles/guns/energy/stun.dm
> +	SSobj.processing |= src
START_PROCESSING(SSobj, src)

2016-09-21 19:16 UTC, X-TheDark commented on code/modules/projectiles/guns/energy/stun.dm
> +	SSobj.processing.Remove(src)
STOP_PROCESSING(SSobj, src)

2016-09-21 19:16 UTC, X-TheDark commented on code/modules/projectiles/guns/energy/stun.dm
> +	SSobj.processing |= src
START_PROCESSING(SSobj, src)

2016-09-21 19:17 UTC, X-TheDark commented on code/modules/projectiles/guns/energy/stun.dm
> +	SSobj.processing.Remove(src)
STOP_PROCESSING(SSobj, src)

2016-09-21 19:17 UTC, X-TheDark commented on code/modules/projectiles/guns/energy/stun.dm
> +	SSobj.processing |= src
START_PROCESSING(SSobj, src)

2016-09-21 19:17 UTC, X-TheDark commented on code/modules/projectiles/guns/energy/stun.dm
> +	SSobj.processing.Remove(src)
STOP_PROCESSING(SSobj, src)

2016-09-21 19:18 UTC, X-TheDark requested changes
Change this

2016-09-21 22:54 UTC, ShadowDeath6 commented
I don't know how to fix reviews

2016-09-22 08:29 UTC, X-TheDark approved these changes

2016-09-22 08:30 UTC, X-TheDark approved these changes

2016-09-22 14:42 UTC, AdamElTablawy commented
i ded tag  pls

also BOOOO giving secborgs limited lasers BOOOO

2016-09-22 20:32 UTC, ShadowDeath6 commented
They still have infinite lasers

2016-09-23 19:23 UTC, ShadowDeath6 commented
It's been 24 hours

wake me up

2016-09-25 22:58 UTC, merged