adds a new lavaland chest item- A self-filling reagent bottle.
yogstation13/yogstation-2017- pull request #926
Opened 2016-10-01 03:21 UTC by ShadowDeath6

I said I would do it

this replaces the armblade nullrod because fuck nodrop items as miner

also makes sal acid have the buffed healing for longer, 25 damage vs the previous 50

:cl: ShadowDeath6
rscadd: Added a new item to lavaland chests: The self-refilling bottle. It slowly regenerates the chemical it starts with. However, the contents of the bottle might not be as useful as expected!
rscdel: Removes the armblade nullrod from lavaland chests.
tweak :Buffs Salicyclic Acid.
/:cl:

as always, someone ruin the fun by leaving an unremovable comment on where I put the list of reagents.

2016-10-01 03:33 UTC, X-TheDark commented
Might want to update Oxaladrone threshold to 25 as well, so they are both at least consistent. Not sure about how both of these changes are balance-wise, will leave feedback later.

2016-10-01 08:51 UTC, killerx09 commented
Remove normal blood from the list, and this will be fine

2016-10-01 10:36 UTC, oisin100 requested changes
Just some stuff that doesnt fit out coding requirements.

2016-10-01 10:36 UTC, oisin100 commented on code/modules/reagents/reagent_containers/bottle.dm
> +	randomchem = pick("synaptizine","oxandrolone","pen_acid","blood","antitoxin","ephedrine","earthsblood","sal_acid","amatoxin","toxin","tirizene","neurotoxin2","morphine","heparin")
Define this list as a variable in the constructor so we dont have to copypaste the `New()` proc if we ever wanted to create a subtype of the refilling bottle.

2016-10-01 10:36 UTC, oisin100 commented on code/modules/reagents/reagent_containers/bottle.dm
> +	START_PROCESSING(SSobj, src)
Why?

2016-10-01 10:36 UTC, oisin100 commented on code/modules/reagents/reagent_containers/bottle.dm
> +	STOP_PROCESSING(SSobj, src)
Why?

2016-10-01 10:36 UTC, oisin100 commented on code/modules/reagents/reagent_containers/bottle.dm
> +		reagents.add_reagent(randomchem, 1)
Random numbers!!!!!!
Define the `1` as a define or even better as a variable inside the constructor!

2016-10-01 10:37 UTC, oisin100 commented on code/modules/reagents/reagent_containers/bottle.dm
> +		reagents.add_reagent(randomchem, 1)
Magic Numbers*

2016-10-01 16:15 UTC, ShadowDeath6 commented on code/modules/reagents/reagent_containers/bottle.dm
> +		reagents.add_reagent(randomchem, 1)
it fills the bottle with one chem per tick

2016-10-01 16:16 UTC, ShadowDeath6 commented on code/modules/reagents/reagent_containers/bottle.dm
> +	STOP_PROCESSING(SSobj, src)
because it processes

2016-10-01 16:17 UTC, ShadowDeath6 commented
Blood is intended for blood loss, not everything needs to be super healing or super poison

2016-10-01 16:42 UTC, ShadowDeath6 commented on code/modules/reagents/reagent_containers/bottle.dm
> +	randomchem = pick("synaptizine","oxandrolone","pen_acid","blood","antitoxin","ephedrine","earthsblood","sal_acid","amatoxin","toxin","tirizene","neurotoxin2","morphine","heparin")
not able to put pick() lists in the constructor so I'm not sure what you want me to do with this

2016-10-01 18:25 UTC, puremanbird commented
is that... is that a chemistry buff??

2016-10-01 18:42 UTC, Super3222 commented
> is that... is that a chemistry buff??

a mix between a chem and lavaland buff.

2016-10-01 21:20 UTC, oisin100 commented on code/modules/reagents/reagent_containers/bottle.dm
> +	randomchem = pick("synaptizine","oxandrolone","pen_acid","blood","antitoxin","ephedrine","earthsblood","sal_acid","amatoxin","toxin","tirizene","neurotoxin2","morphine","heparin")
Put a list in the constructor then pick from it in the `New()`, picking a random reagent will aways work the same way, but what it can pick from may differ depending on subtypes.

2016-10-01 21:22 UTC, oisin100 commented on code/modules/reagents/reagent_containers/bottle.dm
> +	STOP_PROCESSING(SSobj, src)
I realize that, But objects run this code automatically, you dont need to add it to SSObj twice, Infact you might even be causing it to update twice per tick this way.

2016-10-01 21:22 UTC, Time-Green commented
Add colorful reagent to the list!

2016-10-01 21:23 UTC, oisin100 commented on code/modules/reagents/reagent_containers/bottle.dm
> +		reagents.add_reagent(randomchem, 1)
Yes, But `1` is still a magic number, If we decided to create a subtype which filled the bottle up with lets say 5 chem per tick we dont want to have to copy paste the `process()` code.

2016-10-01 21:24 UTC, oisin100 commented
> Add colorful reagent to the list!

Careful time, Shadow has an allergic reaction to colorful reagent.

2016-10-01 21:59 UTC, oisin100 commented on code/modules/reagents/reagent_containers/bottle.dm
> +	STOP_PROCESSING(SSobj, src)
Nevermind, Apparently its only machinery that have this in their constructor.

2016-10-01 23:33 UTC, ShadowDeath6 commented
fuck meme reagents, leave it to chem for the actual useless chems

This is not a chem buff in any way, not sure how you'd come to that solution

2016-10-01 23:52 UTC, X-TheDark commented on code/modules/reagents/reagent_containers/bottle.dm
> +	randomchem = pick("synaptizine","oxandrolone","pen_acid","blood","antitoxin","ephedrine","earthsblood","sal_acid","amatoxin","toxin","tirizene","neurotoxin2","morphine","heparin")
To be more concrete, define a var on this thing, something like
`var/list/pickable_chems = list("your", "list", "of", "stuff")`

Then, in `New()`, do
`randomchem = pick(pickable_chems)`

2016-10-02 00:01 UTC, Super3222 commented
> This is not a chem buff in any way, not sure how you'd come to that solution

Your changelog.

2016-10-02 00:04 UTC, ShadowDeath6 commented on code/modules/reagents/reagent_containers/bottle.dm
> +	randomchem = pick("synaptizine","oxandrolone","pen_acid","blood","antitoxin","ephedrine","earthsblood","sal_acid","amatoxin","toxin","tirizene","neurotoxin2","morphine","heparin")
thank

2016-10-02 00:04 UTC, ShadowDeath6 commented
orite :^)

2016-10-02 00:17 UTC, oisin100 approved these changes

2016-10-02 00:18 UTC, oisin100 commented
Hm, Strange, The changelog checker isnt adding a status flag..

2016-10-06 23:19 UTC, merged